# -*- coding: utf-8 -*-
"""Level 2 addOffsets.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WpJATncW51HIaAEeqi0y5oV80PAYgPT4

Note: you may not use `for` or `while` loops here.
Instead, use recursion.
  
  

With that in mind, write the recursive function `addOffsets(offsets, L)`
that takes two lists of integers, offsets and L, and returns a copy of L
where each value in L has the corresponding offset added to it. If you
run out of offsets (if there are more values in L than offsets), then you
should start again at the beginning of the offsets list.
  
  

For example, to compute `addOffsets([1,2],[10,20,30,40,50])`:
1. Add 1 to 10 to get 11\.
2. Add 2 to 20 to get 22\.
3. We have run out of offsets, so start over, so add 1 to 30 to get 31\.
4. Add 2 to 40 to get 42\.
5. Add 1 to 50 to get 51\.


Thus, the result is `[11,22,31,42,51]`.
  
  

Here are some more test cases:

```
assert(addOffsets([1,2],[10,20,30,40,50]) == [11,22,31,42,51])
assert(addOffsets([1,2,3],[10,20,30,40,50,60,70]) == [11,22,33,41,52,63,71])
assert(addOffsets([1,2,3],[10,20]) == [11,22])
assert(addOffsets([1],[10,20]) == [11,21])
assert(addOffsets([1],[10]) == [11])
assert(addOffsets([1],[ ]) == [ ])
```

  
  

Hint: we suggest that you rotate the offsets by one to the left on each
recursive call.
For example, if the offsets are \[1,2,3] on some call, then you should use
offsets of \[2,3,1]. In this way, you will always use the next offset,
and you will never run out of offsets.
"""

def addOffsets(offsets, L):
    return 42

def testAddOffsets():
    print('Testing addOffsets()...', end='')
    assert(addOffsets([1,2],[10,20,30,40,50]) == [11,22,31,42,51])
    assert(addOffsets([1,2,3],[10,20,30,40,50,60,70]) == [11,22,33,41,52,63,71])
    assert(addOffsets([1,2,3],[10,20]) == [11,22])
    assert(addOffsets([1],[10,20]) == [11,21])
    assert(addOffsets([1],[10]) == [11])
    assert(addOffsets([1],[ ]) == [ ])
    print('Passed!')

def main():
    testAddOffsets()

main()