# -*- coding: utf-8 -*-
"""Level 2 deMeresProblem.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zUkikXzmtIY-wae5N6o-WY09dV5T5zy3

Background: According to [here](https://mathworld.wolfram.com/deMeresProblem.html) (among many sources),
the French nobleman Chevalier de Méré proposed to his friend
(and famous mathematician) Blaise Pascal that
the probability of getting at least one 6 in four rolls of a single 6\-sided die is
greater than the probability of at least one double\-six in 24 throws of two dice.
  
  

Unfortunately, de Méré was unable to prove this. Fortunately, his friend Pascal
was a world\-class mathematician and could. In fact, Pascal showed
that:
1. The probability of getting at least one 6 in four rolls of a single 6\-sided die is about 0\.5177, and
2. The probability of at least one double\-six in 24 throws of two dice is about 0\.4914\.
	* Note that here we roll two dice each time. For one trial, we repeat
	 this (rolling two dice) 24 times. The trial succeeds if any
	 of those 24 two\-dice rolls was a double\-six.


Your task here is to use Monte Carlo Methods to confirm both of Pascal's
conclusions, and thus to confirm de Méré was correct, even if he
could not prove so himself.
  
  

We already wrote the estimateProbability functions for you.
Look them over and be sure you understand them!
Here, you just need to write the runOneTrial functions.
  
  

To be more precise, write the following two functions:
* runOneTrial1()
	+ This runs one trial for the first case, succeeding if we
	 get at least one 6 in four rolls of a single
	 6\-sided die, and
  
* runOneTrial2()
	+ This runs one trial for the second case, succeeding if we
	 get at least one double\-six in 24 throws of two dice.


To be correct, your results need to be within reasonably close bounds
to the known answer with large enough numbers of trials. See the test
function for details.
  
  

Good luck!
"""

import random

def rollDie():
    return random.randrange(1, 7)

def runOneTrial1():
    # success = getting at least one 6 in four rolls of a single 6-sided die
    # note that we provided the rollDie() function for you (see above).
    pass

def runOneTrial2():
    # getting at least one double-six in 24 throws of two dice
    # note that we provided the rollDie() function for you (see above).
    pass

def estimateProbability1(trials):
    successes = 0
    for _ in range(trials):
        success = runOneTrial1()
        if success:
            successes += 1
    return successes / trials

def estimateProbability2(trials):
    successes = 0
    for _ in range(trials):
        success = runOneTrial2()
        if success:
            successes += 1
    return successes / trials

def testDeMeresProblem():
    print('Testing both parts of deMeres Problem...', end='')
    trials = 10**5
    p1 = estimateProbability1(trials)
    assert(0.510 <= p1 <= 0.525) # actual answer is about 0.518

    p2 = estimateProbability2(trials)
    assert(0.485 <= p2 <= 0.495) # actual answer is about 0.491
    print('Passed!')

def main():
    testDeMeresProblem()

main()