# -*- coding: utf-8 -*-
"""Level 2 antiPokerProblem.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q8c6NKsqG0UhmG4KS772wAW9sfvoCbcR

This problem is inspired by
[this page](https://www.math.cmu.edu/~cargue/arml/archive/15-16/probability-04-03-16-solutions.pdf) of probability problems.
  
  

That page explains 3\-card anti\-poker, where the goal is to not make good poker hands. It asks: What is the probability that a random hand of 3 cards from a 52 card deck has cards of not all the same suit and does not contain a pair (same rank)? That is, the hand contains at least 2 suits and 3 different ranks.
  
  

That page shows that this probability is exactly 66/85, or about 0\.7765\.
  
  

Your task here is to use Monte Carlo methods to estimate this probability.
  
  

More specifically, write the function estimateProbability(trials) that
runs the given number of trials, where each trial succeeds if it draws
3 cards from a 52 card deck and the cards are not all the same suit and do not contain a pair (same rank).
  
  

To be judged correct, you need to be reasonably close to the actual answer
as the number of trials increases. See the test code for details.
  
  

Also, note that the helper functions makeDeck() and dealCard(deck) have been provided for you.
  
  

Good luck!
"""

import random

def makeDeck():
    deck = [ ]
    for rank in 'A23456789TJQK':
        for suit in 'CDHS':
            deck.append((rank, suit))
    random.shuffle(deck)
    return deck

def dealCard(deck):
    return deck.pop()

def runOneTrial():
    # success = draw 3 cards from a 52 card deck and the cards are
    # not all the same suit and do not contain a pair (same rank).
    pass

def estimateProbability(trials):
    pass

def testAntiPokerProblem():
    print('Testing the antiPoker Problem...', end='')
    trials = 10**5
    p = estimateProbability(trials)
    assert(0.75 <= p <= 0.80) # actual answer is about 0.7765
    print('Passed!')

def main():
    testAntiPokerProblem()

main()