# -*- coding: utf-8 -*-
"""Level 2 betterWordSearch1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CvcPR_aBUHrAlXyhSiNi9Bwjd1KvPe4X

Background: This version of `wordSearch(board, word)` returns more information about each word \-\-
 the function returns a string that includes whether the word was found,
 where the word was found, and in what direction.

 Here are some examples:

```

board = [ [ 'd', 'o', 'g' ],
          [ 't', 'a', 'c' ],
          [ 'w', 'a', 't' ],
          [ 'u', 'r', 'b' ] ]
assert(wordSearch(board, 'dog') ==
    "'dog' is at (0, 0) heading right")
assert(wordSearch(board, 'cat') ==
    "'cat' is at (1, 2) heading left")
assert(wordSearch(board, 'bat') ==
    "'bat' is at (3, 2) heading up-left")
assert(wordSearch(board, 'tab') ==
    "'tab' is at (1, 0) heading down-right")
assert(wordSearch(board, 'wag') ==
    "'wag' is at (2, 0) heading up-right")
assert(wordSearch(board, 'cow') == "'cow' not found")
assert(wordSearch(board, 'dab') == "'dab' not found")
assert(wordSearch(board, 'goat') == "'goat' not found")
```



 If a word occurs more than once on the board, you can choose whichever one
 you want to return.




 With this in mind, write the function `wordSearch(board, word)`, which takes
 a rectangular 2d list `board`, where each value in
 the board is a single lowercase letter, and `word`,
 which is a string of lowercase letters, and returns a string as outlined above.





 Hint: We found it helpful to put the names of the directions in a 2d list
 like so:

```
dirNames = [ [ 'up-left'  ,  'up' , 'up-right'   ],
             [ 'left'     ,   ''  , 'right'      ],
             [ 'down-left', 'down', 'down-right' ] ]
```
"""

def wordSearch(board, word):
    directions = [(-1, -1), (-1, 0), (-1, 1),
                  (0, -1),          (0, 1),
                  (1, -1), (1, 0), (1, 1)]
    dirNames = [ [ 'up-left'  ,  'up' , 'up-right'   ],
                 [ 'left'     ,   ''  , 'right'      ],
                 [ 'down-left', 'down', 'down-right' ] ]
    
    rows = len(board)
    cols = len(board[0]) if rows > 0 else 0
    
    for r in range(rows):
        for c in range(cols):
            for d in directions:
                dr, dc = d
                rr, cc = r, c
                match = True
                for i in range(len(word)):
                    if rr < 0 or rr >= rows or cc < 0 or cc >= cols or board[rr][cc] != word[i]:
                        match = False
                        break
                    rr += dr
                    cc += dc
                if match:
                    dir_name = dirNames[dr + 1][dc + 1]
                    return f"'{word}' is at ({r}, {c}) heading {dir_name}"
    return f"'{word}' not found"

def testWordSearch():
    print('Testing wordSearch()...', end='')
    board = [ [ 'd', 'o', 'g' ],
              [ 't', 'a', 'c' ],
              [ 'w', 'a', 't' ],
              [ 'u', 'r', 'b' ] ]
    assert(wordSearch(board, 'dog') == "'dog' is at (0, 0) heading right")
    assert(wordSearch(board, 'cat') == "'cat' is at (1, 2) heading left")
    assert(wordSearch(board, 'bat') == "'bat' is at (3, 2) heading up-left")
    assert(wordSearch(board, 'tab') == "'tab' is at (1, 0) heading down-right")
    assert(wordSearch(board, 'wag') == "'wag' is at (2, 0) heading up-right")
    assert(wordSearch(board, 'cow') == "'cow' not found")
    assert(wordSearch(board, 'dab') == "'dab' not found")
    assert(wordSearch(board, 'goat') == "'goat' not found")
    assert(wordSearch(board, 'www') == "'www' not found")
    print('Passed!')

def main():
    testWordSearch()

main()