# -*- coding: utf-8 -*-
"""Level 1 isRectangular.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12E7lSX-8KfhbZwXH_J1EEiWdFYdatENF

Background: We say a 2d list is rectangular if every row is the same length. For example, a 2d
 list with 3 rows that each have 2 elements is rectangular.




 With this in mind, write the function `isRectangular(L)` which takes a 2d list `L` and returns `True` if the
 2d list is rectangular.
 Return `False` otherwise.
"""

def isRectangular(L):
    if len(L) == 0:
        return True
    row_length = len(L[0])
    for row in L:
        if len(row) != row_length:
            return False
    return True

def testIsRectangular():
    print('Testing isRectangular()...', end='')
    L = [[1, 2, 3],
         [4, 5, 6]]
    assert(isRectangular(L) == True)
    L = [[1, 2],
         [4, 5, 6]]
    assert(isRectangular(L) == False)
    L = [[1,  2,  3,  4],
         [5,  6,  7,  8],
         [9, 10, 11, 12]]
    assert(isRectangular(L) == True)
    print('Passed!')

def main():
    testIsRectangular()

main()