# -*- coding: utf-8 -*-
"""4 - Problem Solving with Python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jD9nRX52eQrP40m4LkFfNKok4Ai1gF6c

<font size="1" color="#AAA">Python Fundamentals &copy; David Kosbie</font>  

# Problem Solving with Python
Here we review how to be an effective problem solver in Python.
Follow these steps closely and carefully.
<br><br>
**Problem-Solving with Python:**

  1. Read the problem carefully
      * Take your time with this step
      
      * Clarify any confusions before you start!
    
  2. Study the test cases carefully
      * If a test function seems confusing or wrong,
        you have to clarify that now, before you start solving the problem!
        
      * You can add your own test cases to be sure your test
        functions cover all the important cases

  3. Design your algorithm
      * Solve the problem without Python

      * Use *Top-Down Design* (break down the problem into smaller problems)
      
      * Do not *hardcode* the test cases!
      
        * Your solution must work in general, and not just
          for the supplied test cases.
    
  4. Write your code using top-down design
      * Translate your algorithm into Python

      * Use helper functions

      * Always use good style

  5. Test and Debug your code
      * Each function should have its own test function
      
      * Do not assume that a function is too simple for a test function

      * Test your helper functions *before* you use them

In fact, we have already used these steps in earlier worked examples.
Now we are just being more explicit about them.<br>
You should these same steps in all your problem-solving with code
from this point forward.
"""