# -*- coding: utf-8 -*-
"""isPalindromicList.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DSYhPQZbvSjPAmXs_tiI6gzucuRSWSwg

```
# This is formatted as code
```



 Write the non\-mutating function `isPalindromicList(L)` which takes
 a `list` `L` and returns `True` if it is the
 same forwards as backwards, and `False` otherwise.
"""

def isPalindromicList(L):
    for i in range(len(L) // 2):
        if L[i] != L[-(i + 1)]:
            return False
    return True

def testIsPalindromicList():
    print('Testing isPalindromicList()...', end='')
    assert(isPalindromicList([1, 2, 2, 1]) == True)
    assert(isPalindromicList([1, 2, 3, 1]) == False)
    assert(isPalindromicList([1]) == True)
    assert(isPalindromicList([5.0, -1, True, 'hey', True, -1, 5.0]) == True)
    assert(isPalindromicList([0, 'hi', False, False, 4.0]) == False)
    assert(isPalindromicList([]) == True)

    # Verify function is non-mutating
    L = [1, 2, 1]
    assert(isPalindromicList(L) == True)
    assert(L == [1, 2, 1])

    L = [1, 9, 8]
    assert(isPalindromicList(L) == False)
    assert(L == [1, 9, 8])
    print('Passed!')

def main():
    testIsPalindromicList()

main()