# -*- coding: utf-8 -*-
"""Level 1 isRotation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rX2luqExtaHQGdOYbDUydFYu2tu3XeSI

Background: A rotation of a `list` `L` is constructed by shifting elements from one end of
 the list to the other. For example, `[2, 3, 4, 5, 6]` rotated once to the right is
 `[6, 2, 3, 4, 5]`. If you continue rotating this list to the right, you get
 `[5, 6, 2, 3, 4]`, `[4, 5, 6, 2, 3]`, and so on.




 With this in mind, write the function `isRotation(L, M)` which takes two lists `L`
 and `M`, and returns `True` if `M` is a rotation
 of `L` and `False` otherwise.




 Note: A list is a rotation of itself.
"""

def isRotation(L, M):
    if len(L) != len(M):
        return False
    if len(L) == 0:
        return True
    for i in range(len(L)):
        if L == M:
            return True
        M = [M[-1]] + M[:-1]
    return False

def testIsRotation():
    print('Testing isRotation()...', end='')
    assert(isRotation([2, 3, 4, 5, 6], [4, 5, 6, 2, 3]) == True)
    assert(isRotation([2, 3, 4, 5, 6], [2, 3, 4, 5, 6]) == True)
    assert(isRotation([2, 3, 4, 5, 6], [2, 4, 3, 5, 6]) == False)
    assert(isRotation([1], []) == False)
    assert(isRotation([], []) == True)
    print('Passed!')

def main():
    testIsRotation()

main()