# -*- coding: utf-8 -*-
"""Level 1 insertRowAndCol_(mutating_and_nonmutating).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UX1usljpM_ChAAkjcUNn1O689NhDIlgL

Write the function
 `mutatingInsertRowAndCol(L, row, col, val)` which takes a
 rectangular 2d list `L`, and inserts one new row and one new
 column at the locations specified by `row` and
 `col`. The cells in the new row and column are all set to
 `val`.




 For example, if `L` is the following list:


```

[[1,  2,  3,  4],
 [5,  6,  7,  8],
 [9, 10, 11, 12]]
```


 Then after calling `mutatingInsertRowAndCol(L, 1, 2, 42)`,
 `L` should be equal to:


```

[[ 1,  2, 42,  3,  4],
 [42, 42, 42, 42, 42],
 [ 5,  6, 42,  7,  8],
 [ 9, 10, 42, 11, 12]]
```


 In the example above, a row is inserted at index `1`, and a column is
 inserted at index `2`. All the values in the inserted row and column are
 set to `42`. As with most mutating functions, this function returns
 `None`.




 You are guaranteed that `row` and `col` will be
 valid indexes for `L`.




 Also write the function
 `nonmutatingInsertRowAndCol(L, row, col, val)`,
 which works the same as the previous function, only this version is
 non\-mutating. It does not modify `L`, and it returns a new
 list with the specified row and column added.

 Note: You may not call
 `mutatingInsertRowAndCol(L, row, col, val)` in
 `nonmutatingInsertRowAndCol(L, row, col, val)`. Instead, you
 need to build up a new list from scratch in the non\-mutating version.
"""

def mutatingInsertRowAndCol(L, row, col, val):
     # Insert the new column
     for r in range(len(L)):
          L[r].insert(col, val)
     
     # Insert the new row
     new_row = [val] * len(L[0])
     L.insert(row, new_row)

def nonmutatingInsertRowAndCol(L, row, col, val):
    new_list = []
    for r in range(len(L)):
        new_row = L[r][:col] + [val] + L[r][col:]
        new_list.append(new_row)
    new_list.insert(row, [val] * (len(L[0]) + 1))
    return new_list

def testMutatingInsertRowAndCol():
    print('Testing mutatingInsertRowAndCol()...', end='')
    L = [[1,  2,  3,  4],
         [5,  6,  7,  8],
         [9, 10, 11, 12]]
    mutatingInsertRowAndCol(L, 1, 2, 42)
    assert(L == [[ 1,  2, 42,  3,  4],
                 [42, 42, 42, 42, 42],
                 [ 5,  6, 42,  7,  8],
                 [ 9, 10, 42, 11, 12]])

    L = [[1, 2, 3],
         [4, 5, 6]]
    mutatingInsertRowAndCol(L, 0, 0, 5)
    assert(L == [[5, 5, 5, 5],
                 [5, 1, 2, 3],
                 [5, 4, 5, 6]])

    L = [[1, 2, 3],
         [4, 5, 6]]
    mutatingInsertRowAndCol(L, 1, 3, 5)
    assert(L == [[1, 2, 3, 5],
                 [5, 5, 5, 5],
                 [4, 5, 6, 5]])

def testNonmutatingInsertRowAndCol():
    print('Testing nonmutatingInsertRowAndCol()...', end='')
    L = [[1,  2,  3,  4],
         [5,  6,  7,  8],
         [9, 10, 11, 12]]
    assert(nonmutatingInsertRowAndCol(L, 1, 2, 42) == [[ 1,  2, 42,  3,  4],
                                                       [42, 42, 42, 42, 42],
                                                       [ 5,  6, 42,  7,  8],
                                                       [ 9, 10, 42, 11, 12]])

    L = [[1, 2, 3],
         [4, 5, 6]]
    assert(nonmutatingInsertRowAndCol(L, 0, 0, 5) == [[5, 5, 5, 5],
                                                      [5, 1, 2, 3],
                                                      [5, 4, 5, 6]])

    L = [[1, 2, 3],
         [4, 5, 6]]
    assert(nonmutatingInsertRowAndCol(L, 1, 3, 5) == [[1, 2, 3, 5],
                                                      [5, 5, 5, 5],
                                                      [4, 5, 6, 5]])

    # Verify that the function is non-mutating
    L = [[1,  2,  3,  4],
         [5,  6,  7,  8],
         [9, 10, 11, 12]]
    nonmutatingInsertRowAndCol(L, 1, 2, 42)
    assert(L == [[1,  2,  3,  4],
                 [5,  6,  7,  8],
                 [9, 10, 11, 12]])
    print('Passed!')

def main():
    testMutatingInsertRowAndCol()
    testNonmutatingInsertRowAndCol()

main()