# -*- coding: utf-8 -*-
"""Level 1 largestColumnSum.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GmQckXhmXuMjBWDfAg2M0k8ovkGLGbkZ

Write the function largestColumnSum(L) that takes a non\-empty rectangular 2d list
of ints L and returns the largest sum of any column in L.
  
  

For example:

```

    L = [ [ 1, 2, 3 ],
          [ 4, 5, 6 ] ]
    assert(largestColumnSum(L) == 9) # sum([3, 6])

    L = [ [ 1,  2,  3 ],
          [ 4,  5,  6 ],
          [ 7, -1, -2 ] ]
    assert(largestColumnSum(L) == 12) # sum([1, 4, 7])

    L = [ [ 7, -1, -2 ] ]
    assert(largestColumnSum(L) == 7) # sum([7])

```
"""

def largestColumnSum(L):
    max_sum = float('-inf')
    num_cols = len(L[0])
    num_rows = len(L)

    for col in range(num_cols):
        col_sum = 0
        for row in range(num_rows):
            col_sum += L[row][col]
        if col_sum > max_sum:
            max_sum = col_sum

    return max_sum

def testLargestColumnSum():
    print('Testing largestColumnSum()...', end='')
    L = [ [ 1, 2, 3 ],
          [ 4, 5, 6 ] ]
    assert(largestColumnSum(L) == 9) # sum([3, 6])

    L = [ [  3,  2,  1 ],
          [ -5, -3, -6 ] ]
    assert(largestColumnSum(L) == -1) # sum([2, -3])

    L = [ [ 1,  2,  3 ],
          [ 4,  5,  6 ],
          [ 7, -1, -2 ] ]
    assert(largestColumnSum(L) == 12) # sum([1, 4, 7])

    L = [ [ 7, -1, -2 ] ]
    assert(largestColumnSum(L) == 7) # sum([7])
    print('Passed!')

def main():
    testLargestColumnSum()

main()