# -*- coding: utf-8 -*-
"""Level 1 repeats.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NIv36LC5hZmN1uLziO1ms2BLiPWhs0Hg

#### Problem Writeup



 Write the function `repeats(L)` which takes a `list`
`L` and returns a sorted list of all the repeated elements
 in `L`.




 For example, if `L = [1,2,3,2,1]`, then the repeated elements
 are 2 and 1\. We return a sorted list of these elements, so
 `repeats([1,2,3,2,1]) == [1, 2]`.




 Note: Recall that in this unit, you cannot create new lists
 or mutate existing lists. Instead, think of a clever way to use
 sets to solve the problem.




 Hints:
 1. You may want to use two sets here as you loop over all
 the values in the `list` `L` \-\- one set to keep
 track of the values you have already seen at least once,
 and another set to keep track of the values you have
 seen at least twice (that is, the duplicates in `L`).
2. Recall that you can use `sorted(s)` here to convert
 a set into a sorted list of the values in that set.





#### Guided Solution
"""

def repeats(L):
    seen = set()
    duplicates = set()
    for value in L:
        if value in seen:
            duplicates.add(value)
        else:
            seen.add(value)
    return sorted(duplicates)

def testRepeats():
    print('Testing repeats()...', end='')
    assert(repeats([1,2,3,2,1]) == [1,2])
    assert(repeats([1,2,3,2,2,4]) == [2])
    assert(repeats([1,5,3,5,2,3,2,1]) == [1,2,3,5])
    assert(repeats([7,9,1,3,7,1]) == [1,7])
    assert(repeats(list(range(100))) == [ ])
    assert(repeats(list(range(100))*5) == list(range(100)))

    # Verify that the function is nonmutating:
    L = [1,2,3,2,1]
    repeats(L)
    assert(L == [1,2,3,2,1])
    print('Passed!')

def main():
    testRepeats()

main()