# -*- coding: utf-8 -*-
"""Level 1 BothLists.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tpdtvjsH6iSX6LSIlpCEcD-O87ZM5yQH

Write the function `inBothLists(L, M)` which takes two lists
 `L` and `M`, and returns a sorted list of all
 the values that occur in both lists.




 For example, `inBothLists([1,2,3],[3,2,4])` returns
 `[2, 3]` because `3` and `2` are the elements which appear
 in both lists, so we return the sorted list `[2, 3]`.




 Note: Recall that in this unit, you cannot create new lists or
 mutate existing lists. Instead, think of a clever way to use sets to
 solve the problem.
"""

def inBothLists(L, M):
    return sorted(set(L) & set(M))

def testInBothLists():
    print('Testing inBothLists()...', end='')
    assert(inBothLists([1,2,3],[3,2,4]) == [2,3])
    assert(inBothLists([3,2,1],[4,1,2,1]) == [1,2])
    assert(inBothLists([3,2,1,2],[2,2,2]) == [2])
    assert(inBothLists([1,2,3],[4,5,6,1]) == [1])
    assert(inBothLists([3,2,1,2],[4]) == [])

    # Verify that the function is nonmutating:
    L = [1,2,3]
    M = [3,2,4]
    inBothLists(L, M)
    assert(L == [1,2,3] and M == [3,2,4])
    print('Passed!')

def main():
    testInBothLists()

main()