# -*- coding: utf-8 -*-
"""Level 1 isPermutation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18SacNOyGBUy8ALSqr6d-tcQbykqNUMV3

Background: A permutation of a `list` `L` is a list which
 contains the same elements as `L`, but in any order. For
 example, the following lists are all the permutations of
 `[1, 2, 3]`:

```

[1, 2, 3]
[1, 3, 2]
[2, 1, 3]
[2, 3, 1]
[3, 1, 2]
[3, 2, 1]
```





 With this in mind, write the function `isPermutation(L)`,
 which takes a `list` `L`, and returns `True` if
 `L` is a permutation of the list of numbers from `0` to
 `(n - 1)` inclusive, and `False` otherwise. `n` is the length of
 `L`.




 Note: Recall that in this unit, you cannot create new lists or
 mutate existing lists. Instead, think of a clever way to use sets to
 solve the problem.
"""

def isPermutation(L):
    return set(L) == set(range(len(L)))

def testIsPermutation():
    print('Testing isPermutation()...', end='')
    assert(isPermutation([0,2,1,4,3]) == True)
    assert(isPermutation([1,3,0,4,2]) == True)
    assert(isPermutation([1,3,5,4,2]) == False)
    assert(isPermutation([1,4,0,4,2]) == False)

    # Verify that the function is nonmutating:
    L = [0,2,1,4,3]
    isPermutation(L)
    assert(L == [0,2,1,4,3])
    print('Passed!')

def main():
    testIsPermutation()

main()