# -*- coding: utf-8 -*-
"""Level 2 betterWordSearch2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TJS88f5QsifPCBMIFifvWyf67OTSAZ4e

Background: This version of `wordSearch(board, word)` builds on
 `betterWordSearch1`. Now we also allow for
 wildcards. In particular, the board and the word can each contain
 `'?'` characters, which match any single character.
 For example, `'c?t'` matches `'cat'` or
 `'cot'` but not `'cart'` or `'act'`.




 Here is a sample board with wildcards, and some sample words with wildcards:

```
board = [ [ 'd', '?', 'g' ],
          [ 't', '?', 'c' ],
          [ 'w', 'a', 't' ],
          [ 'u', 'r', 'b' ] ]
assert(wordSearch(board, 'dog') ==
    "'dog' is at (0, 0) heading right")
assert(wordSearch(board, 'dig') ==
    "'dig' is at (0, 0) heading right")
assert(wordSearch(board, 'ant') ==
    "'ant' is at (2, 1) heading up")
assert(wordSearch(board, 'cat') ==
    "'cat' is at (1, 2) heading left")
assert(wordSearch(board, 'u?b') ==
    "'u?b' is at (3, 0) heading right")
assert(wordSearch(board, 'wag') ==
    "'wag' is at (2, 0) heading up-right")
assert(wordSearch(board, 'cow') == "'cow' not found")
assert(wordSearch(board, 'dab') == "'dab' not found")
assert(wordSearch(board, 'goat') == "'goat' not found")
```





 With this in mind, write the function `wordSearch(board, word)`, which takes
 a rectangular 2d list `board`, where each value in
 the board is a single lowercase letter or a wildcard letter, and `word`,
 which is a string of lowercase letters possibly containing a wildcard letter,
 and returns a descriptive string as outlined above.
"""

def wordSearch(board, word):
    return 42

def testWordSearch():
    print('Testing wordSearch()...', end='')
    board = [ [ 'd', '?', 'g' ],
              [ 't', '?', 'c' ],
              [ 'w', 'a', 't' ],
              [ 'u', 'r', 'b' ] ]
    assert(wordSearch(board, 'dog') == "'dog' is at (0, 0) heading right")
    assert(wordSearch(board, 'dig') == "'dig' is at (0, 0) heading right")
    assert(wordSearch(board, 'ant') == "'ant' is at (2, 1) heading up")
    assert(wordSearch(board, 'cat') == "'cat' is at (1, 2) heading left")
    assert(wordSearch(board, 'u?b') == "'u?b' is at (3, 0) heading right")
    assert(wordSearch(board, 'wag') == "'wag' is at (2, 0) heading up-right")
    assert(wordSearch(board, 'cow') == "'cow' not found")
    assert(wordSearch(board, 'dab') == "'dab' not found")
    assert(wordSearch(board, 'goat') == "'goat' not found")
    assert(wordSearch(board, 'www') == "'www' not found")
    print('Passed!')

def main():
    testWordSearch()

main()