# -*- coding: utf-8 -*-
"""Level 2 lookAndSay_+_inverseLookAndSay.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sjC0KRFQdP-py4dV3M_WH9SwhhG4oMRt

Background: When "reading off" the values in a list using the
 look\-and\-say method, we describe how many consecutive occurrences
 of each value there are in the list, in order.




 For example, when reading off `[3,3,8,-10,-10,-10,3]` using the
 look\-and\-say method, in order from left\-to\-right the list contains
 two 3's, then one 8, then three \-10's, then one 3\. That is:


| Count | Value |
| --- | --- |
| 2 | 3 |
| 1 | 8 |
| 3 | \-10 |
| 1 | 3 |


 We can rewrite this as a list of tuples, like so:
 `[(2, 3), (1, 8), (3, -10), (1, 3)]`.
 This is the look\-and\-say representation of the original list.




 With this in mind, write the function `lookAndSay(L)`, which
 takes a list of integers `L`, and returns the list of
 `(count, value)` pairs constructed by reading `L` using the
 look\-and\-say method.
 Thus,
 `lookAndSay([3,3,8,-10,-10,-10,3]) == [(2, 3), (1, 8), (3, -10), (1, 3)])`




 Also write the function `inverseLookAndSay(L)` which does
 the inverse of the previous function. It takes a list of tuples
 representing the `(count, value)` pairs, and returns the original list.
 For example,
 `inverseLookAndSay([(2, 3), (1, 8), (3, -10), (1, 3)]) == [3,3,8,-10,-10,-10,3]`
"""

def lookAndSay(L):
    return 42

def inverseLookAndSay(L):
    return 42

def testLookAndSay():
    print('Testing lookAndSay()...', end='')
    assert(lookAndSay([3, 3, 8, -10, -10, -10, 3]) ==
                      [(2, 3), (1, 8), (3, -10), (1, 3)])
    assert(lookAndSay([1, 1, 0, 0, 1, 1, 1]) == [(2, 1), (2, 0), (3, 1)])
    assert(lookAndSay([-5, 5]) == [(1, -5), (1, 5)])
    assert(lookAndSay([6]) == [(1, 6)])
    assert(lookAndSay([]) == [])

    # Verify that the function is non-mutating
    L = [3, 3, 8, -10, -10, -10, 3]
    lookAndSay(L)
    assert(L == [3, 3, 8, -10, -10, -10, 3])

def testInverseLookAndSay():
    print('Testing inverseLookAndSay()...', end='')
    assert(inverseLookAndSay([(2, 3), (1, 8), (3, -10), (1, 3)]) ==
                             [3, 3, 8, -10, -10, -10, 3])
    assert(inverseLookAndSay([(2, 1), (2, 0), (3, 1)]) == [1, 1, 0, 0, 1, 1, 1])
    assert(inverseLookAndSay([(1, -5), (1, 5)]) == [-5, 5])
    assert(inverseLookAndSay([(1, 6)]) == [6])
    assert(inverseLookAndSay([]) == [])

    # Verify that the function is non-mutating
    L = [(2, 3), (1, 8), (3, -10), (1, 3)]
    inverseLookAndSay(L)
    assert(L == [(2, 3), (1, 8), (3, -10), (1, 3)])
    print('Passed!')

def main():
    testLookAndSay()
    testInverseLookAndSay()

main()