# -*- coding: utf-8 -*-
"""Level 4 getEvalSteps.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fsU7cXNVrg7pt-mAigqPDvwTsUmcs_8C

Write the function `getEvalSteps(expr)`
 that takes a string containing a simple arithmetic expression,
 and returns a multi\-line string containing the step\-by\-step
 (one operator at a time) evaluation of that expression.




 For example, `getEvalSteps('2+3*4-8**3%3')` will return the following (a single multi\-line string):




```

2+3*4-8**3%3 = 2+3*4-512%3
             = 2+12-512%3
             = 2+12-2
             = 14-2
             = 12

```


 You may assume the following constraints:
 1. Numbers are limited to non\-negative integers.
2. Operators are limited to `+`, `-`,
 `*`, `//`, `%`,
 and `**`.
3. All operators are binary, so they take two operands. There are
 no unary operators, meaning `'-5'` is not a legal
 input. For that, you'd need `'0-5'`.
4. The previous restriction is even stronger: no intermediate value
 of `expr` can be negative! So `'1-2+3'` is
 not legal, since it would be converted first into
 `'-1+3'` which is not legal. So you can safely ignore
 all such cases.
5. There are no parentheses.
6. Operators must be evaluated by precedence (`**`
 first, then `*`, `//`,
 `%`, then `+`, `-`).
7. Equal\-precedence operators are evaluated left\-to\-right. (`*`, `//`,
 `%` are equal\-precedent with each other, and `+`, `-`
 are equal\-precedent with each other).
8. Evaluation proceeds until a single integer with no operators
 remains after the equals sign.
9. The equal signs must all be stacked directly over each other.



 Hints:
 1. You may write this however you wish, though you may want to
 write a helper function that finds the next operator to be
 applied, and another helper function that applies a single
 operator. Top\-down design is crucial here. Don't forget to
 thoroughly test your helper functions before using them!
2. In our sample solution, we used very few string methods, just
 `find` and `isdigit`. You may use others,
 but you should not spin your wheels trying to find that awesome
 string method that will make this problem remarkably easier, as
 that method does not exist.
3. For this function, as any other function, you may not use the
 `eval` function. You will have to write your own
 equivalent just for the kinds of simple expressions you will
 deal with here. `eval` is dangerous and should be
 avoided, as it can lead to serious bugs or security
 vulnerabilities.
"""

def getEvalSteps(expr):
    

def testGetEvalSteps():
    print('Testing getEvalSteps()...', end='')
    print('Passed!')
    assert(getEvalSteps('2+3*4-8**3%3') == '''\
2+3*4-8**3%3 = 2+3*4-512%3
             = 2+12-512%3
             = 2+12-2
             = 14-2
             = 12
''')
    assert(getEvalSteps('2**2**3+4-2//3') == '''\
2**2**3+4-2//3 = 4**3+4-2//3
               = 64+4-2//3
               = 64+4-0
               = 68-0
               = 68
''')
    assert(getEvalSteps('4//2**2*8-3+2') == '''\
4//2**2*8-3+2 = 4//4*8-3+2
              = 1*8-3+2
              = 8-3+2
              = 5+2
              = 7
''')
    assert(getEvalSteps('2**4//2-3+1') == '''\
2**4//2-3+1 = 16//2-3+1
            = 8-3+1
            = 5+1
            = 6
''')

def main():
    testGetEvalSteps()

main()