# -*- coding: utf-8 -*-
"""Level 3 getCourse.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bY62rogujCsi0MqiV1aajwCBMq-F6QEG

Note: while you must use recursion here,
you may also use `for` or `while` loops
if you wish.
  
  

Background: we can represent a course catalog (of CMU courses, in this case)
as a list of lists, like so:

```
courseCatalog = ['CMU',
                    ['CIT',
                        [ 'ECE', '18-100', '18-202', '18-213' ],
                        [ 'BME', '42-101', '42-201' ],
                    ],
                    ['SCS',
                        [ 'CS',
                          ['Intro', '15-110', '15-112' ],
                          '15-122', '15-150', '15-213'
                        ],
                    ],
                    '99-307', '99-308'
                ]
```

Each list contains a label, such as 'CMU', or 'CIT', or 'ECE', followed either by
course short names (which are of the form '18\-100' or '15\-112') or
by sublists (which again contain a label followed by more course short names
or more sublists).
  
  

A course's full name includes all the labels that precede that course's
short name,
each followed by a dot ('.').
For example, 18\-100 is in the list labeled 'ECE', which is in
the list labeled 'CIT', which is in a list labeled 'CMU'.
Thus, the full name of 18\-100 is 'CMU.CIT.ECE.18\-100'.
  
  

With that in mind, write the recursive function
`getCourse(courseCatalog, course)`
that takes a course catalog as just described, along with
a course's short name (like '18\-100'), and returns that course's
full name (like 'CMU.CIT.ECE.18\-100'), or
None if the course is not in the catalog.
  
  

Here are more test cases, using the courseCatalog from above:

```
assert(getCourse(courseCatalog, '18-100') == 'CMU.CIT.ECE.18-100')
assert(getCourse(courseCatalog, '15-112') == 'CMU.SCS.CS.Intro.15-112')
assert(getCourse(courseCatalog, '15-213') == 'CMU.SCS.CS.15-213')
assert(getCourse(courseCatalog, '99-307') == 'CMU.99-307')
assert(getCourse(courseCatalog, '15-251') == None)
```

Hint:
* You may want to use `isinstance(value, list)` to
 test if the value is a list.
* Carefully watch the guided video!


#### Guided Solution
"""

def getCourse(courseCatalog, course):
    label = courseCatalog[0]
    for item in courseCatalog[1:]:
        if isinstance(item, list):
            subresult = getCourse(item, course)
            if subresult is not None:
                return label + '.' + subresult
        elif item == course:
            return label + '.' + course
    return None

def testGetCourse():
    print('Testing getCourse()...', end='')
    courseCatalog = ['CMU',
                        ['CIT',
                            [ 'ECE', '18-100', '18-202', '18-213' ],
                            [ 'BME', '42-101', '42-201' ],
                        ],
                        ['SCS',
                            [ 'CS',
                              ['Intro', '15-110', '15-112' ],
                              '15-122', '15-150', '15-213'
                            ],
                        ],
                        '99-307', '99-308'
                    ]
    assert(getCourse(courseCatalog, '18-100') == 'CMU.CIT.ECE.18-100')
    assert(getCourse(courseCatalog, '15-112') == 'CMU.SCS.CS.Intro.15-112')
    assert(getCourse(courseCatalog, '15-213') == 'CMU.SCS.CS.15-213')
    assert(getCourse(courseCatalog, '99-307') == 'CMU.99-307')
    assert(getCourse(courseCatalog, '15-251') == None)

    courseCatalog = ['SA',
                        ['CB', '10-100', '10-200',
                            ['DC', '20-300' ]
                        ]
                    ]
    assert(getCourse(courseCatalog, '10-100') == 'SA.CB.10-100')
    assert(getCourse(courseCatalog, '10-200') == 'SA.CB.10-200')
    assert(getCourse(courseCatalog, '20-300') == 'SA.CB.DC.20-300')
    assert(getCourse(courseCatalog, '30-400') == None)
    print('Passed!')

def main():
    testGetCourse()

main()