# -*- coding: utf-8 -*-
"""Level 4 semesterGrades.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fzVUycUuTz1FcsgSxHDaX717wlf8KKfP

Background: We will represent a gradebook as a multiline string like so:

```

gradebookText = '''\
student  hw1   hw2   hw3   hw4  quiz1   quiz2   quiz3  exam1  exam2
wilma     94    97    91    83     81      95      87    exc     94
fred      90    88    92    85     77      81      90     88     82
barney    75    83    71   exc     68      71      73     72     76
betty    100   100    99   100    exc      98      92     88    100'''

```

Note the following formatting details:
* The first row contains headers.
* The first column contains student names. Student names contain only
 lowercase letters and are no longer than 6 letters.
* The remaining columns contain grades (as integers) for various
 assignments.
* A grade of `'exc'` means excused.
* Assignment names are always a category name (hw, quiz,
 exam) followed by an integer, and they are always numbered in order
 starting from 1\.
* Assignments are grouped by category, so for example all quizzes will be
 together.



For some problems, you will also need a dictionary of category weights like so:

```

categoryWeights = { 'hw':50, 'quiz':10, 'exam':40 }

```

You can assume that any category in the gradebook also appears in
categoryWeights. When calculating the average for a category, excused grades do
not count. For example, to calculate betty's quiz average for the above example,
we ignore the `'exc'` for quiz 1 and take `round((98 + 92) / 2) = 95`




When calculating the average for the semester, each category average
should be multipled by its category weight. For example, if a student's averages
were as follows:

```

categoryAverages = { 'hw': 91, 'quiz': 88, 'exam': 94 }

```

We can express the category weights as percentages by dividing by the sum of all
the weights (`50 + 10 + 40 = 100`). Then the semester average would be `round(91 * (50/100) + 88 * (10/100) + 94 *
(40/100)) = 92`




 With this in mind, write the following functions:

 1. `gradebookAsTable(gradebookText)` which takes a string of
 gradebook text and returns the information as a 2d list of data
2. `studentNames(gradebookText)` which takes a string of
 gradebook text and returns a sorted tuple of student names
3. `categories(gradebookText)` which takes a string of
 gradebook text and returns a 1d list of categories in the same order as
 they appear in the gradebook
4. `studentScores(gradebookText, categoryWeights, student)`
 which takes a string of gradebook text, a dictionary of category weights,
 and the name of a student (who you can assume is in the gradebook) and
 returns a dictionary of categories mapped to the average for that student
 in that category as well as the semester grade calculated according to the
 category weights. Round all averages to the nearest integer.
5. `semesterGrades(gradebookText, categoryWeights)` which
 returns a multiline string of student, category grades, numeric grade, and
 letter grades,
 sorted by student name






 Hints:
 * Study the test cases carefully to make sure you're returning the
 correct thing for each function.
* Write the functions in order. You may find that previous functions are
 useful to write functions further on.
* For `semesterGrades`, each line should be left justified, but
 the grades within each column should be right justified. You may find
 the functions `s.ljust(length)` and
 `s.rjust(length)` useful. `ljust` and
 `rjust` add spaces to the left and right of a string
 respectively until they have that length. You can run this code as an
 example:

```

print('----')
print('ab'.ljust(4))
print('ab'.rjust(4))
print('----')

```

which produces this output:

```

----
ab  
  ab
----

```
"""

def gradebookAsTable(gradebookText):
    return 42

def studentNames(gradebookText):
    return 42

def categories(gradebookText):
    return 42

def studentScores(gradebookText, categoryWeights, student):
    return 42

def semesterGrades(gradebookText, categoryWeights):
    return 42

def getSimpleGradebook():
    return '''\
student  quiz1
wilma       90'''

def getMediumGradebook1():
    return '''\
student  hw1  quiz1  exam1
wilma     90     89     75'''

def getMediumGradebook2():
    return '''\
student  quiz1
wilma       80
barney      90'''

def testGradebookAsTable():
    print('Testing gradebookAsTable()...', end='')
    gradebook1 = getSimpleGradebook()
    assert(gradebookAsTable(gradebook1) ==
    [ ['student', 'quiz1'],
      ['wilma', 90] ])

    gradebook2 = getMediumGradebook1()
    assert(gradebookAsTable(gradebook2) ==
    [ ['student', 'hw1', 'quiz1', 'exam1'],
      ['wilma', 90, 89, 75] ])

def testStudentNames():
    print('Testing studentNames()...', end='')
    gradebook1 = getSimpleGradebook()
    assert(studentNames(gradebook1) == ('wilma',))

    gradebook2 = getMediumGradebook2()
    assert(studentNames(gradebook2) == ('barney', 'wilma'))

def testCategories():
    print('Testing categories()...', end='')
    gradebook1 = getSimpleGradebook()
    assert(categories(gradebook1) == ['quiz'])

    gradebook2 = getMediumGradebook1()
    assert(categories(gradebook2) == ['hw', 'quiz', 'exam'])

def testStudentScores():
    print('Testing studentScores()...', end='')
    gradebook1 = getSimpleGradebook()
    categoryWeights = {'quiz': 100}
    assert(studentScores(gradebook1, categoryWeights, 'wilma') ==
            {'quiz': 90, 'semester': 90})

    gradebook2 = getMediumGradebook1()
    categoryWeights = {'quiz': 30, 'hw': 30, 'exam': 40}
    assert(studentScores(gradebook2, categoryWeights, 'wilma') ==
            {'hw': 90, 'quiz': 89, 'exam': 75, 'semester': 84})

def testSemesterGrades():
    print('Testing semesterGrades()...', end='')
    gradebook1 = getSimpleGradebook()
    categoryWeights = {'quiz': 100}
    print('Passed!')
    assert(semesterGrades(gradebook1, categoryWeights) == '''\
student  quizAvg  semesterAvg  semesterGrade
wilma         90           90              A''')

    gradebook2 = getMediumGradebook1()
    categoryWeights = {'quiz': 30, 'hw': 30, 'exam': 40}
    assert(semesterGrades(gradebook2, categoryWeights) == '''\
student  hwAvg  quizAvg  examAvg  semesterAvg  semesterGrade
wilma       90       89       75           84              B''')

    gradebook3 = getMediumGradebook2()
    categoryWeights = {'quiz': 100}
    assert(semesterGrades(gradebook3, categoryWeights) == '''\
student  quizAvg  semesterAvg  semesterGrade
barney        90           90              A
wilma         80           80              B''')

def testAll():
    print('Testing all()...', end='')
    print('Passed!')
    gradebookText = '''\
student  hw1   hw2   hw3   hw4  quiz1   quiz2   quiz3  exam1  exam2
wilma     94    97    91    83     81      95      87    exc     94
fred      90    88    92    85     77      81      90     88     82
barney    75    83    71   exc     68      71      73     72     76
betty    100   100    99   100    exc      98      92     88    100'''
    categoryWeights = { 'hw':50, 'quiz':10, 'exam':40 }

    gradebookTable = [
        ['student','hw1','hw2','hw3','hw4',
        'quiz1','quiz2','quiz3','exam1','exam2'],
        ['wilma',94,97,91,83,81,95,87,'exc',94],
        ['fred',90,88,92,85,77,81,90,88,82],
        ['barney',75,83,71,'exc',68,71,73,72,76],
        ['betty',100,100,99,100,'exc',98,92,88,100],
    ]
    assert(gradebookAsTable(gradebookText) == gradebookTable)
    assert(studentNames(gradebookText) == ('barney', 'betty', 'fred', 'wilma'))
    assert(categories(gradebookText) == [ 'hw', 'quiz', 'exam' ])
    assert(studentScores(gradebookText, categoryWeights, 'wilma') ==
            {'hw':91, 'quiz':88, 'exam':94, 'semester':92})
    assert(studentScores(gradebookText, categoryWeights, 'fred') ==
            {'hw':89, 'quiz':83, 'exam':85, 'semester':87})
    assert(studentScores(gradebookText, categoryWeights, 'barney') ==
            {'hw':76, 'quiz':71, 'exam':74, 'semester':75})
    assert(studentScores(gradebookText, categoryWeights, 'betty') ==
            {'hw':100, 'quiz':95, 'exam':94, 'semester':97})
    assert(semesterGrades(gradebookText, categoryWeights) == '''\
student  hwAvg  quizAvg  examAvg  semesterAvg  semesterGrade
barney      76       71       74           75              C
betty      100       95       94           97              A
fred        89       83       85           87              B
wilma       91       88       94           92              A''')

def main():
    testGradebookAsTable()
    testStudentNames()
    testCategories()
    testStudentScores()
    testSemesterGrades()
    testAll()

main()