# -*- coding: utf-8 -*-
"""Level 1 maxDigit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/108BhHZV_T3qrCGssq5Asz6adlB6goinl

Note: you may not use `for` or `while` loops here.
Instead, use recursion.
  
  

With that in mind, write the recursive function `maxDigit(n)`
that takes a possibly\-negative int n, and returns the largest digit in n.
  
  

For example, `maxDigit(-583)` returns 8\.
"""

def maxDigit(n):
    max_digit = 0
    absolute_n = abs(n)
    if absolute_n < 10:
        max_digit = absolute_n
        return max_digit
    else:
        next_digit = maxDigit(absolute_n // 10)
        last_digit = absolute_n % 10
        absolute_n = absolute_n // 10
        if next_digit > max_digit:
            max_digit = next_digit
        if last_digit > max_digit:
            max_digit = last_digit
        return max_digit
    


def testMaxDigit():
    print('Testing maxDigit()...', end='')
    assert(maxDigit(0) == 0)
    assert(maxDigit(1) == 1)
    assert(maxDigit(-1) == 1)
    assert(maxDigit(12321) == 3)
    assert(maxDigit(-12321) == 3)
    assert(maxDigit(102030405060708090) == 9)
    assert(maxDigit(22222222222) == 2)
    assert(maxDigit(22222322222) == 3)
    print('Passed!')

def main():
    testMaxDigit()

main()