# -*- coding: utf-8 -*-
"""Level 3 flatten.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kMKUeW9z01H7srmxEBSL-VkUDjj1685l

Note: you may not use `for` or `while` loops here.
Instead, use recursion.
  
  

With that in mind, write the recursive function `flatten(L)`
that takes a list L that may contain sublists (which themselves may
further contain sublists), and returns a new list M where M contains
all the non\-list values in L at the top level (with no sublists).
  
  

For example, `flatten([1,[2]])` returns \[1,2]. See how
the result includes the value 2 but it is now at the top level,
and not in a sublist.
  
  

Here are more test cases:

```
assert(flatten([1,[2]]) == [1,2])
assert(flatten([1,2,[3,[4,5],6],7]) == [1,2,3,4,5,6,7])
assert(flatten(['wow', [2,[[]]], [True]]) == ['wow', 2, True])
assert(flatten([]) == [])
assert(flatten([[]]) == [])
assert(flatten([3]) == [3])
assert(flatten([[[3]]]) == [3])
```

Hints:
1. You may want to use `isinstance(value, list)` to
 test if the value is a list.
2. Be sure to watch the helpful guided video first!


#### Guided Solution
"""

def flatten(L):
    return 42

def testFlatten():
    print('Testing flatten()...', end='')
    assert(flatten([1,[2]]) == [1,2])
    assert(flatten([1,2,[3,[4,5],6],7]) == [1,2,3,4,5,6,7])
    assert(flatten(['wow', [2,[[]]], [True]]) == ['wow', 2, True])
    assert(flatten([]) == [])
    assert(flatten([[]]) == [])
    assert(flatten([3]) == [3])
    assert(flatten([[[3]]]) == [3])
    print('Passed!')

def main():
    testFlatten()

main()