# -*- coding: utf-8 -*-
"""Level 3 powerSet.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gT5kCasbyACy8v4Yi72ufdoWXZXWEGdg

Note: while you must use recursion in this exercise, you may also use use
`for` or `while` loops if you wish.
  
  

Background: A **powerset** consists of all the possible subsets of a given
 collection of elements. In this exercise, subsets will be represented as lists.
 For example, the subsets of `[1, 2, 3]` are:

```
[]
[1], [2], [3]
[1, 2], [2, 3], [1, 3]
[1, 2, 3]
```

 Thus, the powerset of `[1, 2, 3]` would be
 `[[], [1], [2], [3], [1, 2], [2, 3], [1, 3], [1, 2, 3]]`.
 Observe that for every list, the empty list and the list itself are
 valid subsets.




With this in mind, write the function `powerSet(L)` that takes a
list of integers `L` and returns a **sorted** list
representing the powerset of `L`. For example,
`powerSet([1,2])` would return `[[], [1], [1, 2], [2]]`.
Note: It is guaranteed that there are no duplicates in the list.




Hint: Each element in the list can either be included or excluded
in a subset. So, consider recursively generating the subsets of a sublist
of `L` and then implementing the two cases mentioned
above.




\*If the autograder is failing, double\-check that your function outputs a
sorted list.\*



#### Guided Solution
"""

def powerset(L):
    return 42

def testIsPowerSet():
    print('Testing isPowerSet()...', end='')
    # Make sure that your output list is sorted.
    L = [1, 2, 3]
    output = [[], [1], [2], [3], [1, 2], [1, 3], [2, 3], [1, 2, 3]]
    assert(powerset(L) == sorted(output))

    L = [5, 8]
    output = [[], [5], [8], [5, 8]]
    assert(powerset(L) == sorted(output))

    L = [-1]
    output = [[], [-1]]
    assert(powerset(L) == sorted(output))

    L = []
    assert(powerset(L) == [[]])
    print('Passed!')

def main():
    testIsPowerSet()

main()