# -*- coding: utf-8 -*-
"""Level 3 hasSublistSum.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hUF87JY6IgUUpYWRfnosJLxYd5Et2wjD

Note: you may not use `for` or `while` loops in
this exercise. Instead, use recursion.
  
  

Write the function `hasSublistSum(L, s)` that takes a list of
 integers `L` and an integer `s`, and returns
 `True` if there exist elements in `L` that sum
 to `s`. Otherwise, the function returns `False`.



For example, `hasSublistSum([1, 6, 2, 8], 3)` returns
 `True` because 1 and 2 sum to 3\. Similarly,
 `hasSublistSum([1, 6, 2, 8], 11)` returns
 `True` because 1, 2, and 8 sum to 11\. On the other hand,
 `hasSublistSum([7, -1, 4], -5)` returns `False`
 because no combination of elements sums to \-5\. In addition, the function
 should always return true when `s = 0` since the empty list
 is a sublist of any list, and its sum is 0\.
"""

def hasSublistSum(L, s):
    return 42

def testHasSublistSum():
    print('Testing hasSublistSum()...', end='')
    L = [1, 6, 2, 8]
    assert(hasSublistSum(L, 3) == True)

    L = [1, 6, 2, 8]
    assert(hasSublistSum(L, 11) == True)

    L = [3, -1, 7]
    assert(hasSublistSum(L, -1) == True)

    L = [8, 1, 1]
    assert(hasSublistSum(L, 2) == True)

    L = [7, -1, 4]
    assert(hasSublistSum(L, -5) == False)

    L = []
    assert(hasSublistSum(L, 0) == True)

    print('Passed!')

def main():
    testHasSublistSum()

main()