# -*- coding: utf-8 -*-
"""Level 3 friendsOfFriends.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n9dur6Mz8aP08d7MwZHM9ZfY5KA_mYGB

Background: We can create a dictionary mapping people to sets of their
 friends. For example:

```

{
  'Fred'   : {'Wilma', 'Betty', 'Robert'},
  'Betty'  : {'Alice', 'Wilma'},
  'Wilma'  : {'Fred'},
  'Alice'  : {'Betty'},
  'Robert' : set()
}
```





 A friend\-of\-friend of a person is a friend of one of that person's
 friends. For example, Alice is a friend\-of\-friend of Fred, since Alice
 is one of Betty's friends, and Betty is a friend of Fred.




 We don't consider direct friends as friends\-of\-friends, so Wilma would
 not be a friend\-of\-friend of Fred, even though she's one of Betty's
 friends. Similarly, a person can't be one of their own
 friends\-of\-friends. So Fred would not be a friend\-of\-friend of himself,
 even though he is one of Wilma's friends.




 With this in mind, write the function
 `friendsOfFriends(friends)`, which takes a dictionary mapping
 people to sets of their friends, and returns a dictionary mapping
 people to sets of their friends\-of\-friends. For example, calling
 `friendsOfFriends` on the dictionary of friends above would
 return:

```

{
  'Fred'   : {'Alice'},
  'Betty'  : {'Fred'},
  'Wilma'  : {'Betty', 'Robert'},
  'Alice'  : {'Wilma'},
  'Robert' : set()
}
```





 Notes:
 1. You may assume that everyone listed in any of the friend sets
 is also included as a key in the dictionary.
2. You may not assume that if Person1 lists Person2 as a
 friend, Person2 will also list Person1 as a friend. Sometimes
 friendships are only one\-way.
"""

import copy

def friendsOfFriends(friends):
    return 42

def testFriendsOfFriends():
    print('Testing friendsOfFriends()...', end='')
    friends = {
                'Fred'   : {'Wilma', 'Betty', 'Robert'},
                'Betty'  : {'Alice', 'Wilma'},
                'Wilma'  : {'Fred'},
                'Alice'  : {'Betty'},
                'Robert' : set()
              }

    fof = {
            'Fred'  : {'Alice'},
            'Betty' : {'Fred'},
            'Wilma' : {'Betty', 'Robert'},
            'Alice' : {'Wilma'},
            'Robert': set()
          }
    friends2 = copy.deepcopy(friends) # Used to verify function is nonmutating
    assert(friendsOfFriends(friends) == fof)
    # Verify that the function is nonmutating:
    assert(friends == friends2)

    friends = {
                'A' : {'B'},
                'B' : {'C'},
                'C' : {'A'}
              }

    fof = {
            'A' : {'C'},
            'B' : {'A'},
            'C' : {'B'}
          }
    assert(friendsOfFriends(friends) == fof)

    friends = {
                'Melissa' : {'Joshua', 'Anna'},
                'Joshua' : {'Orelia'},
                'Anna' : {'Cynthia'},
                'Orelia' : set(),
                'Cynthia' : set()
              }

    fof = {
            'Melissa': {'Orelia', 'Cynthia'},
            'Joshua': set(),
            'Anna': set(),
            'Orelia': set(),
            'Cynthia': set()
          }
    assert(friendsOfFriends(friends) == fof)

    assert(friendsOfFriends(dict()) == dict())

    print('Passed!')

def main():
    testFriendsOfFriends()

main()