# -*- coding: utf-8 -*-
"""Level 3 countMap.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-_4qvqmSPgtCmiYn0EavDexGuT1eFu7x

Write the function `countMap(L)` that takes a list
 `L` of sets containing immutable values (such as strings,
 integers, and floats) and returns a dictionary mapping integer counts
 to a set of values occuring that many times within `L`.




 For example, say that `L = [ {'a', 'b'}, {'a', 'c'}, {'a', 'b', 'd'}].`
 We see that `'a'` occurs 3 times, `'b'` occurs 2
 times, and `'c'` and `'d'` each occur 1 time.
 So, the resulting dictionary should be
 `{ 1: {'c', 'd'}, 2: {'b'}, 3: {'a'} }).`




 Hint: It may be helpful to first create a dictionary that maps
 each present immutable value to the overall number of times it occurs
 in the sets in `L`. In the example above,
 this would be: `{'a': 3, 'b': 2, 'c': 1, 'd': 1}.`
"""

def countMap(L):
    return 42

def testCountMap():
    print('Testing countMap()...', end='')
    L = [ {'a', 'b'}, {'a', 'c'}, {'a', 'b', 'd'} ]
    d = { 1: {'c', 'd'},
          2: {'b'},
          3: {'a'} }
    assert(countMap(L) == d)

    L = [ {'d'}, {'x', 'y'} ]
    d = { 1: {'d', 'x', 'y'} }
    assert(countMap(L) == d)

    L = [ {1, 'a'}, {2, 'a'} ]
    d = { 1: {1, 2},
          2: {'a'} }
    assert(countMap(L) == d)

    L = [ {5, 4.4, 'a'}, {4.4, 'b', ('a', 'b')} ]
    d = { 1: {5, 'a', 'b', ('a', 'b')},
          2: {4.4} }
    assert(countMap(L) == d)

    assert(countMap([]) == dict())

    print('Passed!')

def main():
    testCountMap()

main()