# -*- coding: utf-8 -*-
"""Level 2 recursiveInterleave.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J2qbIFnrZWv7di6C33C1ybV3Uh-1I_ov

Note: you may not use `for` or `while` loops here.
Instead, use recursion.
  
  

With that in mind, write the recursive function
`recursiveInterleave(L, M)`
that takes two lists, L and M, and returns a list formed by interleaving
the values in L and M. Thus, the result should include alternating
values from L and M. For example:  

`recursiveInterleave([1,2],[3,4])` returns \[1,3,2,4].
  
  

If the lists are of different lengths, interleave the values until you
run out of values in one list, and then just use the remaining
non\-interleaved values from the other list. Thus:  

`recursiveInterleave([1,2],[3,4,5,6])` returns \[1,3,2,4,5,6].  

`recursiveInterleave([1,2,5,6],[3,4])` also returns \[1,3,2,4,5,6].
"""

def recursiveInterleave(L, M):
    if L == []:
        return M
    elif M == []:
        return L
    else:
        return [L[0], M[0]] + recursiveInterleave(L[1:], M[1:])

def testRecursiveInterleave():
    print('Testing recursiveInterleave()...', end='')
    assert(recursiveInterleave([1,2], [3,4,5,6]) == [1,3,2,4,5,6])
    assert(recursiveInterleave([1,2,5,6], [3,4]) == [1,3,2,4,5,6])
    assert(recursiveInterleave([],[3,4]) == [3,4])
    assert(recursiveInterleave([1,2],[]) == [1,2])
    assert(recursiveInterleave([1,2,3,4],[5,6,7]) == [1,5,2,6,3,7,4])
    print('Passed!')

def main():
    testRecursiveInterleave()

main()