# -*- coding: utf-8 -*-
"""1 - For Loops.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UsSp6kHz_QAzPJ5Pv8eS7fcwfCer31jo

<font size="1" color="#AAA">Python Fundamentals &copy; David Kosbie</font>  

# For Loops

## range
Before we cover `for` loops, we first need to learn about the `range` function.

### range(n)
`range(n)` returns a so-called *range* of n integers from 0 to n-1.
"""

print(range(5))

"""The result of a call to `range(n)` is a *range object* (which is a
special kind of *sequence*).  We can use this object
in a loop, but for now we want to better understand the values in the range.
For that, we need to turn the object into a list by calling `list(range(n))`.

Note: we have not yet covered lists, and you should not use lists in any
of your solutions to the exercises in this section.  We are only using
lists here so we can see the values in a range.
"""

print(list(range(5)))

"""### range(start, stop)
This form of `range` returns the integers from start to stop-1.
"""

print(list(range(5, 10)))

"""### range(start, stop, step)
This last form of `range` returns the integers from start to stop-1
stepping with the given step.
"""

print(list(range(5, 10, 2)))

"""The stop value is always omitted."""

print(list(range(5, 11, 2))) # surprised?

"""We can use a negative step to reverse the order of a range.
In this case, the range includes the values from start
*down* to stop+1 stepping with the given step.
"""

print(list(range(8, 3, -1)))

"""## for loops
We use a *for loop* to loop over the values in a sequence.  Here is the general form:

<pre>
for VARIABLE in SEQUENCE:
    BODY
</pre>

This code sets the so-called *loop variable* to each value in the sequence and then runs the body.

Each time the body runs is called a *pass* or an *iteration*.

Since a range is a sequence, we can loop over a range:
"""

for x in range(5):
    # x is the loop variable
    # The body wil run 5 times, with x=0, x=1, x=2, x=3, and x=4
    print(x)

"""Here are some example functions that use range:

### sumToN
Write the function sumToN(n) that takes a non-negative int n and
returns the sum of the ints from 0 to n (inclusive),
so sumToN(5) should return 15 (1+2+3+4+5).
"""

# First attempt: this version has a bug!
def sumToN(n):
    total = 0
    for x in range(n):
        total += x
    return total

print(sumToN(5)) # surprised?

"""Remember that range(n) always excludes n itself."""

# Working version:
def sumToN(n):
    total = 0
    for x in range(n+1): # <-- we use (n+1) so n is in the range!
        total += x
    return total

print(sumToN(5)) # better!

"""Aside: the `sum` function works on ranges, so we did not actually
need to use a loop here:
"""

# Alternate version without loops:
def sumToN(n):
    return sum(range(n+1))

print(sumToN(5))

"""Actually, we could also use the well-known formula for the sum of the integers up to n
(Gauss's Formula).
"""

# Another alternate version using Gauss's Formula
def sumToN(n):
    return n * (n+1) // 2  # use // to get an integer result

print(sumToN(5))

"""### factorial
Write the function factorial(n) that takes a non-negative int n and
returns the product of the ints from 1 to n (inclusive), that is,
n factorial (written n!).
So factorial(5) should return 120 (1\*2\*3\*4\*5).
"""

# First attempt: this version has a bug!
def factorial(n):
    result = 1  # start at 1 since we are multiplying
    for x in range(n+1):
        result *= x
    return result

print(factorial(5)) # surprised?

"""Remember that range(n) always starts at 0."""

# Working version:
def factorial(n):
    result = 1
    for x in range(1, n+1): # <-- we start at 1 instead of 0
        result *= x
    return result

print(factorial(5))

"""Aside: Python has a built-in factorial function (math.factorial), so we still did not need
to use loops here.  In fact, we did not have to write a function at all in this case!
"""

# Alternate version:
import math
print(math.factorial(5))

"""### sumFromMtoN
Write the function sumFromMToN(m, n) that takes two possibly-negative
ints, m and n, and
returns the sum of the ints from m to n (inclusive),
so sumToN(3, 5) should return 12 (3+4+5), and
sumToN(-3, -1) should return -6 (-3 + -2 + -1).
"""

def sumFromMtoN(m, n):
    total = 0
    for x in range(m, n+1):
        total += x
    return total

print(sumFromMtoN(3, 5))
print(sumFromMtoN(-3, -1))

"""Aside: we still could have done this without loops:"""

def sumFromMtoN(m, n):
    return sum(range(m, n+1))

print(sumFromMtoN(3, 5))
print(sumFromMtoN(-3, -1))

"""### sumOfSquaresFromMtoN
Write the function sumOfSquaresFromMToN(m, n) that takes two possibly-negative
ints, m and n, and
returns the sum of the *squares* of the ints from m to n (inclusive),
so sumOfSquaresFromMtoN(3, 5) should return 50 (3<sup>2</sup> + 4<sup>2</sup> + 5<sup>2</sup>), and
sumOfSquaresFromMtoN(-3, -1) should return 14 ((-3)<sup>2</sup> + (-2)<sup>2</sup> + (-1)<sup>2</sup>).
"""

def sumOfSquaresFromMtoN(m, n):
    total = 0
    for x in range(m, n+1):
        total += x ** 2
    return total

print(sumOfSquaresFromMtoN(3, 5))
print(sumOfSquaresFromMtoN(-3, -1))

"""This time we cannot just sum the range!  Note that there is a way to compute this
directly with a math formula, but if you do not know how to do that (as many people do not!),
you can simply loop to sum the squares of the values in the range, like we just did.

## Nested for loops
We can include a for loop inside another for loop.  These are called
*nested* loops, with an *outer* loop and an *inner* loop.
"""

for x in range(4):
    print(f'outer loop, x = {x}')
    for y in range(4):
        print(f'   inner loop, y = {y}')

"""The inner loop range can depend on the outer loop variable.
In this way, for example, we can loop over every unique pair of
values in a range.
"""

for x in range(4):
    print(f'outer loop, x = {x}')
    for y in range(x+1, 4): # <-- this depends on x (the outer loop variable)
        print(f'   inner loop, y = {y}')

"""Let's make that more explicit:"""

# Print all the unique pairs of values in the range:
for x in range(4):
    for y in range(x+1, 4):
        print(x, y)

"""We can use this approach to solve some interesting problems!

### printTenSumProducts
We will say that two positive integers x and y are "ten-sum products" (a coined term) if
their product is ten times their sum.  That is, if x\*y equals 10\*(x+y).

For example, 15 and 30 are ten-sum products because:

  * 15 * 30 == 450

  and

  * 10 * (15 + 30) == 450

With that in mind, write the function printTenSumProduct(maxValue) that takes
an int, maxValue, and for each unique pair of ints x, y that are ten-sum products,
where both x and y are no larger than maxValue, the function prints
a descriptive message.

Notes:
  
  * The problem does not specify what your function should return.  In such
    cases, you should return None implicitly (without an explicit return statement).

  * There are 4 unique ten-sum product pairs where both x and y are no larger than 100.
"""

# First attempt, has a bug:
def printTenSumProducts(maxValue):
    for x in range(1, maxValue + 1):
        for y in range(1, maxValue + 1):
            if x * y == 10 * (x + y):
                print(f'{x} and {y}, because ', end='')
                print(f'{x} * {y} == {x*y}, and 10 * ({x} + {y}) == {x*y}')

printTenSumProducts(100)

"""Run the code and look carefully at the output.  It correctly identifies 15 and 30 as a ten-sum product.  Great!  But it also identifies 30 and 15 as a different ten-sum product.  For this problem, we only want each pair to occur once, so we adjust our inner loop so it starts at the value of the outer loop variable, like so:"""

# Better (now each unique pair occurs only once):
def printTenSumProducts(maxValue):
    for x in range(1, maxValue + 1):
        for y in range(x, maxValue + 1):
            if x * y == 10 * (x + y):
                print(f'{x} and {y}, because ', end='')
                print(f'{x} * {y} == {x*y}, and 10 * ({x} + {y}) == {x*y}')

printTenSumProducts(100)

"""Let's change the problem slightly, requiring that we label each line of output
as "Pair #k" where k is a counter starting at 1.
"""

# This time with numbered lines:
def printTenSumProducts(maxValue):
    lineNumber = 1
    for x in range(1, maxValue + 1):
        for y in range(x, maxValue + 1):
            if x * y == 10 * (x + y):
                print(f'Pair #{lineNumber}: ', end='')
                print(f'{x} and {y}, because ', end='')
                print(f'{x} * {y} == {x*y}, and 10 * ({x} + {y}) == {x*y}')
                lineNumber += 1

printTenSumProducts(100)