# -*- coding: utf-8 -*-
"""3 - Break and Continue.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UHx-P_8aiZ9KdDkCp1xO-W_RlM1QKGnz

<font size="1" color="#AAA">Python Fundamentals &copy; David Kosbie</font>  

# Break and Continue
We now explore *break* statements and *continue* statements.

## Break
A break statement inside a loop simply exits the loop immediately. You often do not need to use this, but sometimes it can be very helpful.

Here is a previous example, now with a break statement added:
"""

x = 5
print(f'At first, x = {x}')
while x < 10:
    if x == 7:
        break
    x += 1
    print(f'now x = {x}')
print(f'afterwards, x = {x}')

"""## Infinite Loops and Break
A while loop where the condition is simply `True` is called an *infinite loop*.
It will keep looping forever.  Well, not really.  It will stop looping if:

  * the code crashes (say by dividing by zero), or
  
  * the computer crashes (say it runs out of battery), or
  
  * the code is inside a function and reaches a return statement, or
  
  * the code reaches a break statement.

Here is a common example using an infinite loop with a break statement:
"""

print('Keep entering integers to get their sum.  Enter 0 to stop.')
total = 0

while True:
    print(f'The total so far is {total}')
    n = int(input('Next integer (or 0 to stop) --> '))
    if n == 0:
        break
    total += n

print(f'We have exited the loop.  The final total is {total}')

"""## Continue
A continue statement is similar to a break statement. It is not used very often in practice, but even so, you should at least understand what it does.

A continue statement inside a loop only exits the current pass, but not the entire loop. After a continue statement, Python returns to the top of the loop and continues running from there.
"""

# Similar example with continue:
x = 5
print(f'At first, x = {x}')
while x < 10:
    x += 1
    if x == 7:
        continue
    print(f'now x = {x}')
print(f'afterwards, x = {x}')

"""It is often easy (and preferable) to rewrite code to not use a continue statement:"""

# Same example but without using continue:
x = 5
print(f'At first, x = {x}')
while x < 10:
    x += 1
    if x != 7:
        print(f'now x = {x}')
print(f'afterwards, x = {x}')

"""## Break and Continue in Nested Loops
Break and continue only affect the *innermost* loop they occur in.
"""

x = 5
for x in range(4):
    if x == 2:
        continue
    print(f'outer loop, x = {x}')
    for y in range(4):
        if y == 2:
            break
        print(f'   inner loop, y = {y}')