# -*- coding: utf-8 -*-
"""4 - Top-Down Design.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Kzt7XLYrHKmIpQNhlZQGbjFakz2B8_Ae

<font size="1" color="#AAA">Python Fundamentals &copy; David Kosbie</font>  

# Top-Down Design
We now cover *top-down design*, an effective process we use
to methodically solve complex problems.
"""

s = "string"
for c in s.split():
    print(c)

"""## Top-Down Design

*Top-Down Design* is an approach to softare development where:

  1. We break down a large, complex problem into smaller tasks.
  
  2. We then break down those tasks into even smaller tasks.
  
  3. We continue this process until we have small, manageable tasks.
  
  4. We then write a Python function for each small task.
  
  5. We use those Python functions as helper functions for the
    larger tasks.
    
  6. We design our code top-down, then we test our code bottom-up.<br>
     This way, each helper function is tested before we use it.

Top-Down Design is also known as:

  * Decomposition
  
  * Divide and Conquer
  
  * Stepwise Refinement


Advantages of Top-Down Design include:

  * Scalability <br>
    We can solve increasingly large problems without becoming
    overwhelmed by their scale.
  
  * Clarity <br>
    Each function we write is small, solving a clear task,
    and calling well-chosen and well-named helper functions.
    This leads to much clearer code.
  
  * Reliability <br>
    We test each smaller function before we use them, thus isolating
    bugs to those functions. This leads to much more reliable code.
    Because of this, top-down design reduces bugs, and makes the bugs
    you do create much easier to find and fix.
  
  * Reusability <br>
    Often, the helper fuctions we write to solve one problem
    can be reused to help solve other problems in the future.
  
  * Efficiency <br>
    Because top-down design leads to more reliable and reusable code,
    it ultimately lets us code much faster.

The bottom line: Top-down design lowers stress, reduces bugs,
increases productivity, and saves time and money.

## Case Study: nthHappyPrime
We will now solve the nthHappyPrime problem to demonstrate the top-down design process.

### Problem Statement

#### Background

A *prime number* (or just a *prime*) is an integer
greater than 1 that is only divisible by 1 and itself.

Restated: an integer n is prime if

  * n is greater than 1, and
  
  * no integer between 2 and n-1 evenly divides n.

The first 10 primes are: 2, 3, 5, 7, 11, 13, 17, 19, 23, 29.

<hr>

A *happy number* is a positive integer n which eventually reaches 1 when
replaced by the sum of the square of each digit in n.

An *unhappy number* is an integer that eventually reaches 4
(and so it never reaches 1).

Every positive integer is either happy or unhappy.

For example, 13 is a happy number because:

  * We replace 13 with 1<sup>2</sup> + 3<sup>2</sup> = 1 + 9 = 10.
  
  * We replace 10 with 1<sup>2</sup> + 0<sup>2</sup> = 1 + 0 = 1.
  
  * We reached 1, so 13 is happy.

As another example, 145 is an unhappy number because:

  * We replace 145 with 1<sup>2</sup> + 4<sup>2</sup> + 5<sup>2</sup> = 1 + 16 + 25 = 42.

  * We replace 42 with 4<sup>2</sup> + 2<sup>2</sup> = 16 + 4 = 20.
  
  * We replace 20 with 2<sup>2</sup> + 0<sup>2</sup> = 4 + 0 = 4.
  
  * We reached 4, so 145 is unhappy.
  
The first 10 happy numbers are: 1, 7, 10, 13, 19, 23, 28, 31, 32, 44.

<hr>

A *happy prime* is a number that is both happy and prime.

The first 10 happy primes are: 7, 13, 19, 23, 31, 79, 97, 103, 109, 139.

#### nthHappyPrime
With that, write the function nthHappyPrime(n) that takes a non-negative int n,
and returns the nth happy prime, starting counting at 0,
so nthHappyPrime(0) returns 7, nthHappyPrime(1) returns 13, and so on.

### Step 1: nthHappyPrime

#### Design nthHappyPrime
To find the nth happy prime:

  * Start guessing int values in order: 1, 2, 3, 4,...
  
  * For each guess, check if it is a happy prime.
  
  * If it is a happy prime, add one to the number of happy primes we have found.
  
  * Keep doing this until we have found the right numer of happy primes.
  
  * Then return the last happy prime we found.

For example, to solve nthHappyPrime(1):

  * is 1 a happy prime? no.
  * is 2 a happy prime? no.
  * ...
  * is 7 a happy prime? yes!
    * We just found nthHappyPrime(0). So keep going.
  * is 8 a happy prime? no.
  * is 9 a happy prime? no.
  * ...
  * is 13 a happy prime? yes!
    * We just found nthHappyPrime(1). So we are done. Return 13.

#### Code nthHappyPrime

We now translate our algorithm into code.

Importantly, we assume we have the right helper functions already written.
That is top-down design!
"""

def nthHappyPrime(n):
    seen = 0
    guess = 0
    # note: continue looping even when seen == n since we start
    # counting at 0 (so when n == 0, we stop when seen == 1).
    while seen < n + 1:
        guess += 1
        if isHappyPrime(guess):
            seen += 1
    return guess

"""We now have to write the helper function(s) we just used:

  * isHappyPrime(guess)

### Step 2: isHappyPrime

#### Design isHappyPrime

To check if a int n is a happy prime, we just test that is happy
and that it is prime.

#### Code isHappyPrime

The code for isHappyPrime is easy to write,
again using top-down design:
"""

def isHappyPrime(n):
    return isHappy(n) and isPrime(n)

"""We now have to write the helper function(s) we just used:

  * isHappy(n)
  
  * isPrime(n)

### Step3: isHappy

#### Design isHappy

To test if a number n is happy, we closely follow the definition
of a happy number.

That is, we first verify that n is positive.  If so,
we keep replacing n by the sum of the square of its digits,
stopping when we reach 1 (so n is happy) or 4 (so n is unhappy).

#### Code isHappy

Here is the resulting code:
"""

def isHappy(n):
    if n < 1:
        return False
    while (n != 1) and (n != 4):
        n = sumOfSquaresOfDigits(n)
    return n == 1

"""We now have to write the helper function(s) we just used:

  * sumOfSquaresOfDigits(n)

### Step 4: sumOfSquaresOfDigits

#### Design sumOfSquaresOfDigits

To find the sum of the square of the digits of an int n,
we loop over each digit of n, square that digit, and add it
to a running total.  We then return that total.

It is a good idea to make your helper functions as general as
possible.  This has multiple advantages:

  * It reduces the chance of a bug in your code, if you
    actually do rely on a case that you did not realize you needed, and
    
  * It makes your helper function more likely to be used,
    and used correctly, in later problems you may solve.

In this case, we will make this function work for negative
values, even though the problem statement does not require that.
To do so, we will just take the absolute value of the number
at the start.

#### Code sumOfSquaresOfDigits

Here is the code:
"""

def sumOfSquaresOfDigits(n):
    n = abs(n)
    total = 0
    while n > 0:
        nextDigit = n % 10
        total += nextDigit ** 2
        n //= 10
    return total

"""This code does not use any helper functions.

### Step 5: isPrime

#### Design isPrime

To test if an int n is prime, we will closely follow the definition
of a prime number.

That is, we will first verify that n is greater than 1. If so, we will
check every value between 2 and n-1, and if any of them evenly divide n
(that is, if they are a *factor* of n), then n is not prime.  If none
of them are factors, then n is prime.

#### Code isPrime

Here is the code:
"""

def isPrime(n):
    # Note: there are faster ways to do this!
    if n < 2:
        return False
    for factor in range(2, n):
        if n % factor == 0:
            return False
    return True

"""This code does not use any helper functions.

### Step 6: Test Bottom-Up

We are done with our top-down design!

We now test our code bottom-up.

#### Step 6.1: Test sumOfSquaresOfDigits
"""

def sumOfSquaresOfDigits(n):
    n = abs(n)
    total = 0
    while n > 0:
        total += (n%10)**2
        n //= 10
    return total

def testSumOfSquaresOfDigits():
    print('Testing sumOfSquaresOfDigits()...', end='')
    assert(sumOfSquaresOfDigits(5) == 25)    # 5**2 = 25
    assert(sumOfSquaresOfDigits(12) == 5)    # 1**2 + 2**2 = 1+4 = 5
    assert(sumOfSquaresOfDigits(234) == 29)  # 2**2 + 3**2 + 4**2 = 4+9+16 = 29
    assert(sumOfSquaresOfDigits(-234) == 29) # 2**2 + 3**2 + 4**2 = 4+9+16 = 29
    print('Passed!')

def main():
    testSumOfSquaresOfDigits()

main()

"""#### Step 6.2: Test isHappy"""

def isHappy(n):
    if n < 1:
        return False
    while (n != 1) and (n != 4):
        n = sumOfSquaresOfDigits(n)
    return n == 1

def sumOfSquaresOfDigits(n):
    n = abs(n)
    total = 0
    while n > 0:
        total += (n%10)**2
        n //= 10
    return total

def testisHappy():
    print('Testing isHappy()...', end='')
    assert(isHappy(1) == True)
    assert(isHappy(2) == False)
    assert(isHappy(13) == True)
    assert(isHappy(14) == False)
    assert(isHappy(10000003) == True)
    assert(isHappy(10000004) == False)
    assert(isHappy(-7) == False)
    print('Passed!')

def main():
    testisHappy()

main()

"""#### Step 6.3: Test isPrime"""

def isPrime(n):
    # Note: there are faster ways to do this!
    if n < 2:
        return False
    for factor in range(2, n):
        if n % factor == 0:
            return False
    return True

def testIsPrime():
    print('Testing isPrime()...', end='')
    assert(isPrime(-2) == False)
    assert(isPrime(1) == False)
    assert(isPrime(2) == True)
    assert(isPrime(3) == True)
    assert(isPrime(4) == False)
    assert(isPrime(29) == True)
    assert(isPrime(49) == False)
    print('Passed!')

def main():
    testIsPrime()

main()

"""#### Step 6.4: Test isHappyPrime"""

def isHappyPrime(n):
    return isHappy(n) and isPrime(n)

def isHappy(n):
    if n < 1:
        return False
    while (n != 1) and (n != 4):
        n = sumOfSquaresOfDigits(n)
    return n == 1

def sumOfSquaresOfDigits(n):
    n = abs(n)
    total = 0
    while n > 0:
        total += (n%10)**2
        n //= 10
    return total

def isPrime(n):
    # Note: there are faster ways to do this!
    if n < 2:
        return False
    for factor in range(2, n):
        if n % factor == 0:
            return False
    return True

def testIsHappyPrime():
    print('Testing isHappyPrime()...', end='')
    assert(isHappyPrime(1) == False)
    assert(isHappyPrime(2) == False)
    assert(isHappyPrime(3) == False)
    assert(isHappyPrime(7) == True)
    assert(isHappyPrime(10) == False)
    assert(isHappyPrime(13) == True)
    print('Passed!')

def main():
    testIsHappyPrime()

main()

"""#### Step 6.5: Test nthHappyPrime"""

def nthHappyPrime(n):
    seen = 0
    guess = 0
    # note: continue looping even when seen == n since we start
    # counting at 0 (so when n == 0, we stop when seen == 1).
    while seen < n + 1:
        guess += 1
        if isHappyPrime(guess):
            seen += 1
    return guess

def isHappyPrime(n):
    return isHappy(n) and isPrime(n)

def isHappy(n):
    if n < 1:
        return False
    while (n != 1) and (n != 4):
        n = sumOfSquaresOfDigits(n)
    return n == 1

def sumOfSquaresOfDigits(n):
    n = abs(n)
    total = 0
    while (n > 0):
        total += (n%10)**2
        n //= 10
    return total

def isPrime(n):
    # Note: there are faster ways to do this!
    if n < 2:
        return False
    for factor in range(2, n):
        if n % factor == 0:
            return False
    return True

def testNthHappyPrime():
    # The first 10 happy primes: 7, 13, 19, 23, 31, 79, 97, 103, 109, 139
    print('Testing nthHappyPrime...', end='')
    assert(nthHappyPrime(0) == 7)
    assert(nthHappyPrime(1) == 13)
    assert(nthHappyPrime(2) == 19)
    assert(nthHappyPrime(3) == 23)
    assert(nthHappyPrime(4) == 31)
    assert(nthHappyPrime(5) == 79)
    assert(nthHappyPrime(6) == 97)
    assert(nthHappyPrime(7) == 103)
    assert(nthHappyPrime(8) == 109)
    assert(nthHappyPrime(9) == 139)
    print('Passed!')

def main():
    testNthHappyPrime()

main()

"""### Step 7: Our Solution

We now just assemble all the code from above, including all the
test functions for all the helper functions.
"""

def nthHappyPrime(n):
    seen = 0
    guess = 0
    # note: continue looping even when seen == n since we start
    # counting at 0 (so when n == 0, we stop when seen == 1).
    while seen < n + 1:
        guess += 1
        if isHappyPrime(guess):
            seen += 1
    return guess

def isHappyPrime(n):
    return isHappy(n) and isPrime(n)

def isHappy(n):
    if n < 1:
        return False
    while (n != 1) and (n != 4):
        n = sumOfSquaresOfDigits(n)
    return n == 1

def sumOfSquaresOfDigits(n):
    n = abs(n)
    total = 0
    while n > 0:
        total += (n%10)**2
        n //= 10
    return total

def isPrime(n):
    # Note: there are faster ways to do this!
    if n < 2:
        return False
    for factor in range(2, n):
        if n % factor == 0:
            return False
    return True

def testSumOfSquaresOfDigits():
    print('Testing sumOfSquaresOfDigits()...', end='')
    assert(sumOfSquaresOfDigits(5) == 25)    # 5**2 = 25
    assert(sumOfSquaresOfDigits(12) == 5)    # 1**2 + 2**2 = 1+4 = 5
    assert(sumOfSquaresOfDigits(234) == 29)  # 2**2 + 3**2 + 4**2 = 4+9+16 = 29
    assert(sumOfSquaresOfDigits(-234) == 29) # 2**2 + 3**2 + 4**2 = 4+9+16 = 29
    print('Passed!')

def testisHappy():
    print('Testing isHappy()...', end='')
    assert(isHappy(1) == True)
    assert(isHappy(2) == False)
    assert(isHappy(13) == True)
    assert(isHappy(14) == False)
    assert(isHappy(10000003) == True)
    assert(isHappy(10000004) == False)
    assert(isHappy(-7) == False)
    print('Passed!')

def testIsPrime():
    print('Testing isPrime()...', end='')
    assert(isPrime(-2) == False)
    assert(isPrime(1) == False)
    assert(isPrime(2) == True)
    assert(isPrime(3) == True)
    assert(isPrime(4) == False)
    assert(isPrime(29) == True)
    assert(isPrime(49) == False)
    print('Passed!')

def testIsHappyPrime():
    print('Testing isHappyPrime()...', end='')
    assert(isHappyPrime(1) == False)
    assert(isHappyPrime(2) == False)
    assert(isHappyPrime(3) == False)
    assert(isHappyPrime(7) == True)
    assert(isHappyPrime(10) == False)
    assert(isHappyPrime(13) == True)
    print('Passed!')

def testNthHappyPrime():
    # The first 10 happy primes: 7, 13, 19, 23, 31, 79, 97, 103, 109, 139
    print('Testing nthHappyPrime...', end='')
    assert(nthHappyPrime(0) == 7)
    assert(nthHappyPrime(1) == 13)
    assert(nthHappyPrime(2) == 19)
    assert(nthHappyPrime(3) == 23)
    assert(nthHappyPrime(4) == 31)
    assert(nthHappyPrime(5) == 79)
    assert(nthHappyPrime(6) == 97)
    assert(nthHappyPrime(7) == 103)
    assert(nthHappyPrime(8) == 109)
    assert(nthHappyPrime(9) == 139)
    print('Passed!')

def main():
    testSumOfSquaresOfDigits()
    testisHappy()
    testIsPrime()
    testIsHappyPrime()
    testNthHappyPrime()

main()

"""With that, we have solved the problem nthHappyPrime using top-down design!"""