# -*- coding: utf-8 -*-
"""5 - Strings (Part 1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1etY9ec3a_1PKJ0vaICFCpZ29m5w8euEL

<font size="1" color="#AAA">Python Fundamentals &copy; David Kosbie</font>  

# Strings (Part 1)
We will explore *strings* in detail in the next section.  Here, though,
we introduce some important strings concepts so we can
start solving more authentic (and a bit less mathy) problems.

## String Operators

### The = Operator
We use `=` to assign a string (or any other value) to a variable.
"""

s = 'This is a string'
print(s)

"""### The + Operator
We use `+` to *concatenate* two strings.
"""

s = 'abc' + 'def'
print(s)

s = 'This is' + 'an example'
print(s) # surprised?

s = 'This is' + ' ' + 'an example'
print(s)

"""### The += Operator
We use `s += t` as a shorthand for `s = s + t`.
"""

# Instead of this:
s = 'abc'
s = s + 'def'
print(s)

# We can do this:
s = 'abc'
s += 'def'
print(s)

"""### The * Operator
We use `*` to concatenate several copies of a string.
"""

s = 'abc' * 5
print(s)

"""### The *= Operator
We use `s *= n` as a shorthand for `s = s * n`.
"""

# Instead of this:
s = 'abc'
s = s * 5
print(s)

# We can do this:
s = 'abc'
s *= 5
print(s)

"""### The == Operator
We use `==` to test strings (or any other values) for equality.
"""

s = 'abc'
print(s == 'abc')
print(s == 'def')

"""### The != Operator
We use `!=` (read "not equals") to test strings (or any other values)
for *inequality*.
"""

s = 'abc'
print(s != 'abc')
print(s != 'def')

"""### The in Operator
We use `in` to test if a string occurs in another string.
"""

s = 'abcdef'
print('a' in s)
print('bc' in s)
print('z' in s)
print('A' in s) # surprised?
print('be' in s) # surprised?

"""### The not in Operator
We use `not in` to test if a string does not occur in another string.
"""

s = 'abcdef'
print('a' not in s)
print('bc' not in s)
print('z' not in s)
print('A' not in s)
print('be' not in s)

"""### The Indexing Operator
We use `[i]` (the *indexing* operator) to access the ith character in
a string, counting from 0.
"""

s = 'abc'
print(s[0])
print(s[1])
print(s[2])

"""Python will raise an exception (that is, crash) if
the index is greater than or equal to the length of the string.
"""

s = 'abc'
print(s[3]) # crashes ('string index out of range')

"""### The Slicing Operator
We use `s[i:j]` to access a *slice* (or *substring*) of the string,
starting at the ith character and ending at the character before
the jth character.

  * Because s[i] is part of the slice, we say i is *inclusive*.
  
  * Because s[j] is not part of the slice, we say j is *exclusive*.
"""

s = 'abcdef'
print(s[2:4])

"""If we omit i, it defaults to 0 (the start of the string)."""

s = 'abcdef'
print(s[:4])

"""If we omit j, it defaults to the end of the string (the string's length)."""

s = 'abcdef'
print(s[2:])

"""## String-Related Functions

### len
We use `len(s)` to find the length of the string s.
"""

s = 'abcdef'
print(len(s))

s = '' # the empty string
print(len(s))

"""### int
We use `int(s)` to convert a string (or any value) to an int.
"""

s = '123'
n = int(s)
print(n)
print(type(n))

"""Python will raise an exception (that is, crash)
if the string cannot be converted to an int.
"""

s = 'oh no!'
n = int(s) # crashes ('invalid literal for int()')

"""### str
We use `str(n)` to convert an int (or any value) to a string.
"""

n = 123
s = str(n)
print(s)
print(type(s))

"""## String Methods

### s.upper
We use `s.upper()` to convert a string to uppercase.

Non-letters are not changed.
"""

s = 'I have 3 dogs and 2 cats!'
print(s.upper())

"""### s.lower
We use `s.lower()` to convert a string to lowercase.

Again, non-letters are not changed.
"""

s = 'I have 3 dogs and 2 cats!'
print(s.lower())

"""### s.isalpha
We use `s.isalpha()` to test if a string is *alphabetic*
(composed only of letters).
"""

s = 'abcdef'
print(s.isalpha())

s = 'abc123'
print(s.isalpha())

"""### s.count
We use `s.count(t)` to find the count of the number of times
the string t occurs in the string s.
"""

s = 'abc bc c'
print(s.count('a'))
print(s.count('bc'))
print(s.count('c'))
print(s.count('d'))
print(s.count(' ')) # counting spaces

"""## Multiline Strings
A *multiline string* is a string that contains a *newline* character.

### Triple-Quotes
We use triple-quotes to include newlines in strings.
"""

s = '''This is
a multiline string'''
print(s)

"""We can use a `\` (backslash) to ignore the first newline."""

s = '''\
This is
a multiline string'''
print(s)

"""If we did not use the `\`, we would get an unwanted extra newline at
the start of the string.
"""

# This string has an unwanted newline at the start:
s = '''
This is
a multiline string'''
print(s)

"""### \n
We use `\n` to add a newline to a string.
"""

line1 = 'This is a line.'
line2 = 'This is another line.'
s = line1 + '\n' + line2
print(s)

"""If we omit the `\n` the result is on the same line."""

# This omits the \n so the result is just one line
line1 = 'This is a line.'
line2 = 'This is another line.'
s = line1 + line2
print(s)

"""A newline counts as just one character in the length of a string."""

s = 'abc' + '\n' + 'def'
print(s)
print(len(s)) # surprised?

"""We can create multiline strings using either triple-quotes or \\n.

They look different in the code, but they create identical strings.
"""

s = '''\
Hello
there'''

t = 'Hello\nthere'

print(s == t)

"""## String Constants

### string.ascii_lowercase
We can use `string.ascii_lowercase` if we need a string with
all the lowercase letters (in order).

Be sure to import string first!
"""

import string
s = string.ascii_lowercase
print(s)

"""### string.ascii_uppercase
We can use `string.ascii_uppercase` if we need a string with
all the uppercase letters (in order).
"""

import string
s = string.ascii_uppercase
print(s)

"""## Looping Over Strings

### Looping over Characters
We use `for c in s` to loop the variable c over each character
in the string s.
"""

s = 'abcd'
for c in s:
    print(f'The next letter is {c}')

"""### Looping over Indexes
We use `for i in range(len(s))` to loop the variable i over each valid *index*
of the string s.

Then we use `s[i]` to access the ith character in s.
"""

s = 'abcd'
for i in range(len(s)):
    c = s[i]
    print(f'Character {i} is {c}')

"""### Reverse Looping over Indexes
We use `for i in range(len(s)-1, -1, -1)` to loop the variable i
*in reverse order* over each valid index of s.
"""

s = 'abcd'
for i in range(len(s)-1, -1, -1):
    c = s[i]
    print(f'Character {i} is {c}')

"""### Looping over Lowercase Letters
We use `for letter in string.ascii_lowercase` to loop
over the lowercase letters in alphabetic order.
"""

import string

s = 'So much FUN!'
for letter in string.ascii_lowercase:
    if letter in s:
        print(f'{letter} is in the string')

"""### Looping over Uppercase Letters
We use `for letter in string.ascii_uppercase` to loop
over the uppercase letters in alphabetic order.
"""

import string

s = 'This is FUN!'
for letter in string.ascii_uppercase:
    if letter in s:
        print(f'{letter} is in the string')

"""### Looping over Words
We use `for word in s.split()` to loop over the words in s.
"""

s = 'This is a test'
for word in s.split():
    print(f'The next word is {word}')

"""When using `s.split()`, Python will include punctuation as part of words."""

s = 'This is a test, only a test!'
for word in s.split():
    print(f'The next word is {word}')

"""When using `s.split()`, Python also treats newlines as spaces,
and collapses multiple spaces.
"""

s = '''\
This    is    line1.
And    this    is     line2.'''
for word in s.split():
    print(f'The next word is {word}')

"""## Modifying Strings

### Strings are Immutable
Strings in Python are *immutable*,
meaning we cannot change (or mutate) them.

Specifically, for a string s, if we try to set the character at s[i], Python crashes.
"""

s = 'abcde'
s[2] = 'z' # this crashes because strings are immutable

"""### Replacing Characters
While we cannot set s[i] to a new string t, we can do something very similar:

  * Create a new string with:
  
    * the letters in s up to i (that is, `s[:i]`), then

    * the new string t, then
    
    * the letters in s after i (that is, `s[i+1:]`)

  * Assign this new string back to s
"""

s = 'abcde'
s = s[:2] + 'z' + s[3:]
print(s) # works!

"""In fact, this works over a substring or slice of s."""

s = 'abcde'
# Let's replace 'bcd' with 'z':
s = s[:1] + 'z' + s[4:]
print(s)