# -*- coding: utf-8 -*-
"""7 - Additional Topics (Loops).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B2tcskwY25RV478A6TpntetirA1DISkv

<font size="1" color="#AAA">Python Fundamentals &copy; David Kosbie</font>  

# Additional Topics (Loops)
Here are some additional topics that are not part of the core curriculum.
However, they are likely to be useful to you in your coding future.
If you are new to Python, you can skip these topics for now and
return later.  For those of you with some Python experience,
you may find some useful concepts here that are new to you.

## Modifying the Loop Variable in a For Loop
In a for loop, the loop variable advances to the next value
before each pass, even if you modified the loop variable in the loop.
"""

for x in range(3):
    print(f'At the top of the body, x = {x}')
    x += 4
    print(f'At the bottom of the body, modified x = {x}')

"""## Loop Variable Value after a For Loop
In many languages (like C, Java, and JavaScript), if you loop a variable i
over the integers from 0 (inclusive) to 5 (exclusive) -- that is, a range from 0 to 5 --
then after the loop, i will be set to 5.  This is not true in Python.
"""

for i in range(5):
    pass
print(i) # surprised?

"""## Scoping and Loops
In many languages (like C, Java, and JavaScript), you can define loop variables whose scope
is limited to just that loop.  Again, this is not true in Python.
All local variables in Python are scoped to the entire function they are in,
and never any finer-grained than that.

## Enumerate

It is sometimes handy to iterate over both the values in a sequence and
the indexes of those values.  The `enumerate` function lets us to exactly that.
"""

# Using enumerate with a range:
for i, x in enumerate(range(10, 30, 5)):
    print(f'On pass #{i}, x = {x}')

# Using enumerate with a string:
for i, c in enumerate('Hello'):
    print(f'On pass #{i}, c = {c}')

"""You never are required to use enumerate, since you can always loop over just the indexes and then use the index to access the corresponding value in the sequence, like so:"""

# Previous example, without enumerate:
R = range(10, 30, 5)
for i in range(len(R)):
    x = R[i]
    print(f'On pass #{i}, x = {x}')

"""This approach is almost never used with ranges, but it sometimes used
with strings and lists.

## More on the Walrus Operator

One common use of the *walrus operator* (`:=`) is in the condition
of a while loop.

Here is an earlier example rewritten to use a walrus operator:
"""

print('Keep entering integers to get their sum.  Enter 0 to stop.')
total = 0

while (n := int(input('Next integer (or 0 to stop) --> '))) != 0:
    print(f'The total so far is {total}')
    total += n

print(f'We have exited the loop.  The final total is {total}')

"""## For-else and While-else

Loops can include an else clause after the body.  The else clause runs
after the loop completes.

This is rarely used in practice, but it is valid Python.
"""

# A for loop with an else clause:
for x in range(3):
    print(f'inside the body, x = {x}')
else:
    print(f'in the else clause, x = {x}')
print(f'afterwards, x = {x}')

# A while loop with an else clause:
x = 1
while x < 10:
    x *= 2
    print(f'inside the body, x = {x}')
else:
    print(f'in the else clause, x = {x}')
print(f'afterwards, x = {x}')

"""In either kind of loop, the else clause is not executed if the loop was terminated by a break or a return (if inside a function)."""

# A for loop with an else clause and a break statement:
for x in range(3):
    if x == 2:
        break
    print(f'inside the body, x = {x}')
else:
    print(f'in the else clause, x = {x}')
print(f'afterwards, x = {x}')