# -*- coding: utf-8 -*-
"""Level 1 missingValue.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ka5pi4LSQqw3RwDGI4b3Vt_CGcI7P3XV

Write the function missingValue(L, M) that takes two lists L and M where M contains the same values as L, perhaps in a different order, but with one value missing.
  
  

Thus, you are guaranteed that len(M) \=\= len(L) \- 1\.
  
  

Your function should return the missing value.
  
  

Be sure not to mutate (change) L or M.
  
  

Hint: it may help to compare sorted versions of L and M and
find the first index where they differ.
  
  

For example:

```

    assert(missingValue([1,2,3], [3,1]) == 2)
    assert(missingValue([1,2,3], [2,1]) == 3)
    assert(missingValue(['A', 'B', 'A', 'C'], ['C', 'A', 'B']) == 'A')
    assert(missingValue(['A', 'B', 'A', 'C'], ['A', 'A', 'B']) == 'C')
    assert(missingValue([2,2], [2]) == 2)
    assert(missingValue([2,3], [2]) == 3)
    assert(missingValue([2,3], [3]) == 2)
    assert(missingValue(['amazing'], [ ]) == 'amazing')

```
"""

def missingValue(L, M):
    sorted_L = sorted(L)
    sorted_M = sorted(M)
    for i in range(len(sorted_M)):
        if sorted_L[i] != sorted_M[i]:
            return sorted_L[i]
    return sorted_L[-1]

def testMissingValue():
    print('Testing missingValue()...', end='')
    assert(missingValue([1,2,3], [3,1]) == 2)
    assert(missingValue([1,2,3], [2,1]) == 3)
    assert(missingValue(['A', 'B', 'A', 'C'], ['C', 'A', 'B']) == 'A')
    assert(missingValue(['A', 'B', 'A', 'C'], ['A', 'A', 'B']) == 'C')
    assert(missingValue(['A', 'B', 'A', 'C'], ['A', 'C', 'A']) == 'B')
    assert(missingValue([2,2], [2]) == 2)
    assert(missingValue([2,3], [2]) == 3)
    assert(missingValue([2,3], [3]) == 2)
    assert(missingValue(['amazing'], [ ]) == 'amazing')

    # Make sure the function is non-mutating
    L = [1, 2, 3]
    M = [3, 1]
    assert(missingValue(L, M) == 2)
    assert(L == [1, 2, 3])
    assert(M == [3, 1])
    print('Passed!')

def main():
    testMissingValue()

main()