# -*- coding: utf-8 -*-
"""Level 1 sortedEvens.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PwvhTFAiwGpPI3eXYY395bMM279y-ZY7

Write the function sortedEvens(L) that takes a list L of ints and
returns a new list of just the even numbers in L in sorted order.
"""

def sortedEvens(L):
    evens = [x for x in L if x % 2 == 0]
    return sorted(evens)

def testSortedEvens():
    print('Testing sortedEvens()...', end='')
    assert(sortedEvens([1, 4, 3, 2, 5]) == [2, 4])
    assert(sortedEvens([1, 3, 2, 5]) == [ 2 ])
    assert(sortedEvens([6, 4, -2, 8, 4, 0, 9]) == [ -2, 0, 4, 4, 6, 8 ])
    assert(sortedEvens([1, 3, 5]) == [ ])
    assert(sortedEvens([ ]) == [ ])

    # confirm this is non-mutating:
    L = [1, 4, 3, 2, 5]
    assert(sortedEvens([1, 4, 3, 2, 5]) == [2, 4])
    assert(L == [1, 4, 3, 2, 5])
    print('Passed!')

def main():
    testSortedEvens()

main()