# -*- coding: utf-8 -*-
"""Level 1 median.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W53EEb3UzVp0j-jXB7oP2hcFvb-UutF7

Write the non\-mutating function `median(L)` which takes a `list`
`L` of integer or float values and returns the median value. The median
 value is the middle element, or the average of two middle elements, of all the
 numbers in numerical order. If the list is empty, return `None`.




 Note: Do not use `statistics.median()` here.
"""

def almostEqual(x, y):
    return (abs(x - y) < 10**-9)


def median(L):
    if len(L) == 0:
        return None
    sorted_L = sorted(L)
    n = len(sorted_L)
    mid = n // 2
    if n % 2 == 1:
        return sorted_L[mid]
    else:
        return (sorted_L[mid - 1] + sorted_L[mid]) / 2

def testMedian():
    print('Testing median()...', end='')
    assert(median([42]) == 42)
    assert(almostEqual(median([1, 2]), 1.5))
    assert(median([-1.7, 3, -2, 4.2, 2]) == 2)
    assert(median([2, 3, 2, 4, 2]) == 2)
    assert(almostEqual(median([2, 3, 2, 4, 2, 3]), 2.5))
    assert(median([]) == None)

    # Verify function is non-mutating
    L = [1, 3, 2]
    assert(median(L) == 2)
    assert(L == [1, 3, 2])

    print('Passed!')

def main():
    testMedian()

main()