# -*- coding: utf-8 -*-
"""Level 1 hasNoDuplicates.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yuRTE-dFH6hwO6Gb2YdmA04d5of-FtkQ

Write the function `hasNoDuplicates(L)` which takes a `list`
`L`, and returns `True` if `L` has no
 duplicate values (so every value in `L` is unique) and
 `False` otherwise.




 For example:
 * `hasNoDuplicates([1,2,3,2]) == False`
* `hasNoDuplicates([1,2,3,4]) == True`






 Note: Recall that in this unit, you cannot create new lists or
 mutate existing lists. Instead, think of a clever way to use sets to
 solve the problem.
"""

def hasNoDuplicates(L):
    return len(L) == len(set(L))

def testHasNoDuplicates():
    print('Testing hasNoDuplicates()...', end='')
    assert(hasNoDuplicates([1,2,3,2]) == False)
    assert(hasNoDuplicates([1,2,3,4]) == True)
    assert(hasNoDuplicates([ ]) == True)
    assert(hasNoDuplicates([42]) == True)
    assert(hasNoDuplicates([42, 42]) == False)

    # Verify that the function is nonmutating:
    L = [1,2,3,2]
    hasNoDuplicates(L)
    assert(L == [1,2,3,2])
    print('Passed!')

def main():
    testHasNoDuplicates()

main()