# -*- coding: utf-8 -*-
"""Level 1 movieAwards.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XWGbE4fb9QVbKt62gkKeYHX8GMM8ka_G

Write the function `movieAwards(oscarResults)` which takes a set of tuples,
 where each tuple holds the name of a category and the name of the winning movie, and returns
 a dictionary mapping each movie to the number of awards it won. For example, if we provide the set:




```

{
    ("Best Picture", "Green Book"),
    ("Best Actor", "Bohemian Rhapsody"),
    ("Best Actress", "The Favourite"),
    ("Film Editing", "Bohemian Rhapsody"),
    ("Best Original Score", "Black Panther"),
    ("Costume Design", "Black Panther"),
    ("Sound Editing", "Bohemian Rhapsody"),
    ("Best Director", "Roma")
}
```

the function should return:



```

{
    "Black Panther" : 2,
    "Bohemian Rhapsody" : 3,
    "The Favourite" : 1,
    "Green Book" : 1,
    "Roma" : 1
}
```


 Note: Remember that sets and dictionaries are unordered, so the returned
 dictionary may be in a different order than what we have shown for the example above, and that is ok.
"""

def movieAwards(oscarResults):
    awards_count = {}
    for category, movie in oscarResults:
        if movie in awards_count:
            awards_count[movie] += 1
        else:
            awards_count[movie] = 1
    return awards_count

def testMovieAwards():
    print('Testing movieAwards()...', end='')
    test = {('Best Picture', 'The Shape of Water'),
            ('Best Actor', 'Darkest Hour'),
            ('Best Actress', 'Three Billboards Outside Ebbing, Missouri'),
            ('Best Director', 'The Shape of Water')}
    result = {'Darkest Hour': 1,
              'Three Billboards Outside Ebbing, Missouri': 1,
              'The Shape of Water': 2}
    assert(movieAwards(test) == result)

    test = {('Best Picture', 'Moonlight'),
            ('Best Director', 'La La Land'),
            ('Best Actor', 'Manchester by the Sea'),
            ('Best Actress', 'La La Land')}
    result = {'Moonlight': 1,
              'La La Land': 2,
              'Manchester by the Sea': 1}
    assert(movieAwards(test) == result)

    test = {('Best Picture', '12 Years a Slave'),
            ('Best Director', 'Gravity'),
            ('Best Actor', 'Dallas Buyers Club'),
            ('Best Actress', 'Blue Jasmine')}
    result = {'12 Years a Slave': 1,
              'Gravity': 1,
              'Dallas Buyers Club': 1,
              'Blue Jasmine': 1}
    assert(movieAwards(test) == result)

    test = {('Best Picture', 'The King\'s Speech'),
            ('Best Director', 'The King\'s Speech'),
            ('Best Actor', 'The King\'s Speech')}
    result = {'The King\'s Speech': 3}
    assert(movieAwards(test) == result)

    test = {('Best Picture', 'Spotlight'), ('Best Director', 'The Revenant'),
            ('Best Actor', 'The Revenant'), ('Best Actress', 'Room'),
            ('Best Supporting Actor', 'Bridge of Spies'),
            ('Best Supporting Actress', 'The Danish Girl'),
            ('Best Original Screenplay', 'Spotlight'),
            ('Best Adapted Screenplay', 'The Big Short'),
            ('Best Production Design', 'Mad Max: Fury Road'),
            ('Best Cinematography', 'The Revenant')}
    result = {'Spotlight': 2,
              'The Revenant': 3,
              'Room': 1,
              'Bridge of Spies': 1,
              'The Danish Girl': 1,
              'The Big Short': 1,
              'Mad Max: Fury Road': 1}
    assert(movieAwards(test) == result)

    assert(movieAwards(set()) == dict())
    print('Passed!')

def main():
    testMovieAwards()

main()