# -*- coding: utf-8 -*-
"""TBc3Oct14.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QoYyW4W66Dfp8j-GLBjGY1-e2OFMe6uP
"""

import time

print("before")
time.sleep(10)
print("after")

def blastoff(tMinus):
    print(f't minus {tMinus}')
    time.sleep(1)
    blastoff(tMinus - 1)

blastoff(10)

def blastoff(tMinus):
    if tMinus == 0:
        return print("BLASTOFF!!!!")
    print(f't minus {tMinus}')
    time.sleep(1)
    blastoff(tMinus - 1)

blastoff(10)

def blastoff(tMinus):
    if tMinus == 0:
        return print("BLASTOFF!!!!")
    print(f't minus {tMinus}')
    time.sleep(1)
    blastoff(tMinus - 1)

blastoff(10)

def blastoff(tMinus):
    if tMinus == 0:
        print("BLASTOFF!!!!")
    else:
        print(f't minus {tMinus}')
        time.sleep(1)
        blastoff(tMinus - 1)

def mvcGameLoop():
    events = getEvents() # controller
    for event in events:
        handleEvent(event) # model
    for ob in gameObs: # view
        paint(ob)
    mvcGameLoop()

def mvcGameLoopWhile():
    gameIsRunning = True
    while gameIsRunning:
        events = getEvents() # controller
        for event in events:
            handleEvent(event) # model
        for ob in gameObs: # view
            paint(ob)

fruits = ["apple", "banana", "cherry", "durian"]

def listFruits(fruits):
    for fruit in fruits:
        print(fruit)

# listFruits(fruits)
def recursiveForLoop(fruits):
    # if not fruits:
    if len(fruits) == 0:
        return print("end of fruits")
    firstFruit, rest = fruits[0], fruits[1:]
    print(firstFruit)
    recursiveForLoop(rest)
recursiveForLoop(fruits)

def bottom():
    print("start bottom")
    middle()
    print("finish bottom")

def middle():
    print("start middle")
    top()
    print("finish middle")

def top():
    print("start top")
    print("cherry")
    print("finish top")

bottom() #illustrates call stack in python tutor

"""# Simulation"""

students = ["bushra", "nick", "matt", "tom", "renny", "max", "vicky", "lane", "samuel", "vani"]
students2 = students + students[-1:]

def containsDuplicateStudents_viaList(students):
    for i, a in enumerate(students):
        for b in students[i+1:]:
            # print(a, b, a == b, sep="\t")
            if a == b:
                return True
    return False

students2

import random

def runOneTrial():
    random.shuffle(students2)
    before = time.time()
    containsDuplicateStudents_viaList(students=students2)
    after = time.time()
    return after - before

def estimateAverage(trials):
    total = 0
    for _ in range(trials):
        total += runOneTrial()
    return total/trials

for trials in [10**2, 10**3, 10**4, 10**5]:
    print(trials, estimateAverage(trials))

results = []
for _n in range(5):
    trial_results = []
    for trials in [10**2, 10**3, 10**4, 10**5]:
        # print(trials, estimateAverage(trials))
        trial_results.append(estimateAverage(trials))
    results.append(trial_results)
results

import statistics
dir(statistics)

resultCols = [ list(col) for col in zip(*results) ]

def transpose (L2d):
    return [ list(col) for col in zip(*results) ]

test_list = [[1, 2] [3, 4]]
transposed_test = transpose(test_list)
transposed_test

zip([1,2], ["a", "b"])

list(zip([1,2], ["a", "b"]))

listOfLists = [[1   ,2],
               ["a" ,"b"]]
list(zip(*listOfLists))

def transpose (L2d):
    return list(zip(*L2d))

test_list = [[1, 2] [3, 4]]
transposed_test = transpose(test_list)
transposed_test

test_list = [[1, 2], [3, 4]]
transposed_test = transpose(test_list)
transposed_test

def transpose (LL):
    return [ list(col) for col in zip(*LL) ]

def transpose(A):
    return list(map(list, zip(*A)))

def packer(*args):
    print(args)

packer("green", "bay")

print(*"a string")

print(repr(*"a string"))

*"a string"

print(repr("a string"))

x , y = 100, 250

def total(*inputs):
    print(inputs)
    totes = 0
    for input in inputs:
        totes += input
    return totes

total(1,2,3)

def passKwargs(**kwargs):
    print(kwargs)

passKwargs(name="nick",truck="ram", hasTent=True)

def lotsOfArgs(n, *rest, **kwargs):
    print(n)
    print(rest)
    print(kwargs)

lotsOfArgs(1,2,3,4,5,6, cpm="gt")

lotsOfArgs(2,3,4,5,6, cpm="gt", n=1)

zip(*test_list)

list(zip(*test_list))

map(list, zip(*test_list))

list(map(list, zip(*test_list)))

def transpose(A):
    return list(map(list, zip(*A)))

test_list = [[1, 2], [3, 4]]
transposed_test = transpose(test_list)
transposed_test

def transpose2(LL):
    return [list(col) for col in zip(*LL)]

test_list = [[1, 2], [3, 4]]
transposed_test = transpose2(test_list)
transposed_test

def transpose3(LL):
    result = []
    for colTuple in zip(*LL):
        result.append(list(colTuple))
    return result

test_list = [[1, 2], [3, 4]]
transposed_test = transpose3(test_list)
transposed_test

results = []
for _n in range(5):
    trial_results = []
    for trials in [10**2, 10**3, 10**4, 10**5]:
        # print(trials, estimateAverage(trials))
        trial_results.append(estimateAverage(trials))
    results.append(trial_results)
results

resultCols = transpose(results)

resultCols

for trials in resultCols:
    longest = max(trials)
    shortest = min(trials)
    range = longest - shortest
    print(range)

def runOneTrial(studentList):
    random.shuffle(studentList)
    before = time.time()
    containsDuplicateStudents_viaList(studentList)
    after = time.time()
    return after - before

def estimateAverage(trials, studentList):
    total = 0
    for _ in range(trials):
        total += runOneTrial(studentList)
    return total/trials

for studentNumber in [10, 20, 40, 80]:
    print(studentNumber)
    studentList = range(studentNumber)
    print(studentList)
    # studentList += studentList[-1:]
    # print(estimateAverage(10**5, studentList))

# results = []
# for _n in range(5):
#     trial_results = []
#     for trials in [10**2, 10**3, 10**4, 10**5]:
#         # print(trials, estimateAverage(trials))
#         trial_results.append(estimateAverage(trials))
#     results.append(trial_results)
# results

range #OOPS don't overwrite builtins

globals()["range"]

# now restart the runtime

def runOneTrial(studentList):
    random.shuffle(studentList)
    before = time.time()
    containsDuplicateStudents_viaList(studentList)
    after = time.time()
    return after - before

def estimateAverage(trials, studentList):
    total = 0
    for _ in range(trials):
        total += runOneTrial(studentList)
    return total/trials

for studentNumber in [10, 20, 40, 80]:
    studentList = list(range(studentNumber))
    studentList += studentList[-1:]
    print(estimateAverage(10**5, studentList))

# results = []
# for _n in range(5):
#     trial_results = []
#     for trials in [10**2, 10**3, 10**4, 10**5]:
#         # print(trials, estimateAverage(trials))
#         trial_results.append(estimateAverage(trials))
#     results.append(trial_results)
# results

import random, time