# -*- coding: utf-8 -*-
"""Level 1 oddCount.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1of2E7HRyoHfDlaN9FVAA31UXMcSEh7Rl

Note: you may not use `for` or `while` loops here.
Instead, use recursion.
  
  

With that in mind, write the recursive function `oddCount(L)`
that takes a list L of integers, and returns a count of the number of
odd integers in L.
  
  

For example, `oddCount([2,3,4,3,6])` returns 2, because there
are two odd numbers in that list (both 3's).
"""

def oddCount(L):
    if L == []:
        return 0
    elif L[0] % 2 != 0:
        return 1 + oddCount(L[1:])
    else:
        return oddCount(L[1:])

def testOddCount():
    print('Testing oddCount()...', end='')
    assert(oddCount([]) == 0)
    assert(oddCount([1]) == 1)
    assert(oddCount([2]) == 0)
    assert(oddCount([1,2,3,4,5,4,3]) == 4)
    assert(oddCount([1,2,3,4,5,4,3,2]) == 4)
    assert(oddCount([2,4,6,8,10,12,14]) == 0)
    assert(oddCount([1,1,1,1,1]) == 5)
    print('Passed!')

def main():
    testOddCount()

main()