# -*- coding: utf-8 -*-
"""Level 1 oddSum.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15BoX73TM-FPbVDUeAt6Xu66M9MC03Hku

Note: you may not use `for` or `while` loops here.
Instead, use recursion.
  
  

With that in mind, write the recursive function `oddSum(L)`
that takes a list L of integers, and returns the sum of just the
odd integers in L.
  
  

For example, `oddSum([2,3,4,3,6])` returns 6 (3\+3\).
  
  

If there are no odd values in the list, return 0\.
"""

def oddSum(L):
    if L == []:
        return 0
    elif L[0] % 2 != 0:
        return L[0] + oddSum(L[1:])
    else:
        return oddSum(L[1:])

def testOddSum():
    print('Testing oddSum()...', end='')
    assert(oddSum([]) == 0)
    assert(oddSum([1]) == 1)
    assert(oddSum([2]) == 0)
    assert(oddSum([1,2,3,4,5,4,3]) == 12)   # 1+3+5+3
    assert(oddSum([1,2,3,4,5,4,3,2]) == 12) # 1+3+5+3
    assert(oddSum([2,4,6,8,10,12,14]) == 0)
    assert(oddSum([1,1,1,1,1]) == 5) # 1+1+1+1+1
    print('Passed!')

def main():
    testOddSum()

main()