# -*- coding: utf-8 -*-
"""Level 1 twoHeadsInFiveFlips.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hXdFfGwbHl2xGGW_OVmVpPRtb15MTSob

This problem is inspired by
[this page](https://courses.washington.edu/psy524a/_book/the-binomial-distribution.html) of probability problems.
  
  

That page shows that the probability of getting exactly 2 heads in 5 coin flips
is 0\.3125\.
  
  

Your task here is to use Monte Carlo methods to estimate this probability.
  
  

More specifically, write the function estimateProbability(trials) that
runs the given number of trials, where each trial succeeds if it flips
5 coins and exactly 2 of them are heads.
  
  

To be judged correct, you need to be reasonably close to the actual answer
as the number of trials increases. See the test code for details.
  
  

Also, note that the helper function flipCoin() has been provided for you.
  
  

Good luck!
"""

import random

def flipCoin():
    return random.choice('HT')

def estimateProbability(trials):
    success = 0
    for _ in range(trials):
        flips = [flipCoin() for _ in range(5)]
        if flips.count('H') == 2:
            success += 1
    return success / trials

def testTwoHeadsInFiveFlipsProblem():
    print('Testing the twoHeadsInFiveFlips Problem...', end='')
    trials = 10**5
    p = estimateProbability(trials)
    assert(0.30 <= p <= 0.32) # actual answer is about 0.313
    print('Passed!')

def main():
    testTwoHeadsInFiveFlipsProblem()

main()