# -*- coding: utf-8 -*-
"""Level 1 reversedEvens.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gqOtHw0jW3YpJwuQnaUMcdotvpJS0Haz

Without using iteration (for or while loops), write the recursive function
reversedEvens(L) that takes a list L and returns a list of just the even
values in L in reverse order.
"""

def reversedEvens(L):
    if L == []:
        return []
    elif L[-1] % 2 == 0:
        return [L[-1]] + reversedEvens(L[:-1])
    else:
        return reversedEvens(L[:-1])

def testReversedEvens():
    print('Testing reversedEvens()...', end='')
    assert(reversedEvens([]) == [])
    assert(reversedEvens([1]) == [])
    assert(reversedEvens([1,2]) == [2])
    assert(reversedEvens([1,2,3]) == [2])
    assert(reversedEvens([1,2,3,4]) == [4,2])
    assert(reversedEvens([1,2,3,4,5,6,5,4,5,6,7]) == [6,4,6,4,2])
    print('Passed!')

def main():
    testReversedEvens()

main()