# -*- coding: utf-8 -*-
"""Level 2 getHoursLogged.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10YpYUz9A-Fog4GZhDA3a_1DoZFY8bCzx

#### Problem Writeup




 Background: We can represent the times a person starts and
 stops working as a list of `(time, person)` tuples.
 Each person will have exactly two logs in the list:
 one for the time they check\-in to work and one for the time
 they check\-out of work. For example, consider the following list:

```

L = [(0, 'Spongebob'), (10, 'Krabs'), (30, 'Squidward'),
     (55, 'Krabs'), (250, 'Squidward'), (300, 'Spongebob')]
```

 This means that Spongebob works between minutes 0 and 300,
 Krabs works between minutes 10 and 55, and
 Squidward works between minutes 30 and 250\.



 With this in mind, write the function `getHoursLogged(logs)`,
 which takes such a list, and returns a dictionary mapping each person in
 the logs to the total number of minutes they worked.
 You are guaranteed that the tuples are ordered by the time values.
 For the above list, your function should return `{ 'Spongebob': 300, 'Krabs': 45, 'Squidward' : 220 }`.



#### Guided Solution
"""

import copy

def getHoursLogged(logs):
    return 42

def testGetHoursLogged():
    print('Testing getHoursLogged()...', end='')
    logs1 = [(0, 'Spongebob'), (10, 'Krabs'), (30, 'Squidward'),
             (55, 'Krabs'), (250, 'Squidward'), (300, 'Spongebob')]
    assert(getHoursLogged(logs1) ==
        {'Spongebob': 300, 'Krabs': 45, 'Squidward': 220})

    logs2 = [(10, 'A'), (20, 'A')]
    assert(getHoursLogged(logs2) == {'A': 10})

    logs3 = [(10, 'A'), (20, 'A'), (21, 'B'), (22, 'B')]
    assert(getHoursLogged(logs3) == {'A': 10, 'B': 1})

    assert(getHoursLogged([]) == dict())

    # Verify that the function is nonmutating:
    L = [(10, 'A'), (20, 'A')]
    getHoursLogged(L)
    assert(L == [(10, 'A'), (20, 'A')])
    print('Passed!')

def main():
    testGetHoursLogged()

main()