# -*- coding: utf-8 -*-
"""Level 2 integerLetterFrequencies.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JAfQavO1BeGp3otAUsysy2cbeieKdIjc

Background: Given a string `s`, the "frequency" of a letter
 in `s` is the letter's count divided by the length of
 `s`, expressed as a percentage (i.e. multiplied by 100\).
 So, the frequency of 'a' in the string 'abcabcab' can be calculated as
 follows:
 * Number of Occurences of 'a': 3
* Length of String: 8
* Frequency of 'a' in 'abcabcab': (3 / 8\) \* 100 \= 37\.5






 The "integer frequency" of a letter in `s` is the
 integer floor of its frequency (i.e. the largest integer less than or
 equal to the calculated frequency). Thus, the integer frequency
 for the above example is 37\.




 With that in mind, write the function `integerLetterFrequencies(s)`
 that takes a string `s` and returns a dictionary mapping
 each *uppercase* letter from 'A' to 'Z' to its corresponding integer
 frequency in `s`. Note that:
 * Your dictionary should not include letters that never occur in
 `s` nor non\-letters (like digits, spaces, and punctuation).
* Your function should be case insensitive. A lowercase 'a' in
 `s` counts as an uppercase 'A'.






 For example, if we consider the string 'abca\-bcab', we can obtain
 `integerLetterFrequencies('abca-bcab')` as follows:
 * Length of 'abca\-bcab': 9
* Integer Frequencies of Its Letters:
	+ 'A': (3 / 9\) \* 100 \= 33\.333\... \-\-\> 33
	+ 'B': (3 / 9\) \* 100 \= 33\.333\... \-\-\> 33
	+ 'C': (2 / 9\) \* 100 \= 22\.222\... \-\-\> 22
* Returned Dictionary: {'A': 33, 'B': 33, 'C': 22}






 Additional Specifications: When you write this function, you should only
 loop once over the input string `s`, and you should not use
 built\-in string methods such as `s.count(t)` to calculate
 letter frequencies. You also should not check if a character exists
 in a string using `c in s`. However, you are allowed to
 check if a character exists as a key in a dictionary.




 Hint: Create a dictionary that maps each letter in `s`
 (case\-insensitively) to its number of occurences.
"""

import math
def integerLetterFrequencies(s):
	pass

def testIntegerLetterFrequencies():

	print('Testing integerLetterFrequencies()...', end='')    
	assert(integerLetterFrequencies('abca-bcab') == {'A': 33, 'B': 33, 'C': 22})    
	assert(integerLetterFrequencies('XyYxX') == {'X': 60, 'Y': 40})    
	assert(integerLetterFrequencies('1AaAB!') == {'A': 50, 'B': 16})    
	assert(integerLetterFrequencies('?*!#') == dict())    
	assert(integerLetterFrequencies('a') == {'A': 100})    
	assert(integerLetterFrequencies('b ') == {'B': 50})    
	assert(integerLetterFrequencies('') == dict())    
	print('Passed!')

def main():    
    testIntegerLetterFrequencies()
    
main()