# -*- coding: utf-8 -*-
"""1 - Conditionals.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c2kkqsQgo7aCqnBiQcaVr0osKfHz0Q8f

<font size="1" color="#AAA">Python Fundamentals &copy; David Kosbie</font>  

# Conditionals
A *conditional*, often called an *if statement*, allows us to run code only if some
*condition* (that is, a boolean *test*) is True.

## `if` Statements
Here is our first `if` statement:
"""

x = 5
if x == 5:
    print('yes')

"""Some important details:

  * `x == 5` is the *condition* (or *test*) of the conditional
  
  * Here, the print statement is the *body* of the conditional

  * We must include the colon (`:`) after the condition

  * We must *indent* the body (usually by 4 spaces) inside the conditional

Let's add some code after the conditional:
"""

x = 5
if x == 5:
    print('yes')
print('after')

"""Let's change `x` and try again:"""

x = 6
if x == 5:
    print('yes')
print('after')

"""Notice how the code did not print 'yes'.  Importantly:
  * The body of the conditional only runs if the condition is True!

### Body with Multiple Lines
We can include multiple lines in the body:
"""

x = 5
if x == 5:
    print('yes')
    print('definitely')
print('after')

"""Run the code above with a different value for `x`.

### Body on the Same Line
If the body has just one short line, we can place it on the same
line as the condition:
"""

x = 5
if x == 5: print('yes') # Only do this for short one-line bodies!
print('after')

"""### A Better Example
Let's write a function that uses a conditional in a more realistic way:
"""

def signString(n):
    if n > 0:
        return 'positive'
    return 'non-positive'

print(signString(5))
print(signString(-5))

"""## if-else Statements
We can add an `else` clause to our conditional. The body of the `else` clause only runs if the condition is False.
"""

def signString(n):
    if n > 0:
        return 'positive'
    else:
        return 'non-positive'

print(signString(5))
print(signString(-5))

"""Some coders prefer to return only at the end of a function.
We can add the local variable `result` to do that:
"""

def signString(n):
    if n > 0:
        result = 'positive'
    else:
        result = 'non-positive'
    return result

print(signString(5))
print(signString(-5))

"""## Nested Conditionals
We can include a conditional inside the body of another conditional.
We call this a *nested conditional*.
"""

def signString(n):
    if n > 0:
        result = 'positive'
    else:
        if n == 0:
            result = 'zero'
        else:
            result = 'negative'
    return result

print(signString(5))
print(signString(0))
print(signString(-5))

"""## if-elif-else Statements
We can include `elif` clauses (which are short for *else if*)
after the `if` and before the optional `else`.
"""



def signString(n):
    if n > 0:
        result = 'positive'
    elif n == 0:
        result = 'zero'
    else:
        result = 'negative'
    return result

print(signString(5))
print(signString(0))
print(signString(-5))

"""Note:
  * If you have an `else` clause, then exactly one body will run.
  
  * If you do not have an `else` clause, then either zero or one body will run.

## Using Multiple elifs
We can use many elifs.
"""

def getGrade(score):
    if score >= 90:
        grade = 'A'
    elif score >= 80:
        grade = 'B'
    elif score >= 70:
        grade = 'C'
    elif score >= 60:
        grade = 'D'
    else:
        grade = 'F'
    return grade

print('103 -->', getGrade(103))
print(' 88 -->', getGrade(88))
print(' 70 -->', getGrade(70))
print(' 61 -->', getGrade(61))
print(' 22 -->', getGrade(22))

"""Note:
  * The conditions are tested in order from top to bottom.
  
  * Only the body of the first condition that is True runs.
  
  * At most one body will ever run.

## if-else Expressions
An if-else *expression* has this form:
  * trueResult if condition else falseResult

This is an expression, not a statement, so for example you can print the result or assign it to a variable.
"""

x = 42
print('small' if x < 10 else 'large')
y = 'positive' if x > 0 else 'non-positive'
print(y)

"""Notes:
  * Only use if-else expressions with very simple conditions.
  
  * For complex conditions, always use if statements instead.

## Short-Circuit Evaluation
Python stops evaluating logical operators as soon as it knows
the result:
  * `(False and x)` returns False *without evaluating x*
  
  * `(True or x)` returns True *without evaluating x*

This can prevent code from crashing in some cases.
"""

print(False and (1/0 > 5)) # this does not crash!
print(True and (1/0 > 5))  # but this does crash!

print(True or (1/0 > 5)) # this does not crash!
print(False or (1/0 > 5))  # but this does crash!

"""We have not yet covered lists, but we will include the next example here so you can
see a more realistic use of short-circuit evaluation:
"""

def isEven(L, index):
    # return True if the value at L[index] is even
    # this uses short-circuit evaluation:
    return (0 <= index < len(L)) and (L[index] % 2 == 0)

L = [2, 4, 5]
print(isEven(L, 7)) # does not crash!

"""Note that you ever actually need to use short-circuit evaluation (though
coders often use it in practice).  Instead you can do this:
"""

def isEven(L, index):
    # return True if the value at L[index] is even
    # this version does not use short-circuit evaluation:
    if (0 <= index < len(L)):
        return L[index] % 2 == 0
    else:
        return False

L = [2, 4, 5]
print(isEven(L, 7)) # does not crash!

"""## Anti-Patterns for Conditionals
Here we cover some ways that you should *not* use conditionals. <br>
Examples of code patterns that you should not use are called *anti-patterns*. <br>
Novice coders often use anti-patterns.  You should avoid it!

### Using if instead of elif or else
The following code works but is not advised:
"""

# Poor style (not using if-elif-else where appropriate):

def signString(n):
    if n > 0:
        result = 'positive'
    if n == 0:
        result = 'zero'
    if n < 0:
        result = 'negative'
    return result

print(signString(5))
print(signString(0))
print(signString(-5))

"""The code above has several problems:

  1. It is unclear
    It is not obvious that the 3 conditions are exclusive -- that is, that only one
    of them will ever be True.  If instead you use an if-elif-else, that is perfectly clear.
    
  2. It is inefficient
    As written above, each of the 3 conditions is always evaluated, even if the first
    condition is True.  If instead you use an if-elif-else, once a condition evaluates to True,
    no further conditions are evaluated.

So we see that we should have used an if-elif-else like so:
"""

# Good style (using if-elif-else):

def signString(n):
    if n > 0:
        result = 'positive'
    elif n == 0:
        result = 'zero'
    else:
        result = 'negative'
    return result

print(signString(5))
print(signString(0))
print(signString(-5))

"""### Using if to return the condition
This is another common anti-pattern:
"""

def isPositive(n):
    # This is an anti-pattern (so don't do it!):
    if n > 0:
        return True
    else:
        return False

print(isPositive(5))
print(isPositive(-5))

"""This is not a huge problem, but it is wasteful, using four lines where one line works fine.
It also just makes code look a bit unprofessional.

Instead, don't use an `if` here at all, and just return the condition:
"""

def isPositive(n):
    # This avoids the anti-pattern:
    return n > 0

print(isPositive(5))
print(isPositive(-5))