# -*- coding: utf-8 -*-
"""2 - Debugging.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pCDIOxXx48syQV4d809FjXLRV9SnkXPM

<font size="1" color="#AAA">Python Fundamentals &copy; David Kosbie</font>  

# Debugging
  * Debugging is a vital skill for all coders.
  
  * Avoid complicated debugging approaches for now.  Simple debugging methods work very well, especially for new coders.

## Assertions
We can call the built-in *assert* function to
add *assertions* (or just *asserts*) to our code to help us debug.

We call assert with a *condition* that *must be True*.

  * If the condition is True, the assert *succeeds*, and *does nothing*.  The code
    just continues running.

  * If the condition is False, the assert *fails*, and *crashes (raises an exception).
  
    * This may seem bad, but it is very helpful.
    
    * A failed assertion means we have a bug. By crashing, we know we have a bug,
      and we know where to look for it.  These are very good things.
      
For example:
"""

def f(x, y):
    assert(y != 0)
    return x / y

print(f(2, 0)) # this will cause the assertion to fail

"""## Stack Traces
When Python crashes (due to an error or exception), it prints a *stack trace*.

A stack trace tells us which line of which function we are on, and the entire
*stack* of these (when a function calls another which calls another).

This is *extremely* helpful information when we debug!
"""

# This code will crash. Look closely at the stack trace for
# all the helpful information it provides.

def f(x, y):
    return x / y

def g(x):
    y = x // 2
    return f(x, y)

def h(x):
    y = g(x)
    y += g(x-1)
    y += g(x-2)
    return y

print(h(2))

"""## Print Debugging
  * The simplest debugging approach is *print debugging* -- using print statements to see
your program's state during execution.

### Step 1: Observe the failed test case
In this example, we are solving this problem:
<br><br>
Write the function longestInterval(x, y, z) that takes three ints and
returns the size of the longest interval between any two of them.
For example, consider longestInterval(5, 3, 1):

  * The interval from 5 to 3 is 2

  * The interval from 5 to 1 is 4

  * The interval from 3 to 1 is 2

Thus, the longest interval is max(2, 4, 2) which is 4.
<br><br>
Our solution has a bug (intentionally added).
  * Run the code to observe the bug.
  
  * Be sure to see which test case failed.
"""

# This is our solution, with a bug!

def longestInterval(x, y, z):
    d1 = intervalDistance(x, y)
    d2 = intervalDistance(x, z)
    d3 = intervalDistance(y, z)
    return max(d1, d2, d3)

def intervalDistance(x, y):
    # Returns the distance of the interval from x to y
    return x - y

def testLongestInterval():
    print('Testing longestInterval()...', end='')
    assert(longestInterval(5, 3, 1) == 4)
    assert(longestInterval(5, 5, 5) == 0)
    assert(longestInterval(-1, -2, -3) == 2)
    assert(longestInterval(1, 5, 9) == 8)
    print('Passed!')

def main():
    testLongestInterval()

main()

"""### Step 2: Isolate the failed test case
  * Comment out the call to main (or to your test functions)
  
  * Only include a call to the failing test case
"""

# Step 2: we isolate the failed test case

def longestInterval(x, y, z):
    d1 = intervalDistance(x, y)
    d2 = intervalDistance(x, z)
    d3 = intervalDistance(y, z)
    return max(d1, d2, d3)

def intervalDistance(x, y):
    # Returns the distance of the interval from x to y
    return x - y

def testLongestInterval():
    print('Testing longestInterval()...', end='')
    assert(longestInterval(5, 3, 1) == 4)
    assert(longestInterval(5, 5, 5) == 0)
    assert(longestInterval(-1, -2, -3) == 2)
    assert(longestInterval(1, 5, 9) == 8)
    print('Passed!')

def main():
    testLongestInterval()

#main()                               # <-- We commented out this line
assert(longestInterval(1, 5, 9) == 8) # <-- We added this line

"""### Step 3: Observe the incorrect result
  * The failed assert does not tell us what incorrect value we returned
  
  * Add a print statement to see the incorrect result
"""

# Step 3: Observe the incorrect result

def longestInterval(x, y, z):
    d1 = intervalDistance(x, y)
    d2 = intervalDistance(x, z)
    d3 = intervalDistance(y, z)
    return max(d1, d2, d3)

def intervalDistance(x, y):
    # Returns the distance of the interval from x to y
    return x - y

def testLongestInterval():
    print('Testing longestInterval()...', end='')
    assert(longestInterval(5, 3, 1) == 4)
    assert(longestInterval(5, 5, 5) == 0)
    assert(longestInterval(-1, -2, -3) == 2)
    assert(longestInterval(1, 5, 9) == 8)
    print('Passed!')

def main():
    testLongestInterval()

#main()
print(longestInterval(1, 5, 9))  # <-- We temporarily added this line
assert(longestInterval(1, 5, 9) == 8)

"""### Step 4: Add helpful print statement(s)

#### Option 1: Use a print statement
"""

# Step 4: Add helpful print statement(s)
# This version just prints the values of d1, d2, and d3

def longestInterval(x, y, z):
    d1 = intervalDistance(x, y)
    d2 = intervalDistance(x, z)
    d3 = intervalDistance(y, z)
    print(d1, d2, d3) # <-- We added this line
    return max(d1, d2, d3)

def intervalDistance(x, y):
    # Returns the distance of the interval from x to y
    return x - y

def testLongestInterval():
    print('Testing longestInterval()...', end='')
    assert(longestInterval(5, 3, 1) == 4)
    assert(longestInterval(5, 5, 5) == 0)
    assert(longestInterval(-1, -2, -3) == 2)
    assert(longestInterval(1, 5, 9) == 8)
    print('Passed!')

def main():
    testLongestInterval()

#main()
assert(longestInterval(1, 5, 9) == 8)

"""#### Option 2: Use an f-string"""

# Step 4: Add helpful print statement(s)
# This version prints d1, d2, and d3 with f-strings

def longestInterval(x, y, z):
    d1 = intervalDistance(x, y)
    d2 = intervalDistance(x, z)
    d3 = intervalDistance(y, z)
    print(f'{d1=}, {d2=}, {d3=}') # <-- We added this line
    return max(d1, d2, d3)

def intervalDistance(x, y):
    # Returns the distance of the interval from x to y
    return x - y

def testLongestInterval():
    print('Testing longestInterval()...', end='')
    assert(longestInterval(5, 3, 1) == 4)
    assert(longestInterval(5, 5, 5) == 0)
    assert(longestInterval(-1, -2, -3) == 2)
    assert(longestInterval(1, 5, 9) == 8)
    print('Passed!')

def main():
    testLongestInterval()

#main()
assert(longestInterval(1, 5, 9) == 8)

"""#### Option 3: Use locals()"""

# Step 4: Add helpful print statement(s)
# This version prints locals() to see d1, d2, and d3 (and more)

def longestInterval(x, y, z):
    d1 = intervalDistance(x, y)
    d2 = intervalDistance(x, z)
    d3 = intervalDistance(y, z)
    print(locals()) # <-- We added this line
    return max(d1, d2, d3)

def intervalDistance(x, y):
    # Returns the distance of the interval from x to y
    return x - y

def testLongestInterval():
    print('Testing longestInterval()...', end='')
    assert(longestInterval(5, 3, 1) == 4)
    assert(longestInterval(5, 5, 5) == 0)
    assert(longestInterval(-1, -2, -3) == 2)
    assert(longestInterval(1, 5, 9) == 8)
    print('Passed!')

def main():
    testLongestInterval()

#main()
assert(longestInterval(1, 5, 9) == 8)

"""### Step 5: Add test case(s) to isolate your bug
Note that this steps is only required sometimes. <br>
Here we see that the bug is probably in `intervalDistance`, so we will
add a test case for that.
"""

# Step 5: Add test case(s) to isolate your bug

def longestInterval(x, y, z):
    d1 = intervalDistance(x, y)
    d2 = intervalDistance(x, z)
    d3 = intervalDistance(y, z)
    print(locals())
    return max(d1, d2, d3)

def intervalDistance(x, y):
    # Returns the distance of the interval from x to y
    return x - y

def testLongestInterval():
    print('Testing longestInterval()...', end='')
    assert(longestInterval(5, 3, 1) == 4)
    assert(longestInterval(5, 5, 5) == 0)
    assert(longestInterval(-1, -2, -3) == 2)
    assert(longestInterval(1, 5, 9) == 8)
    print('Passed!')

def main():
    testLongestInterval()

#main()
#assert(longestInterval(1, 5, 9) == 8) # <-- We removed this line
assert(intervalDistance(1, 5) == 4)    # <-- We added this test case

"""### Step 6: Find and fix your bug"""

# Step 6: Find and fix your bug

def longestInterval(x, y, z):
    d1 = intervalDistance(x, y)
    d2 = intervalDistance(x, z)
    d3 = intervalDistance(y, z)
    print(locals())
    return max(d1, d2, d3)

def intervalDistance(x, y):
    # Returns the distance of the interval from x to y
    return abs(x - y)  # <-- We fixed the bug here (or we think we fixed it!)

def testLongestInterval():
    print('Testing longestInterval()...', end='')
    assert(longestInterval(5, 3, 1) == 4)
    assert(longestInterval(5, 5, 5) == 0)
    assert(longestInterval(-1, -2, -3) == 2)
    assert(longestInterval(1, 5, 9) == 8)
    print('Passed!')

def main():
    testLongestInterval()

#main()
assert(longestInterval(1, 5, 9) == 8)

"""### Step 7: Run all the tests again"""

# Step 7: Run all the tests again

def longestInterval(x, y, z):
    d1 = intervalDistance(x, y)
    d2 = intervalDistance(x, z)
    d3 = intervalDistance(y, z)
    print(locals())
    return max(d1, d2, d3)

def intervalDistance(x, y):
    # Returns the distance of the interval from x to y
    return abs(x - y)

def testLongestInterval():
    print('Testing longestInterval()...', end='')
    assert(longestInterval(5, 3, 1) == 4)
    assert(longestInterval(5, 5, 5) == 0)
    assert(longestInterval(-1, -2, -3) == 2)
    assert(longestInterval(1, 5, 9) == 8)
    print('Passed!')

def main():
    testLongestInterval()

main() # <-- We added this line again

"""### Step 8: Remove your extra test code"""

# Step 8: Remove your extra test code

def longestInterval(x, y, z):
    d1 = intervalDistance(x, y)
    d2 = intervalDistance(x, z)
    d3 = intervalDistance(y, z)
    return max(d1, d2, d3)

def intervalDistance(x, y):
    # Returns the distance of the interval from x to y
    return abs(x - y)

def testLongestInterval():
    print('Testing longestInterval()...', end='')
    assert(longestInterval(5, 3, 1) == 4)
    assert(longestInterval(5, 5, 5) == 0)
    assert(longestInterval(-1, -2, -3) == 2)
    assert(longestInterval(1, 5, 9) == 8)
    print('Passed!')

def main():
    testLongestInterval()

main()

"""## Using a Visualizer

* A *visualizer* lets you step through your code one step at a time
    and see each function call and the value of each variable at each step.

  * We suggest that you use
  [Python Tutor's Visualizer](https://pythontutor.com/visualize.html#mode=edit)
  with these steps:
  
    1. Paste your code into its editor.
    
    2. Select "Visualize Execution".
    
    3. Carefully step through the code's execution (or *trace*).
    
        1. Press "First" to go to the start of the trace.
        
        2. Press "Next" several times until you reach the failed test case.
        
        3. Carefully step line-by-line from there.
  
  * Try this with the first example in step 1 (with the bug) from above.
  
    * It is taking too many steps!
    
  * Try it again with the isolated failed test case from step 2 from above.

## Using a Debugger
  * A *debugger* is a powerful tool that is similar to a visualizer but more powerful.
  
  * Unfortunately, debuggers are also complex tools.
  
  * Also, there are different debuggers which work differently.
  
  * For example, Google Colab uses ipydb, and VS Code uses a visual debugger.
  
  * We suggest that you do not use a debugger for now.
  
    * Simpler debugging approaches will work well for you
      without the complexity.

## Summary
  * Print debugging works everywhere, even if you do not have access to a
    visualizer or a debugger.
    
  * Print debugging does not require knowledge about how to use specialized debugging tools.
    
  * Print debugging is a methodical process.  Follow the steps carefully.

  * Print debugging should be your go-to debugging approach for now.
"""