# -*- coding: utf-8 -*-
"""3 - Style.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g6pSlbHlXb1rNsygM7i8rxiAOYpYQOqy

<font size="1" color="#AAA">Python Fundamentals &copy; David Kosbie</font>  

# Style
Here we cover *style*, a crucial part of learning to code like a professional.

## Definition
Style is...

  * a set of guidelines to help you write cleaner, clearer, better code.
  
Style is not...

  * a rigid set of rules you must follow at all times.

Using good style will...

  * help you create fewer bugs, and help you more easily find and fix the bugs you do create.
  
Using good style will also...

  * save you huge amounts of time, since debugging is the most time-consuming part of coding.
  
  * save you huge amounts of stress, since debugging is also the most stressful part of coding.

  * help you get a job, since employers seek coders who use good style.

## Standard Style Guides

The two most popular professional style guides:

  * [PEP 8 – Style Guide for Python Code](https://peps.python.org/pep-0008/)

  * [Google Python Style Guide](https://google.github.io/styleguide/pyguide.html)

Pros:

  * Industry Standard
  
  * Amazingly Detailed
  
Cons

  * Not for Novices
  
  * Amazingly Detailed

Our Suggestion:

  * Start with some style guidelines (see below).
  
  * As you gain experience, add more style guidelines.

And this:

  * For now, try to make your code stylistically like ours.
  
And finally this:

  * Be *reasonable* about style.   Try to use it thoughtfully but not obsessively.

## Style Guidelines for New Coders
Here are a small set of Python style guidelines
that are best-suited for new coders like you.  Follow them as well as you can.

### Use Meaningful Names
Give your variables and functions clear, meaningful names. Avoid abbreviations or overly-short names, except you can use standard short names like i, j, and k for indexes and n, x, y, and so on for integers (that have no special meaning, and so cannot have any better name). In any case, well-named variables make your code much clearer.
"""

# Poor style (very unclear variable names):

di = vel * ti

# Good style (clearer variable names):

distance = velocity * elapsedTime

# Or (maybe even clearer variable names):

distanceInMiles = milesPerHour * timeInHours

"""### Use Effective Comments
Use comments but not too heavily. Add comments where they help make your code clearer. Keep your comments very brief and to-the-point.
"""

# Poor style (way too much commenting, and comments have almost no value):

def digitCount(x):   # define a function f that takes a value x
    x = abs(x)       # set x to the absolute value of itself
    result = 1       # set the variable result to 1
    while x >= 10:   # loop while x has at least 2 digits
        result += 1  # add 1 to the result
        x //= 10     # and divide x by 10
    return result    # return the result

print(digitCount(-37)) # call digitCount with an argument of -37

# Good style (a light touch of comments where they are most needed):

def digitCount(x):
    x = abs(x) # treat negatives as positives
    result = 1
    # now keep removing digits while x still has multiple digits:
    while x >= 10:
        result += 1
        x //= 10
    return result

print(digitCount(-37))

"""This was just a suggestion. You do not have to use those exact comments in
those exact places.  This just gives you an idea of where and when you might use them.

### Use Standard Formatting
Format your code cleanly, basically so it looks like our sample code. Do not exceed 80 characters per line, indent properly (4 spaces per indent), be consistent in your use of spacing around variables and operators, and generally format your code so it is easy to read.
"""

# Poor style (but this stil runs correctly!):

def digitCount(x):
 x=abs(x);result=1
 while x>=10:result+=1;x//=10
 return result
print(digitCount(-37))

# Good style (properly formatted):

def digitCount(x):
    x = abs(x)
    result = 1
    while x >= 10:
        result += 1
        x //= 10
    return result

print(digitCount(-37))

"""### Avoid Magic Numbers
Do not use *magic numbers*. These are constants in your code that hide their computation. They make your code hard to maintain and prone to bugs. To avoid magic numbers, assign them to well-named variables and then use those variables instead. Also, note that the most-frequently used integers (-1, 0, 1, 2, 10, maybe a few others) are exceptions to this rule, and can be used anywhere in your code.
"""

# Poor style (uses a magic number):

miles = 85
costOfGas = round(miles * 0.11486486, 2) # what is 0.11486486?
print(costOfGas)

# Good style (no magic number!):

miles = 85
costPerGallon = 4.25 # in USD (say)
milesPerGallon = 37
costOfGas = round(miles * costPerGallon / milesPerGallon, 2)
print(costOfGas)

# Even better style (with another well-named variable to make the math clearer):

miles = 85
costPerGallon = 4.25 # in USD (say)
milesPerGallon = 37
costPerMile = costPerGallon / milesPerGallon # <-- added this line
costOfGas = round(miles * costPerMile, 2)
print(costOfGas)

"""### Avoid Repetitive Code
Do not write repetitive code -- that is, code that has nearly-identical parts, typically with just one or two values changed over several repeated lines. Often, you can replace mostly-repetitive blocks of code with a well-chosen data structure or well-designed helper function.
"""

# Assume x is a non-negative int with at most 4 digits, this returns the largest of those digits.

# Poor style (repetitive code):

def maxOf4Digits(x):
    return max((x % 10),
               (x // 10 % 10),
               (x // 100 % 10),
               (x // 1000 % 10))

print(maxOf4Digits(5746))

# Improved but not ideal style (uses a helper function, but also still patterned code):

def maxOf4Digits(x):
    return max(getKthDigit(x, 0),
               getKthDigit(x, 1),
               getKthDigit(x, 2),
               getKthDigit(x, 3))

def getKthDigit(n, k):
    return (n // 10**k) % 10

print(maxOf4Digits(5746))

# Good style (once we learn about loops and lists):

def maxOf4Digits(x):
    digits = [getKthDigit(x, k) for k in range(4)]
    return max(digits)

def getKthDigit(n, k):
    return (n // 10**k) % 10

print(maxOf4Digits(5746))

# Another example showing a common style mistake by new coders
# This example uses loops and lists, but we include it here while we are covering good style:

# Write a function that returns the count of the most frequent digit an int n:

# Poor style (repetitive variables count0, count1, ...):

def getMostFrequentDigitCount(n):
    n = abs(n)
    if n < 10:
        return 1
    count0 = count1 = count2 = count3 = count4 = count5 = count6 = count7 = count8 = count9 = 0
    while n > 0:
        digit = n % 10
        if digit == 0:   count0 += 1
        elif digit == 1: count1 += 1
        elif digit == 2: count2 += 1
        elif digit == 3: count3 += 1
        elif digit == 4: count4 += 1
        elif digit == 5: count5 += 1
        elif digit == 6: count6 += 1
        elif digit == 7: count7 += 1
        elif digit == 8: count8 += 1
        else:            count9 += 1
        n //= 10
    return max(count0, count1, count2, count3, count4, count5, count6, count7, count8, count9)

print(getMostFrequentDigitCount(1020010))

# Good style (replace repetitive variables with a list):

def getMostFrequentDigitCount(n):
    n = abs(n)
    if n < 10:
        return 1
    counts = [0] * 10
    while n > 0:
        digit = n % 10
        counts[digit] += 1
        n //= 10
    return max(counts)

print(getMostFrequentDigitCount(1020010))

"""### Additional Guidelines
There are many more guidelines we could include.  Here are some important ones
we have already covered:

  * Use Helper Functions
  
  * Use Test Functions

  * Use Top-Down Design

  * Avoid Global Variables

  * Avoid Unneeded Code (such as print statements left over from debugging)

That's plenty for now.  Do your best to follow these closely,
without obsessing on making every last line follow every last guideline.
"""