# -*- coding: utf-8 -*-
"""5 - Worked Examples (Conditionals).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ckTZW1-Qr42xXBwTc-x03v2TcZuvrotc

<font size="1" color="#AAA">Python Fundamentals &copy; David Kosbie</font>  

# Worked Examples (Conditionals)
This notebook contains examples for you to review before you work on this section's exercises.
Watch the video solutions closely, then be sure you can reproduce the solutions
on your own!

Note: to help you focus on the materials we are currently covering,
you should resist using concepts we have not yet covered. For example,
here you should resist using
loops, strings, or lists yet (even if you
already know them well).

Reminder: many of the exercises today are a bit *mathy*.  This will change once
we cover loops and strings, but for now, let's learn how to use arithmetic
and conditionals to solve some mathy problems.  Besides, you very likely will
at times have to solve these kinds of problems on the job.

## Problem Statements
This section contains the problem statements and starter code.
Watch the accompanying video, then try to solve the problems
yourself.  If needed, you can refer to the sample solutions below.

### closestEven
Write the function closestEven(n) that takes an int or float n and returns the closest even number to n as an int. In the case of a tie, return the larger even value.
"""

import math

def closestEven(n):
    pass

def testClosestEven():
    print('Testing closestEven()...', end='')
    assert(closestEven(0) == 0)
    assert(closestEven(11) == 12)
    assert(closestEven(12) == 12)
    assert(closestEven(13) == 14)
    assert(closestEven(1.01) == 2)
    assert(closestEven(2.99) == 2)
    assert(closestEven(-11) == -10)
    assert(closestEven(-12) == -12)
    assert(closestEven(-13) == -12)
    assert(type(closestEven(1)) == int)
    assert(type(closestEven(12.0)) == int)
    print('Passed!')

def main():
    testClosestEven()

main()

"""### fractionalPart
Write the function fractionalPart(n) that takes a value n and...

  * if n is a float, the function returns the *fractional part* of n (that is,
    the part after the decimal point).  This value should be positive even
    if n is negative.
    
  * if n is an int, the function returns None (since ints do not have fractional parts).
  
  * otherwise, the function returns 'not a number'
"""

def fractionalPart(n):
    pass

def almostEqual(x, y):
    epsilon = 10**-9
    return abs(x - y) < epsilon

def testFractionalPart():
    print('Testing fractionalPart()...', end='')
    # first test non-floats:
    assert(fractionalPart(8) == None)
    assert(fractionalPart('wow') == 'not a number')

    # now test floats:
    assert(almostEqual(fractionalPart(1.234), 0.234))
    assert(almostEqual(fractionalPart(-5.67), 0.67))
    assert(almostEqual(fractionalPart(-5.000067), 0.000067))
    assert(almostEqual(fractionalPart(1.0), 0.0))
    print('Passed!')

def main():
    testFractionalPart()

main()

"""### getTravelTime
Note: sometimes problem statements are necessarily long and detailed
(like this one).
Don't be daunted.  Just read this carefully.  You can solve it!

Background: we will assume that cars travel at 60 miles per hour.
Also, all distances will be in miles.

Thus, to travel 90 miles by car requires 90 miles / 60 milesPerHour = 1.5 hours.

Next, we will assume that planes travel at 600 miles per hour.  However,
we have to add 3 hours to the travel time to account for getting to and
from the airports.

Thus, to travel 900 miles by plane requires 900 miles / 600 milesPerHour + 3 hours = 4.5 hours.

With this in mind, write the function getTravelTime(miles) that computes the
travel time both by car and by plane, and reports the faster one (with ties
going to cars), rounding times to the tenth of an hour, like so:

<pre>
getTravelTime(60) returns 'You can travel 60 miles by car in 1.0 hours!'
getTravelTime(90) returns 'You can travel 90 miles by car in 1.5 hours!'
getTravelTime(600) returns 'You can travel 600 miles by plane in 4.0 hours!'
getTravelTime(900) returns 'You can travel 900 miles by plane in 4.5 hours!'
</pre>

Note that the travel time by car or plane is the same at 200 miles,
at 3&frac13; (which rounds to 3.3), but cars win the tie, so:

<pre>
getTravelTime(200) returns 'You can travel 200 miles by car in 3.3 hours!'
getTravelTime(201) returns 'You can travel 201 miles by plane in 3.3 hours!'
</pre>

Finally, if the distance is 0 return this message:

<pre>
getTravelTime(0) returns 'You can travel 0 miles instantly!'
</pre>

And if the distance is negative, it returns a message like this:

<pre>
getTravelTime(-20) returns 'It makes no sense to travel -20 miles!'
</pre>
"""

def getTravelTime(miles):
    pass

def testGetTravelTime():
    print('Testing getTravelTime()...', end='')
    assert(getTravelTime(60) == 'You can travel 60 miles by car in 1.0 hours!')
    assert(getTravelTime(90) == 'You can travel 90 miles by car in 1.5 hours!')
    assert(getTravelTime(600) == 'You can travel 600 miles by plane in 4.0 hours!')
    assert(getTravelTime(900) == 'You can travel 900 miles by plane in 4.5 hours!')
    assert(getTravelTime(200) == 'You can travel 200 miles by car in 3.3 hours!')
    assert(getTravelTime(201) == 'You can travel 201 miles by plane in 3.3 hours!')
    assert(getTravelTime(0) == 'You can travel 0 miles instantly!')
    assert(getTravelTime(-20) == 'It makes no sense to travel -20 miles!')
    assert(getTravelTime(-100) == 'It makes no sense to travel -100 miles!')
    assert(getTravelTime(100) == 'You can travel 100 miles by car in 1.7 hours!')
    assert(getTravelTime(8200) == 'You can travel 8200 miles by plane in 16.7 hours!')
    print('Passed!')

def main():
    testGetTravelTime()

main()

"""<pre>

</pre>
<hr>

## Sample Solutions
This section contains sample solutions to these exercises.

Note that there are many good ways to solve every problem.  These are just
one way of doing so.  If you found another good approach, that's fine!

Also, these may not even exactly match the solutions in the accompanying
videos.  That's fine. Again, there are many good solutions to
most problems.

Finally, while you are strongly encouraged to review these (that's
why we are providing them to you, after all), we recommend that you
try to get to the point where you can solve the problems above without
referring to the video or these sample solutions.  You can do it!

### closestEven
Write the function closestEven(n) that takes an int or float n and returns the closest even number to n as an int. In the case of a tie, return the larger even value.
"""

import math

def closestEven(n):
    lowerInt = math.floor(n)
    higherInt = lowerInt + 1
    if lowerInt % 2 == 0:
        return lowerInt
    else:
        return higherInt

def testClosestEven():
    print('Testing closestEven()...', end='')
    assert(closestEven(0) == 0)
    assert(closestEven(11) == 12)
    assert(closestEven(12) == 12)
    assert(closestEven(13) == 14)
    assert(closestEven(1.01) == 2)
    assert(closestEven(2.99) == 2)
    assert(closestEven(-11) == -10)
    assert(closestEven(-12) == -12)
    assert(closestEven(-13) == -12)
    assert(type(closestEven(1)) == int)
    assert(type(closestEven(12.0)) == int)
    print('Passed!')

def main():
    testClosestEven()

main()

"""### fractionalPart
Write the function fractionalPart(n) that takes a value n and...

  * if n is a float, the function returns the *fractional part* of n (that is,
    the part after the decimal point).  This value should be positive even
    if n is negative.
    
  * if n is an int, the function returns None (since ints do not have fractional parts).
  
  * otherwise, the function returns 'not a number'
"""

def fractionalPart(n):
    if type(n) == float:
        n = abs(n)
        return n - int(n)
    elif type(n) == int:
        return None
    else:
        return 'not a number'

def almostEqual(x, y):
    epsilon = 10**-9
    return abs(x - y) < epsilon

def testFractionalPart():
    print('Testing fractionalPart()...', end='')
    # first test non-floats:
    assert(fractionalPart(8) == None)
    assert(fractionalPart('wow') == 'not a number')

    # now test floats:
    assert(almostEqual(fractionalPart(1.234), 0.234))
    assert(almostEqual(fractionalPart(-5.67), 0.67))
    assert(almostEqual(fractionalPart(-5.000067), 0.000067))
    assert(almostEqual(fractionalPart(1.0), 0.0))
    print('Passed!')

def main():
    testFractionalPart()

main()

"""### getTravelTime
Note: sometimes problem statements are necessarily long and detailed
(like this one).
Don't be daunted.  Just read this carefully.  You can solve it!

Background: we will assume that cars travel at 60 miles per hour.
Also, all distances will be in miles.

Thus, to travel 90 miles by car requires 90 miles / 60 milesPerHour = 1.5 hours.

Next, we will assume that planes travel at 600 miles per hour.  However,
we have to add 3 hours to the travel time to account for getting to and
from the airports.

Thus, to travel 900 miles by plane requires 900 miles / 600 milesPerHour + 3 hours = 4.5 hours.

With this in mind, write the function getTravelTime(miles) that computes the
travel time both by car and by plane, and reports the faster one (with ties
going to cars), rounding times to the tenth of an hour, like so:

<pre>
getTravelTime(60) returns 'You can travel 60 miles by car in 1.0 hours!'
getTravelTime(90) returns 'You can travel 90 miles by car in 1.5 hours!'
getTravelTime(600) returns 'You can travel 600 miles by plane in 4.0 hours!'
getTravelTime(900) returns 'You can travel 900 miles by plane in 4.5 hours!'
</pre>

Note that the travel time by car or plane is the same at 200 miles,
at 3&frac13; (which rounds to 3.3), but cars win the tie, so:

<pre>
getTravelTime(200) returns 'You can travel 200 miles by car in 3.3 hours!'
getTravelTime(201) returns 'You can travel 201 miles by plane in 3.3 hours!'
</pre>

Finally, if the distance is 0 return this message:

<pre>
getTravelTime(0) returns 'You can travel 0 miles instantly!'
</pre>

And if the distance is negative, it returns a message like this:

<pre>
getTravelTime(-20) returns 'It makes no sense to travel -20 miles!'
</pre>
"""

def getTravelTime(miles):
    if miles == 0:
        return 'You can travel 0 miles instantly!'
    elif miles < 0:
        return f'It makes no sense to travel {miles} miles!'
    else:
        # distance = velocity * time, so time = distance / velocity
        carVelocity = 60 # in miles/hour (mph)
        carTime = miles / carVelocity # in hours

        planeVelocity = 600 # mph
        planeTime = miles / planeVelocity + 3 # 3 hours getting to/from airports

        if planeTime < carTime:
            means = 'plane'
            hours = planeTime
        else:
            means = 'car'
            hours = carTime

        hours = round(hours, 1)
        return f'You can travel {miles} miles by {means} in {hours} hours!'

def testGetTravelTime():
    print('Testing getTravelTime()...', end='')
    assert(getTravelTime(60) == 'You can travel 60 miles by car in 1.0 hours!')
    assert(getTravelTime(90) == 'You can travel 90 miles by car in 1.5 hours!')
    assert(getTravelTime(600) == 'You can travel 600 miles by plane in 4.0 hours!')
    assert(getTravelTime(900) == 'You can travel 900 miles by plane in 4.5 hours!')
    assert(getTravelTime(200) == 'You can travel 200 miles by car in 3.3 hours!')
    assert(getTravelTime(201) == 'You can travel 201 miles by plane in 3.3 hours!')
    assert(getTravelTime(0) == 'You can travel 0 miles instantly!')
    assert(getTravelTime(-20) == 'It makes no sense to travel -20 miles!')
    assert(getTravelTime(-100) == 'It makes no sense to travel -100 miles!')
    assert(getTravelTime(100) == 'You can travel 100 miles by car in 1.7 hours!')
    assert(getTravelTime(8200) == 'You can travel 8200 miles by plane in 16.7 hours!')
    print('Passed!')

def main():
    testGetTravelTime()

main()