# -*- coding: utf-8 -*-
"""6 - Additional Topics (Conditionals).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vz28ytSRUkh2PtnAfdtjPZ2y8E-DyLsm

<font size="1" color="#AAA">Python Fundamentals &copy; David Kosbie</font>  

# Additional Topics (Conditionals and Problem-Solving)
Here are some additional topics that are not part of the core curriculum.
However, they are likely to be useful to you in your coding future.
If you are new to Python, you can skip these topics for now and
return later.  For those of you with some Python experience,
you may find some useful concepts here that are new to you.

## bool()
The bool() function converts any value to a Boolean (True or False).

### Zero and Zero-Sized Values
Zero and zero-sized values (like empty strings, empty lists, etc) are
converted to False.
"""

# These all convert to False:
print(bool(0))
print(bool(0.0))
print(bool(''))   # empty string
print(bool([]))   # empty list
print(bool({}))   # empty dict
print(bool(None)) # even None

"""### Non-Zero and Non-Zero-Sized Values
Other values besides zero and zero-sized values are
converted to True.
"""

# These all convert to True:
print(bool(1))       # non-zero int
print(bool(-1))      # non-zero negative int
print(bool(3.14))    # non-zero float
print(bool('yes'))   # non-empty string
print(bool([1]))     # non-empty list
print(bool({1:2}))   # non-empty dict

"""## Truthy and Falsy Values
Any value v is *truthy* if bool(v) returns True.<br>

Any value v is *falsy* if bool(v) returns False.<br>

The key: Python treats truthy values as True and falsy values as False.
"""

# examples of truthy and falsy values:
if (0):   print('yes for 0!')
if (1):   print('yes for 1')
if (''):  print('yes for empty string')
if ('x'): print('yes for non-empty string')

"""## Truthy and Falsy Values with `and` and `or`
`and` and `or` work in surprising ways with truthy and falsy values.

  * `and` returns the first False or falsy value it finds, or the last value otherwise.
  
  * `or` returns the first True or truthy value it finds, or the *first* value otherwise.

See if you can use these rules to predict what the following prints:
"""

# Many experienced coders will not correctly predict what these lines print:
print('maybe' and 42)
print('maybe' or 42)
print('yes' and None and 0.0 and 42)
print('yes' or None or 0.0 or 42)

"""## Avoid Truthy and Falsy Values
As we just saw, it can be hard to predict precisely how Python evaluates
logical expressions using truthy and falsy values.

For this reason: *avoid using truthy and falsy values*.

Instead, in boolean expressions, use explicit tests based on the object's type.
For example:

  * For an int x, use (x != 0).
  
  * For a string s, use (s != ''), or if you prefer, use (len(s) > 0).
"""

# For example, instead of this:

def endsInZero(x):
    return not (x % 10) # This relies on 0 being falsy (avoid!)

print(endsInZero(10))
print(endsInZero(21))
print()

# Do this:

def endsInZero(x):
    return (x % 10) == 0 # This does not rely on 0 being falsy (better!)

print(endsInZero(10))
print(endsInZero(21))

# This example uses strings, which we have not covered yet, but
# it is a commonly-seen anti-pattern that you should avoid:

# Instead of this:

def getGreeting(name):
    name = name or 'Anonymous' # This relies on '' being falsy and also on
                               # `or` returning the first truthy value (avoid!)
    return f'Hello, {name}'

print(getGreeting('Fred'))
print(getGreeting(''))
print()

# Do this:

def getGreeting(name):
    if name == '':  # This does not rely on '' being falsy, nor on
                    # `or` returning the first truthy value (better!)
        name = 'Anonymous'
    return f'Hello, {name}'

print(getGreeting('Fred'))
print(getGreeting(''))

"""## Boolean Arithmetic
In arithmetic expressions:

  * Python treats False as 0
  
  * Python treats True as 1
  
This is called *boolean arithmetic*.
"""

print(False + 3)
print(True + 3)

"""## Avoid Boolean Arithmetic
As with truthy and falsy values, you should avoid using boolean arithmetic.
"""

# Instead of this:

def sign(n):
    # Return 1 for positive n, 0 for 0, -1 for negative n
    # This version works but is just awful...
    return (n > 0) - (n < 0)

print(sign(5))
print(sign(0))
print(sign(-5))
print()

# Do this:

def sign(n):
    # Return 1 for positive n, 0 for 0, -1 for negative n
    # This version is much clearer
    if n > 0:
        return 1
    elif n == 0:
        return 0
    else:
        return -1

print(sign(5))
print(sign(0))
print(sign(-5))

"""## Truth Tables
A *truth table* for a boolean expression lists all the possible combinations
of truth values of its operands, one per row, along with that expression's
result for those values.

For example:
<pre>
    x      y    (x and y)
  False  False    False
  False  True     False
  True   False    False
  True   True     True
</pre>

We can also write 0 for False and 1 for True, like so:
<pre>
    x  y  (x and y)
    0  0     0
    0  1     0
    1  0     0
    1  1     1
</pre>

For those who know about binary numbers, note that the rows are generally written in
sorted order when we view the arguments as a single binary number.
So in the table above, they are ordered 00, 01, 10, 11.

### Using Helper Columns
For more complex expressions, we can use *helper columns* for the
sub-expressions.  This can make the table easier to make.

For example:
<pre>
    x  y  (x or y)  (x and y)  (not (x and y))  ((x or y) and not (x and y))
    0  0     0          0            1                     0
    0  1     1          0            1                     1
    1  0     1          0            1                     1
    1  1     1          1            0                     0
</pre>

### Equivalent Expressions
Two boolean expressions are *equivalent* if their truth tables
match for every row.

For example:
<pre>
    x  y  ((x or y) and not (x and y))  ((x and not y) or (y and not x))
    0  0              0                                0
    0  1              1                                1
    1  0              1                                1
    1  1              0                                0
</pre>

This shows that these two expressions are *equivalent*:

  * ((x or y) and not (x and y))
  
  * ((x and not y) or (y and not x))
  
In fact, both of these compute *xor*, where exactly one value is True
and the other is False.
"""

# We can demonstrate the equivalence from above in code like so:

def f(x, y):
    return ((x or y) and not (x and y))

def g(x, y):
    return ((x and not y) or (y and not x))

def printRow(x, y):
    # Using :2 converts to an int in a field of width 2
    print(f'{x:2}{y:2}{f(x, y):2}{g(x, y):2}')

print(' x y f g')
printRow(False, False)
printRow(False, True)
printRow(True,  False)
printRow(True,  True)
print()

# We can also confirm equivalence with asserts:
print('Testing that f is equivalent to g...', end='')
assert(f(False, False) == g(False, False))
assert(f(False, True ) == g(False, True ))
assert(f(True,  False) == g(True,  False))
assert(f(True,  True ) == g(True,  True ))
print('Passed!')

"""## De Morgan's Laws

*De Morgan's Laws* state that:

  * (not (A or B)) is equivalent to ((not A) and (not B))

and

  * (not (A and B)) is equivalent to ((not A) or (not B))

### Proving De Morgan's Laws

We can *prove* De Morgan's Laws are true using truth tables. We do so below for the first rule.

Rule 1: (not (A or B)) is equivalent to ((not A) and (not B))

We write the truth tables for each expression, like so:

<pre>
A  B  (A or B)  (not (A or B))
0  0     0            1
0  1     1            0
1  0     1            0
1  1     1            0
</pre>

And:

<pre>
A  B  (not A)  (not B)  ((not A) and (not B))
0  0     1        1                1
0  1     1        0                0
1  0     0        1                0
1  1     0        0                0
</pre>

Since the last column of the two tables matches exactly, we have shown
that the two expressions are equivalent. The same can be done for the other rule.

### Using De Morgan's Laws
We can sometimes use De Morgan's Laws to simplify expressions.
For example, say that we had this expression in our code:

  * (not ((hour > 12) or (day == 'Monday')))

If A is (hour > 12) and B is (day == 'Monday'),
then the expression can be re-written as: (not (A or B)).

Using De Morgan's Laws, we can replace this with the equivalent expression: (not A) and (not B) So, our expression becomes:

  * (not (hour > 12)) and (not (day == 'Monday'))

We can go further by replacing:

  * (not (hour > 12)) with (hour <= 12)

and

  *  (not (day == 'Monday')) with (day != 'Monday')

Our entire expression thus simplifies to:

  * (hour <= 12) and (day != 'Monday')

This is a simpler expression than to the original, and it clearly conveys
the intended condition - that is, it is morning (hour <= 12) on any day but Monday.
"""