# -*- coding: utf-8 -*-
"""Level 3 bowlingScore.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H-arhe6zeETaKVEJuAv5E04a3DvvSKCW

Background: When you are bowling, you get 10 frames. In each frame
 you get 2 throws, where you try to knock down the 10 pins. Your score
 for that frame is the total number of pins you knocked down in those 2
 throws. So if you knock down 3 pins on your first throw, and then 6 more
 on the second throw, your score in that frame is 3\+6, or 9\. Your total
 score is the sum of your score in each frame.




 There are some special cases to consider:
 1. If you knock down less than 10 pins on your first throw, but then
 you knock down the rest of the pins on your second throw, this is called
 a "spare". When you get a spare, your score in that frame also includes
 your next throw (in the next frame). So if you knock down 3 on your first
 throw, and 7 on your second throw, that is a spare. So you score 10 plus
 your next throw. Say your next throw is a 5 (in the next frame). Then your
 score for the spare is 15\. Remember, this throw is counted twice, as it
 forms part of the score for its frame and the previous frame (the one with the spare).
2. If you knock down all 10 pins on your first throw in a frame,
 that is called a "strike". In that case, the frame ends. Also,
 the score for the strike includes the next 2 throws. So if you get a strike,
 then in the next frame you get 3 on your first throw and 5 on your second
 throw, then the score for the strike is 10\+3\+5, or 18\. As another example,
 if you get a strike, followed by another strike, followed
 by a 3, then the score for the first strike is 10\+10\+3, or 23\.
3. If you get a spare in the last frame (the 10th frame), you get one
 more throw, and your score for that last spare includes that last throw.
 However, there is no 11th frame, even though you got that last throw.
4. Similarly, if you get a strike in the last frame, you get two
 more throws, which count towards the 10th frame. Again, though,
 there is no 11th frame, even though you got both of those last throws.






 So we see that the best possible score is if you get a strike in every
 frame, and then in the last frame you get two extra throws and both of
 those are strikes, too. In that case, your score is 30 in all 10
 frames, so your total score is 300\.




 With this in mind, write the function `bowlingScore(scores)`
 which takes a list of the scores on each throw, and returns the total
 score for that game.




 Remember that when you score a 10, that frame only has 1 throw, except the
 last frame, as described above.
"""

import copy

def bowlingScore(scores):
    scores = copy.deepcopy(scores)

    total_score = 0
    frame = 1
    i = 0

    while frame <= 10:
        if scores[i] == 10:  # Strike
            total_score += 10 + scores[i + 1] + scores[i + 2]
            i += 1
        elif scores[i] + scores[i + 1] == 10:  # Spare
            total_score += 10 + scores[i + 2]
            i += 2
        else:  # Open frame
            total_score += scores[i] + scores[i + 1]
            i += 2
        frame += 1

    return total_score

def testBowlingScore():
    print('Testing bowlingScore()...', end='')
    assert(bowlingScore([10]*12)==300)
    assert(bowlingScore([7,2,8,2,10,7,1,8,2,7,3,10,10,5,4,8,2,7])==162)
    assert(bowlingScore([2,6,2,6,9,1,10,10,10,5,1,4,5,9,0,8,1])==140)
    assert(bowlingScore([6,4,2,7,8,1,2,4,6,3,10,6,2,1,9,6,4,10,10,10])==137)
    assert(bowlingScore([8,1,5,3,4,3,0,8,9,0,8,1,3,6,1,8,5,4,7,1])==85)

    # Finally, verify that the function is non-mutating
    L = [7,2,8,2,10,7,1,8,2,7,3,10,10,5,4,8,2,7]
    bowlingScore(L)
    assert(L == [7,2,8,2,10,7,1,8,2,7,3,10,10,5,4,8,2,7])
    print('Passed!')

def main():
    testBowlingScore()

main()