# -*- coding: utf-8 -*-
"""0 - Python Resources.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GwpPPB-2AYXnYaYJLpSNYs5Po3qiprkb

<font size="1" color="#AAA">Python Fundamentals &copy; David Kosbie</font>  

# Python Resources
There are countless free online Python resources for you,
some better than others. Here is a short list of some of the best
that you might try first.

First note that you do not need any of these for this bootcamp.
All the required material is included in the lecture notes, and covered in detail
in the accompanying lecture videos.

We provide these as an additional resource in case they prove helpful.

<hr>

<ul>
    <li><a href="https://allendowney.github.io/ThinkPython/">Think Python</a>, by Allen Downey.</li>
    <br><li><a href="https://books.trinket.io/pfe/index.html">Python for Everybody</a>, by Charles Severance.</li>
    <br><li><a href="https://automatetheboringstuff.com/">Automate the Boring Stuff with Python</a>, by Al Sweigart.</li>
    <br><li><a href="https://pythonbooks.org/free-books/">pythonbooks</a>, a well-curated list of other free online Python books.</li>
    <br><li>The Official Python Documentation (version 3.12):
        <ul>
            <br><li><a href="https://docs.python.org/3/">Python Documentation Home</a>
                <ul>
                    <li><a href="https://docs.python.org/3/tutorial/index.html">The Python Tutorial</a></li>
                    <li><a href="https://docs.python.org/3/library/index.html">The Python Standard Library</a></li>
                    <li><a href="https://docs.python.org/3/py-modindex.html">The Python Module Index</a></li>
                    <li><a href="https://docs.python.org/3/reference/index.html">The Python Language Reference</a></li>
                </ul>
            </li>
            <br><li><a href="https://pypi.org/">The Python Package Index (pypi)</a>
        </ul>
    </li>
</ul>

<hr>

We will provide some additional resources on Data Analsysis in Python
on Day 10 we reach that topic.
"""