# -*- coding: utf-8 -*-
"""1 - Foundations.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iX6a8ff7iw84CC7FHWoObSvaxx9xM7V6

<font size="1" color="#AAA">Python Fundamentals &copy; David Kosbie</font>  

# Foundations
We begin with some key concepts we need to start writing Python code.
There is a lot of vocabulary here,
but it is all required to understand how to write code well.
Soon these terms and concepts will be second nature to you.

## Printing Values
`42` is a *value*.  We call the `print` function to display values.
"""

print(42)

"""We can call `print` repeatedly, and we can print multiple values on each call."""

print(1)
print(2, 3)

"""## Comments
Code following a hash mark (#) is a *comment*.  Comments help
make code clearer.  Python ignores comments.
"""

print(42) # This is a comment!

"""## Data Types
Values are also called *data*.
Each value has a *type*.
We call the `type` function to get the type of a value.

### Ints
A number without a decimal point is an *integer* (or an *int*).
"""

print(type(42)) # This prints <class 'int'>, because 42 is an int

"""### Floats
A number with a decimal point is a *floating-point number* (or a *float*).
"""

print(type(4.2))

"""Note that `4.` is not the same as `4`."""

print(type(4))   # int
print(type(4.))  # float
print(type(4.0)) # float

"""### Strings
Values in quotes are *strings*.
"""

print('Hello world!') # this prints the string 'Hello world!'

"""
We can use single-quotes or double-quotes."""

print('Amazing') # uses single-quotes
print("Awesome") # uses double-quotes

"""Note that `'4'` is not the same as `4`."""

print(type('4')) # string
print(type(4))   # int

"""### Booleans
The values `True` and `False` are *booleans* (or *bools*).
"""

print(type(True))
print(type(False))

"""### None
The value `None` is a special value.  It has its own type.
"""

print(type(None)) # None has type NoneType

"""## Variables
A *variable* is a named memory location that *refers* to a value.

### Assigning Variables
We can *assign* a value to a variable.
This is the same as *setting* the variable to that value.
"""

x = 42   # This sets the variable x to the value 42.
         # Equivalently, it assigns the value 42 to x.
print(x) # And this prints the value x is set to (that is, 42)

"""### Reassigning Variables
We can *reassign* or *change* the value of a variable.  Unlike in some languages (like Java or C), in Python we can even reassign a variable to a new type of value.
"""

x = 42        # This sets x to the int 42
print(x)
x = 1.23      # This reassigns x to the float 1.23
print(x)
x = 'amazing' # This reassigns x to the string 'amazing'
print(x)

"""### Naming Variables
We can give variables any name, so long as it starts with a letter and
only contains letters, digits, or underscores.
"""

name = 'fred'
age = 37

"""#### camelCase and snake_case
For multi-word names, we can either use *camelCase* (where we capitalize the first letter of each word after the first word) or *snake_case* (where we separate words with underscores).  Both conventions are used at times, so be comfortable with either, but try to be consistent in your own code.
"""

numberOfCats = 3    # This uses CamelCase
number_of_dogs = 2  # This uses snake_case

"""## F-Strings
We can use *f-strings* to *format* strings nicely.
  * f-strings include an f before the string.
  * The f is not part of the string (it just makes it an f-string).
  * In f-strings, values in braces are evaluated.
"""

x = 42
y = 31
print(f'{x} plus {y} equals {x + y}')

"""## Statements
A *statement* is an instruction or command to Python.  For now, a statement corresponds to a single line of code.  Soon, we will learn about *compound statements* like `if` and `while` that use multiple lines of code.
"""

x = 42   # This line is an assignment statement
print(x) # This line is a print statement

"""## Expressions
An *expression* is Python code that evaluates to a value.  Anything that can go on the right-hand side of an assignment statement is an expression.  Expressions generally occur within statements.
"""

w = 42                  # 42 is an expression
x = w                   # w is an expression
y = x + 10              # x + 10 is an expression
z = (32 + x) / (y - 30) # (32 + x) / (y - 30) is an expression
print(z - 2)            # z - 2 is an expression

"""## Operators
An *operator* is a symbol (or several symbols) or keyword that performs
a specific operation on values (called *operands*),
evaluating to a *result*.  Operators generally occur within expressions.
"""

x = 12 + 34  # + is the addition operator
             # 12 and 34 are operands
             # 46 is the result
y = x * 10   # * is the multiplication operator
             # 46 and 10 are the operands
             # 460 is the result
print(y)

"""### Types Affect Semantics
The meaning (or *semantics*) of an operator can depend on the types of its arguments.
For example, `*` performs multiplication over numbers, but if one of the arguments is a string, then it *concatenates* the string repeatedly.
"""

print(123 * 10)    # 1230
print('abc' * 10)  # abcabcabcabcabcabcabcabcabcabc (10 'abc' strings together)

"""## Functions
Python organizes code into *functions*, which are blocks of code that
take some *input* (called *arguments*), perform some task,
and return an *output* (called the *result*).  Python includes many
useful *built-in functions* such as `min` and `max`
(among many others).

### Calling Functions
We call a function by placing its *arguments* in parentheses after the function name.
The function takes those arguments, performs its task, and returns the result, which we can then use like any other value.
"""

larger = max(15, 27) # This calls the built-in function max.
                     # 15 and 27 are arguments.
                     # The function takes those arguments,
                     # and returns its result (27 in this case).
print(larger)

"""### Writing Functions
Writing Python code generally involves writing our own functions.
We use `def` to define a new function.  After we define the function,
then we can call it just like built-in functions.
"""

# This defines the new function sumOfSquares:
def sumOfSquares(x, y):
    return x*x + y*y

# Now we can call sumOfSquares like any other function:
x = sumOfSquares(2, 3) # Sets x to 13 (2**2 + 3**3)
print(x)

"""## Modules
A *module* is a file (or set of files) that contains functions
or constants grouped by some purpose.
For example, the `math` module includes helpful math functions like
`factorial`, and constants like `pi`.
To use a module, you must first import it.
"""

import math
print(math.factorial(4)) # prints 24 (4*3*2*1)
print(math.pi)           # prints 3.141592653589793

"""We can also import specific functions or constants from a module.
If we do it this way, then we do not need to include the module name
when we use them.
"""

from math import factorial, pi
print(factorial(4)) # See how we do not need math. here
print(pi)           # or here

"""## Console Input
We can call the `input` function to get input from the user.
"""

name = input('Enter your name: ')
print(f'Hi {name}!')

"""The function `input` always returns a string.  If want to input an int,
we need to use the `int` function to convert that string to an int.
"""

# first try (fails):
x = input('Enter a number: ')
print(f'{x}*10 equals {x*10}')

# second try using int:
x = int(input('Enter a number: '))
print(f'{x}*10 equals {x*10}')

"""## Errors
There are 3 major kinds of errors we will experience:
  * Syntax Errors
  * Runtime Errors
  * Logical Errors

### Syntax Errors
A *syntax error* occurs when our code does not follow the *grammar*
(or rules for how to structure code) for Python.
"""

# This code has a syntax error: it is missing the right-parenthesis
print('This will not work!

"""Run the code above and see how Python reports the syntax error to us.
The report is a bit complicated, but it includes lots of important information.
It tells us the line where the error occurred, and (in complicated language)
what the error was.  Be sure to read these error reports carefully and
try to understand them before fixing them.

### Runtime Errors
A *runtime error* (also called a *crash*, which is a kind of *bug*)
occurs when your code has correct syntax and starts running,
but then it performs some illegal operation, such as dividing by 0.
"""

x = 1 / 0  # This generates a run-time error

"""As with syntax errors, Python gives us a detailed and very useful error report for runtime errors.  Read it carefully!

### Logical Errors
A *logical error* (also called a *bug*) occurs when your program has correct syntax and runs without crashing (so, without a runtime error), only it produces an incorrect result.
"""

print('5 squared is 23')  # this is a logical error

"""Run the code above.  See how it does not have a syntax error or a runtime error.  It ran just fine.  However, it says that 5 squared is 23, which is wrong.  The code has a logical error.
Python usually does not catch logical errors.  We do not get an error report.
We have to find and fix these errors on our own.  This makes logical errors the
hardest kind of errors to deal with.

## Testing and Debugging
Literally everyone who writes code will create some bugs.  It is a natural part of the coding process.  Of course, we want to create as few bugs as possible, and then to find and fix them before we trust our code.  To do that, we use two techniques:
  * Testing  
    Testing involves *finding* bugs.
    Any time we write code,
    we first *test* that code to verify that it works properly.
    We will soon discuss *test functions*, which is the main approach
    we will use for testing.
    
  * Debugging  
    If our tests find a bug, we then have to *fix* the bug.  This is called
    *debugging*.

We will soon learn more about testing and debugging.  For now, just know that
these are absolutely essential steps that you (and everyone) must master to be
a competent programmer.
"""