# -*- coding: utf-8 -*-
"""2 - Operators and Expressions.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AU-s68w2uHqtp1CF9qrDaUa4I4OdHcx2

<font size="1" color="#AAA">Python Fundamentals &copy; David Kosbie</font>  

# Operators and Expressions

## Arithmetic Operators
The *Arithmetic Operators* perform basic arithmetic on numbers.

### Addition, Subtraction, and Multiplication
We start with addition operator (`+`),
subtraction operator (`-`), and
multiplication operator (`*`).
"""

print(9 + 3)
print(9 - 3)
print(9 * 3)

"""For these operators, the result is an int only if both operands are ints.
If either operand is a float, then the result is a float.
"""

print(9 + 3)
print(9 + 3.0)

print(9 - 3)
print(9.0 - 3)

print(9 * 3)
print(9 * 3.0)

"""### Division
Python has two division operators: `/` and `//`.

#### The Division Operator
`/` is the *division operator*.  Unlike addition, subtraction, and multiplication,
the `/` operator always results in floats, even if both operands are ints.
"""

print(9 / 3) # surprising?
print(3 / 9)

"""#### The Floor Division Operator
`//` is the *floor division operator* (sometimes just called "div").
If both operands are ints, the result will also be an int.
"""

print(9 // 3)
print(9 // 3.0)

"""`//` is called the floor division operator because it converts its result
to an integer using the *floor* operation.  This means that it results in
the largest integer that is no larger than the result.

For example, (18 / 5) is 3.6.  The largest integer no larger than 3.6 is 3.
Thus, (18 // 5) is 3, as we see:
"""

print(18 / 6)
print(18 // 6)

print(18 / 5)
print(18 // 5)

"""For positive results, floor division is the same as truncation (that is, where we
just ignore the decimal part of the result).

For negative results, floor division is not the same as truncation!

"""

print(-18 / 5)
print(-18 // 5)

"""#### Division by Zero
If you divide by zero, Python raises a ZeroDivisionError.
"""

print(5 / 0) # error!

"""### Exponentiation
`**` is the *exponentiation operator*.  `(x ** y)` results in x<sup>y</sup>.
If both operands are ints, the result is an int.
"""

print(2 ** 3)
print(2 ** 3.0)

"""We can find the square root of a number using `**`:"""

print(9 ** (1/2))

"""Note that Python can handle very large numbers:"""

print(123 ** 45)

"""### Remainder
`%` is the *remainder operator* (also called the *modulo operator*, or
just the *mod operator*).  `(x % y)` results in the remainder when we divide
x by y.
"""

print(21 % 5)
print(20 % 5)
print(19 % 5)

"""These special cases for `(x % y)` can be confusing:

"""

print(5 % 5)
print(4 % 5)
print(0 % 5)
print(-1 % 5)

"""While `(0 % x)` is 0, note that `(x % 0)` raises a ZeroDivisionError."""

print(0 % 5)
print(5 % 0)

"""## Assignment Operators
The *assignment operators* are a shorthand that let us
perform an arithmetic operation on x and then set x to the result.
For example, `+=` is an assignment operator where
 `(x += 5)` is the same as `(x = x + 5)`:
"""

x = 10
x += 5
print(x)

"""Each arithmetic operator has a corresponding assignment operator."""

x = 10
x += 5
print(f'Using += results in {x}')

x = 10
x -= 5
print(f'Using -= results in {x}')

x = 10
x *= 5
print(f'Using *= results in {x}')

x = 10
x /= 5
print(f'Using /= results in {x}')

x = 10
x //= 5
print(f'Using //= results in {x}')

x = 10
x %= 5
print(f'Using %= results in {x}')

x = 10
x **= 5
print(f'Using **= results in {x}')

"""## Relational Operators
The relational operators compare two values for equality,
inequality, or relative order.
These result in boolean values (True or False).

### Equality and Inequality Operators
`==` tests for equality, and `!=` tests for inequality.
"""

print(5 == 6)
print(5 != 6)

print(6 == 6)
print(6 != 6)

"""#### `=` vs `==`
Be sure to understand the difference between these operators.
  * `x = 5` assigns the value 5 to the variable x.
  
  * `x == 5` compares x and 5 and returns True if they are equal and False otherwise.

### Ordering Operators
These operators test the relative order of their operands:
`<`, `<=`, `>=`, `>`.
"""

print(5 < 6)
print(5 <= 6)

print(6 < 6)
print(6 <= 6)

print(6 > 5)
print(6 >= 5)

print(5 > 5)
print(5 >= 5)

"""## Logical Operators
The 3 *logical operators* are `and`, `or`, and `not`:

  * `(x and y)` is True if both x is True and y is True.
  
  * `(x or y)` is True if either x is True or y is True (or both).
  
  * `(not x)` is True if x is False.
"""

print(True and False)
print(True and True)

print(True or False)
print(False or False)

print(not True)
print(not False)

x = 42
print((x > 20) and (x < 40))
print((x > 20) or (x < 40))

"""## Operator Order
Operators are evaluated in the conventional order:

  1. Parentheses

  2. Exponentiation

  3. Multiplication, Division, and Remainder

  4. Addition, Subtraction
"""

print(1 + 2 ** 3 * (4 + 5))

"""Operator order can lead to confusing bugs.  For example, `(x ** 1/2)`
looks like it computes the square root of x, but it does not (why not?).

When in doubt, add parentheses to keep the order of operations clear.
"""

print(9 ** 1/2)
print(9 ** (1/2))

"""## Parallel and Chained Operators

### Parallel Assignment
We can assign multiple values to multiple variables at once using *parallel assignment*
(also known as *tuple assignment*).
"""

# instead of this:
# x = 5
# y = 10
# we can do this:
x, y = 5, 10 # parallel assignment
print(x, y)

"""In parallel assignment, all the values on the right-hand side are evaluated first,
and only then are variables on the left-hand side changed.  For example:
"""

x = 5
x, y = x+1, x+2 # both values on the right are evaluated before
                # either variable on the left is set
print(x, y)

"""### Parallel Swap
Using parallel assignment, we can swap two variables on one line without
using a temp variable.

Here is a traditional swap using a temp variable:
"""

x = 5
y = 10

# swap x and y using a temp variable:
temp = x
x = y
y = temp

print(x, y)

"""With *parallel swap*, we can do the same thing in one line, and without a temp variable:"""

x = 5
y = 10

# swap x and y using parallel swap:
x, y = y, x

print(x, y)

"""### Chained Assignment
We can assign the same value to multiple variables at once using *chained assignment*. <br>
So instead of this:
"""

x = 5
y = 5

print(x, y)

"""we can do this:"""

x = y = 5 # chained assignemnt
print(x, y)

"""### Chained Comparisons
We can sometimes combine two comparisons into one using *chained comparisons*. <br>
So instead of this:
"""

x = 5
print((0 < x) and (x < 10))

"""we can do this:"""

x = 5
print(0 < x < 10) # chained comparisons

"""## Floats Are Approximate
While ints are always exact, sometimes floats are only approximate.
"""

print(0.1 + 0.1)
print(0.1 + 0.2) # surprised?

"""### Do not use `==` with Floats
Because floats are approximate, `==` can sometimes fail to work
as expected with floats.
"""

print(0.1 + 0.1 == 0.2)
print(0.1 + 0.2 == 0.3) # surprised?

"""### Do not use `math.isclose` with Floats
Python has a built-in function (`math.isclose`) that is supposed to
test if two floats are equal (or very nearly equal).  It seems to
work well:
"""

import math
print(math.isclose(0.1 + 0.2, 0.3))

"""However, `math.isclose` fails for values near zero!"""

import math
print(math.isclose(0.1 + 0.2 - 0.3, 0)) # surprised?

"""Lesson: **do not use `math.isclose`!**

### Use `almostEqual` with Floats
Instead of `==` or `math.isclose`,
use the `almostEqual` function (which is not built-in to Python)
to compare floats.
"""

# You have to define this function yourself before you can use it:
def almostEqual(x, y):
    epsilon = 10**-9
    return abs(x - y) < epsilon

# But now we can safely compare floats for equality (or near-equality):
print(almostEqual(0.1 + 0.1, 0.2))
print(almostEqual(0.1 + 0.2, 0.3)) # better!

"""Let's confirm that `almostEqual` works near 0 (unlike `math.isclose`):"""

def almostEqual(x, y):
    epsilon = 10**-9
    return abs(x - y) < epsilon

print(almostEqual(0.1 + 0.2 - 0.3, 0)) # success!

"""## Multiline Expressions
We cannot include newlines in Python expressions.  So this fails:
"""

# This produces a syntax error:
x = 1234567890123456789012345678901234567890 +
    9876543210987654321098765432109876543210

print(x)

"""Instead, we can wrap the expression in parentheses.  Then we can
use newlines:
"""

# This works but is not pretty:
x = (1234567890123456789012345678901234567890 +
9876543210987654321098765432109876543210)

print(x)

"""To make your code more readable, if you use multiline expressions,
indent each line so they line up inside the parentheses, like this:
"""

# This works and is properly indented:
x = (1234567890123456789012345678901234567890 +
     9876543210987654321098765432109876543210)

print(x)