# -*- coding: utf-8 -*-
"""3 - Functions.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wA3dcZzNTe3aR1M1Cuj8mREY9BHOybGR

<font size="1" color="#AAA">Python Fundamentals &copy; David Kosbie</font>  

# Functions

## Some Built-In Functions
Here we cover some useful functions that are built-in to Python.
There are many others, but these are enough for you to get started.

### `print`
We have already seen that we can use `print` to print values to
the console (or terminal):
"""

print(1+12)

"""If we provide multiple arguments, each is printed on the same line.
Note that they are not comma-separated.
"""

print(1, 2)

"""Each print ends with a newline.  We can use `end=''` to stay on the same line."""

print(1)
print(2)

print(3, end='') # this stays on the same line
print(4)

"""### Type Conversion Functions
The `int` function *converts* values to ints:
"""

print(int(2.3))  # convert the float 2.3 to the int 2
print(int(-2.3)) # convert the float -2.3 to the int -2
print(int('25')) # convert the string '25' to the int 25

"""Each type has its own conversion function:"""

print(float(2))     # convert the int 2 to the float 2.0
print(float('2.3')) # convert the string '2.3' to the float 2.3
print(str(23))      # convert the int 23 to the string '23'

"""### Arithmetic and Math Functions
Here are some useful built-in arithmetic and math functions:

#### `abs`
This returns the *absolute value* of its argument,
preserving its type.
"""

print(abs(123))
print(abs(-123))

print(abs(1.23))
print(abs(-1.23))

"""#### `min` and `max`
These return the smallest and largest values of their arguemnts:
"""

print(min(2,1,4,3))
print(max(2,1,4,3))

"""#### `round`
This returns its value rounded to the nearest integer:
"""

print(round(2.3))
print(round(2.8))

"""Values that end in .5 are rounded to the nearest even:"""

print(round(1.5))
print(round(2.5)) # surprised?

"""We can add a second argument for the number of digits after
the decimal to round to:
"""

print(round(2.468))
print(round(2.468, 1))
print(round(2.468, 2))

"""#### `math.floor` and `math.ceil`
`math.floor` returns the largest int no larger than its argument. <br>
`math.ceil` (for *ceiling*) returns the smallest int no smaller than its argument.
"""

import math

print(math.floor(2.4))
print(math.ceil(2.4))

"""Be sure to understand how this works with negative arguments:"""

print(math.floor(-5.8))
print(math.ceil(-5.8))

"""Both of these functions return their argument unchanged if it is already an int:"""

print(math.floor(9))
print(math.ceil(9))

"""## Writing Functions
When we write code, we mainly write *functions*.  We are almost
ready for you to write your first functions!

### Why Write Functions?
Structuring your code using functions has many advantages, including these:

  1. Clearer Code
  
  2. Reusable Code

  3. Testable and Debuggable Code

  4. Industry Standard code

### Defining vs Calling Functions
As we have seen, we first use `def` to *define* a function. <br>
Once a function is defined, we can then *call* it.
"""

# First we define the function f:
def f(x):
    return 10 * x

# Now we can call this function:
print(f(123))

"""### Parameters vs Arguments
*Parameters* are the named variables that a function takes in a
function definition. <br>
*Arguments* are the values passed in to those variables
in a function call.
"""

def f(x, y):  # x and y are parameters
    return x**2 + y**2

print(f(2, 3)) # 2 and 3 are arguments
               # When we call f, the parameters are set to the arguments.
               # Here, x is set to 2, and y is set to 3

"""### Variable Scope
The *scope* of a variable is where it can be used.

#### Local Variables
Variables inside a function have *local* scope and are
called *local variables* (or just *locals*).
They can only be used in that function.  This includes parameters, and any
other variables you use in a function.

Functions cannot see the local variables in another function,
even if they have the same name.
"""

def f(x):
    y = 1  # Here y is a local variable in the function f
    return x + y

def g(x):
    y = 2  # Here y is a local variable in the function g.
           # It has the same name as the local y in f,
          # but these are two entirely unrelated variables.
    return x + y

print(f(5))
print(g(5))

"""#### Parameters are Local Variables
This is why two functions can use the same variable names
for their parameters without affecting each other.
"""

def f(x):
    # Here x is a parameter, so it is a local variable in f.
    x += 1
    return x

def g(x):
    # Here x is a parameter, so it is a local variable in g.
    # This x has nothing to do with the local x in f.
    x += 2
    return x

print(f(5))
print(g(5))

"""#### Global Variables
Variables that are set outside of any function have *global* scope and are
called *global variables* (or just *globals*).  Every function can
see global variables.
"""

# This shows how globals work.
# But you should not write code like this (see below).

delta = 5 # this is a global variable, visible by all functions

def plusDelta(x):
    return x + delta

def timesDelta(x):
    return x * delta

print(plusDelta(5))
print(timesDelta(5))

"""#### Avoid Globals
In general, you should avoid using global variables.  Their use is complicated and
prone to errors.  For now, stick to local variables.

The one exception is that it is ok to store constants in global variables.
If you do this, it is standard practice to capitalize their names.
For example:
"""

# This is an acceptable use of globals:
GAMMA = 0.57721566490153286

def addGamma(x):
    return x + GAMMA

print(addGamma(2))

"""### Return Statements
When a function reaches a `return` statement, it stops running and
returns the value in that statement.

Thus, code placed after a return statement is *unreachable* (also
called *dead code*).  You should not include unreachable code
in your programs.
"""

def f(x):
    return x*5
    print('This line is unreachable -- it will never run!')

print(f(2))

"""If a function does not include a return statement, Python simply
returns `None` for that function.
"""

# See how this function does not have a return statement:
def f(x):
    y = x + 5

# Thus, Python returns None when we call f:
print(f(3))

"""### `print` vs `return`
A common mistake by new coders is to use `print` instead of `return` in
a function.  This can even seem to work right:
"""

def square(x):
    print(x**2) # This uses print instead of return!

print(square(5))

"""The code prints 25, but it also prints None, suggesting that something is wrong.
Something is very wrong indeed, as we see here:
"""

def square(x):
    print(x**2) # This uses print instead of return!

x = square(5)
print(x * 10) # surprised?

"""The solution is to return the proper value and not print it, like so:"""

def square(x):
    return x**2 # This correctly uses return now!

x = square(5)
print(x * 10) # works!

"""### Returning Multiple Values
Functions can return multiple comma-separated values.

These can be assigned to multiple comma-separated variables, like so:
"""

def squares(x, y):
    # return two values -- the squares of each argument
    return x**2, y**2

x = 5
y = 10

xSquared, ySquared = squares(x, y) # see how we assign two variables at once
                                   # to the two return values of the function

print(xSquared, ySquared)

"""### Helper Functions
When solving a problem with code, we often can write functions that help by solving
a smaller part of the problem.  These are called *helper functions*.
"""

# This is a helper function.  It is used by largerOnesDigit below.
def onesDigit(n):
    return n % 10

# This function uses the helper function defined above.
def largerOnesDigit(x, y):
    return max(onesDigit(x), onesDigit(y))

print(largerOnesDigit(134, 672)) # 4
print(largerOnesDigit(132, 674)) # Still 4

"""### Type Hints
Functions can optionally use *type hints* (also called *type declarations*)
to declare the types of their arguments and
the type of their result.  For example:
"""

# Example code without type hints:
def getGreeting(name, age):
    return f'Hi {name}. When you double your age, you will be {age*2} years old!'

print(getGreeting('Fred', 30)) # Fred is currently 30

"""Clearly it is our *intention* when we defined getGreeting that name should
be a string, and age should be an int, and that getGreeting returns another string.

We can make this *explicit* using type hints.  In particular:

  * We replace `name` with `name: str` to note that name should be a string.
  
  * We replace `age` with `age: int` to note that age should be an int.
  
  * After the parameter list and before the closing colon (:) on the def line,
    we add ` -> str` to note that the function should return a string.

Putting this all together we get:
"""

# Same example code with type hints:
def getGreeting(name: str, age: int) -> str:
    return f'Hi {name}. When you double your age, you will be {age*2} years old!'

print(getGreeting('Fred', 30))

"""The code runs the same!

Note that hints are just hints. They are not enforced.
"""

# Same example code with type hints:
def getGreeting(name: str, age: int) -> str:
    return f'Hi {name}. When you double your age, you will be {age*2} years old!'

# But this time we use the wrong types when calling getGreeting:
print(getGreeting(123, 'thirty'))

"""In most programming languages, code with type mismatches will not run.

In Python, the code runs (so type hints are not enforced), but probably
in unwanted ways.

  * See how it printed thirtythirty?  That can't be what we wanted!
  
*The Bottom Line:* Type hints are a good way to let coders know the types
your function expects to receive and to return, but they are just hints.
You should be comfortable writing code with type hints but also without type hints.

### Test Functions
In general, we write functions to solve problems. We then use *test functions*
to test if our functions work properly. When we assign a problem to you,
we often include a test function for you.  For example:
"""

! uname -a

# This is what a sample problem looks like, with a test function we provided.

# Write the function isPositive(x) that takes a number (int or float) x
# and returns True if x is positive (greater than 0) and False otherwise.
def isPositive(x):
    pass

def testIsPositive():
    print('Testing isPositive()...', end='')
    assert(isPositive(1) == True)
    assert(isPositive(0) == False)
    assert(isPositive(-1) == False)
    print('Passed!')

testIsPositive()

"""Your job is to replace the `pass` statement (which does nothing) with your
own code that solves the given problem.

Run the code above and see how it fails on the first test case.
A call to isPositive(1) was supposed to return True, but it returned None
(because we have not written the function yet!).

Here is a solved version of that problem:
"""

# This a sample solution to the problem above:

# Write the function isPositive(x) that takes a number (int or float) x
# and returns True if x is positive (greater than 0) and False otherwise.
def isPositive(x):
    return (x > 0)

def testIsPositive():
    print('Testing isPositive()...', end='')
    assert(isPositive(1) == True)
    assert(isPositive(0) == False)
    assert(isPositive(-1) == False)
    print('Passed!')

testIsPositive()

"""#### Incomplete Test Functions
For now, we will provide you with test functions.  But soon you should
write your own test functions.  Thus, it is important that you know to
include test cases for all so-called *edge cases* that may arise.

Here is an example of an incomplete test function:
"""

def onesDigit(n):
    return n%10

# This test function is incomplete!  Do you see why?
def testOnesDigit():
    print('Testing onesDigit()...', end='')
    assert(onesDigit(5) == 5)
    assert(onesDigit(123) == 3)
    assert(onesDigit(100) == 0)
    print('Passed!')

testOnesDigit() # Passed!  Why is this bad?

"""Our code passed the test function *even though it has a bug!*.
This improved version of the test function catches our bug:
"""

def onesDigit(n):
    return n%10

# This test function now catches the bug:
def testOnesDigit():
    print('Testing onesDigit()...', end='')
    assert(onesDigit(5) == 5)
    assert(onesDigit(123) == 3)
    assert(onesDigit(100) == 0)
    assert(onesDigit(-123) == 3) # Added this test
    print('Passed!')

testOnesDigit() # Crashed!  So the test function worked (it caught the bug!)

"""The improved test function caught the bug in `onesDigit`.  Can you fix it?
In any case, be aware that test functions are only really useful
if they have well-chosen test cases.
"""