# -*- coding: utf-8 -*-
"""5 - Additional Topics (Data and Functions).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B9uc0_n9qUdBzMl6-htoyJSWz5Bu7BCY

<font size="1" color="#AAA">Python Fundamentals &copy; David Kosbie</font>  

# Additional Topics (Data and Functions)
Here are some additional topics that are not part of the core curriculum.
However, they are likely to be useful to you in your coding future.
If you are new to Python, you can skip these topics for now and
return later.  For those of you with some Python experience,
you may find some useful concepts here that are new to you.

## Assignment Expressions (Walrus Operator)
We can use the *walrus operator* (`:=`) to assign to a variable in an expression.
"""

x = (y := 5) * 10
print(x)
print(y)

"""## `is` vs `==`
Python includes the `is` operator, which appears to be similar to `==`.
"""

x = 5
y = 5
print(x == y)
print(x is y)

"""However, `is` and `==` are *not* the same:"""

x = 257
y = 257
print(x == y)
print(x is y) # shocking!

"""We will discuss `is` more when we cover *aliasing* of strings and lists. <br>
For now, it is best if you just *avoid using `is`*.

## More Built-In Functions

### dir and help
`dir` shows the values in an object.  These include many of the methods you can call on the object
(along with lots of other stuff you can ignore).
"""

# A quick way to see the str methods:
print(dir(str))

"""`help` shows the documentation for a function or module."""

help(str) # notice how we do not use print here

"""We can also use help to get details about a specific method:"""

help(str.strip)

"""### int, bin, oct, and hex
These functions convert numbers into string representations in various bases:
  * `bin(x)`: convert to binary (base 2)

  * `oct(x)`: convert to octal (base 8)

  * `hex(x)`: convert to hexadecimal (base 16)

And this function goes the other way, converting back to integers in various bases:
  * `int(x, base=10)`: convert x to an int in the given base
"""

# convert 123 into different bases (results are strings)
print(bin(123))
print(oct(123))
print(hex(123))

# convert the string '101' into different bases:
print(int('101'))
print(int('101', 2))
print(int('101', 8))
print(int('101', 16))

"""### pow and math.pow
We use `**` to exponentiate, but `pow` and `math.pow` also do this. <br>
They work subtly differently, however.<br>
For example, `math.pow` returns floats, and does not work over complex numbers.<br>
We suggest you stick with `**` to exponentiate.
"""

import math
print(2**5)
print(pow(2, 5))
print(math.pow(2, 5)) # note this is a float

# (1 + 2j) is a complex number
print((1 + 2j) ** 3)       # works
print(pow(1 + 2j, 3))      # works
print(math.pow(1 + 2j, 3)) # fails

"""### isinstance
`isinstance(x, t)` returns True if x is an instance of the given type t.
"""

print(isinstance(123, int))
print(isinstance(123, float))

print(isinstance(1.23, int))
print(isinstance(1.23, float))

"""We can use so-called *superclasses* to test for multiple types at once.
For example, we can test for any kind of number like so:
"""

import numbers
print(isinstance(123, numbers.Number))
print(isinstance(1.23, numbers.Number))
print(isinstance(1+2j, numbers.Number)) # even works for complex numbers!

"""## roundHalfUp
The built-in `round` function rounds to the nearest even:
"""

print(round(1.5))
print(round(2.5)) # surprised?

print(round(-2.5)) # surprised?
print(round(-1.5))

"""If you truly require rounding up in the more

---

traditional way,
you can use this `roundHalfUp` function we provdide for you here:
"""

import decimal

def roundHalfUp(d):
    # Round to nearest with ties going away from zero.
    rounding = decimal.ROUND_HALF_UP
    return int(decimal.Decimal(d).to_integral_value(rounding=rounding))

print(roundHalfUp(1.5))
print(roundHalfUp(2.5)) # works as expected

print(roundHalfUp(-2.5)) # ditto
print(roundHalfUp(-1.5))

"""## Functions as Values
We can use functions as values mostly like any other values. <br>
Here is an example of something we can do that you should not do.
"""

max = min # this is a bad idea, but shows how function names are
          # variables like any other variables

print(max(2, 3)) # surprised?

"""### Functions as Arguments
We can write functions that take other functions as arguments.
"""

def callTwice(f, x):
    return f(f(x))

def timesTen(x):
    return 10*x

def divideByTen(x):
    return x//10

print(callTwice(timesTen, 456))
print(callTwice(divideByTen, 456))

"""### Functions that Return Functions
Functions can even return functions:
"""

def makeCallTwiceFunction(f):
    def newFunction(x):
        return f(f(x))
    return newFunction

def timesTen(x):
    return 10 * x

def divideByTen(x):
    return x // 10

timesHundred = makeCallTwiceFunction(timesTen)
divideByHundred = makeCallTwiceFunction(divideByTen)

print(timesHundred(456))
print(divideByHundred(456))

"""### Lambda Functions
Lambda functions are also called `anonymous functions`.<br>
Lambda functions are expressions, and can be assigned to variables.<br>
Lambda functions are limited in Python, and can only return a single expression.
"""

def callTwice(f, x):
    return f(f(x))

f = lambda x: 10 * x

print(f(456))
print(callTwice(f, 456))

"""We can use a lambda function without ever assigning it to a variable:"""

def callTwice(f, x):
    return f(f(x))

print(callTwice(lambda x: x * 10, 456))

"""## More on Globals
While globals are discouraged, they are used sometimes in practice, so
it's good for you to know a bit more about them.

### Assignment and Locals
Assigning a value to a variable in a function makes that variable local. <br>
If there is a global variable of the same name, we say that the local
variable *hides* the global variable.
"""

delta = 42 # global

def f(x):
    delta = 5 # hides the global, so this is a local variable
    return x + delta

def g(x):
    return x + delta

print(f(1))
print(g(1))
print(delta)

"""### The global Declaration
We use `global` to declare a variable is global.  Compare this code
to the code above:
"""

delta = 42 # global

def f(x):
    global delta # this makes delta global
    delta = 5 # does not hides the global anymore
    return x + delta

def g(x):
    return x + delta

print(f(1))
print(g(1))
print(delta)

"""### locals() and globals()
These functions return the local and global variables currently in scope. <br>
Printing locals can be useful when debugging.
"""

delta = 42

def f(x):
    print(locals())
    print(globals()) # this prints a lot!
    return x + delta

print(f(1))

"""We can use `globals()` to access a hidden global variable:"""

delta = 42

def f(x):
    delta = 5 # hides the global
    print(f'local value of delta: {delta}')
    print(f'global value of delta: {globals()["delta"]}')
    return x + delta

print(f(1))

"""## docstrings
We can provide *documentation* for a function by adding a *docstring*
after the `def` line. Then `help` works with the function.
"""

def absoluteDifference(x, y):
    """
    Returns the absolute difference between x and y.  That is, |x - y|.

    Args:
        x (int): The first number.
        y (int): The second number.

    Returns:
        int: The absolute difference |x - y|.
    """
    return abs(x - y)

print(absoluteDifference(3, 5))
help(absoluteDifference)