# -*- coding: utf-8 -*-
"""4 - Worked Examples (Data and Functions).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12ntj66pbbUxLk9EINycRkjj8sLro0NIl

<font size="1" color="#AAA">Python Fundamentals &copy; David Kosbie</font>  

# Worked Examples (Data and Functions)
This notebook contains examples for you to review before you work on this section's exercises.
Watch the video solutions closely, then be sure you can reproduce the solutions
on your own!
<br><br>
Note: to help you focus on the materials we are currently covering,
you should resist using concepts we have not yet covered. For example,
here you should use arithmetic only, and resist using
conditionals, loops, strings, or lists yet (even if you
already know them well).

## Problem Statements
This section contains the problem statements and starter code.
Watch the accompanying video, then try to solve the problems
yourself.  If needed, you can refer to the sample solutions below.

### distance
Write the function distance(x1, y1, x2, y2) which takes four int or float values x1, y1, x2, y2 that represent the two points (x1, y1) and (x2, y2), and returns the distance between those points as a float.
"""

import math

def distance(x1, y1, x2, y2):
    pass

def almostEqual(x, y):
    epsilon = 10**-9
    return abs(x - y) < epsilon

def testDistance():
    print('Testing distance()...', end='')
    assert(almostEqual(distance(0, 0, 0, 1), 1))
    assert(almostEqual(distance(0, 0, 1, 0), 1))
    assert(almostEqual(distance(1, 5, 1, 12), 7))
    assert(almostEqual(distance(-7, -11, 5, -2), 15))
    assert(almostEqual(distance(-13, 21, 3, 51), 34))
    assert(almostEqual(distance(0, 0, 0, 0), 0))
    assert(almostEqual(distance(5, 5, 0, 0), 5 * math.sqrt(2)))
    assert(almostEqual(distance(-3, 1, -2, 4), math.sqrt(10)))
    assert(type(distance(0, 0, 0, 1)) == float)
    print('Passed!')

def main():
    testDistance()

main()

"""### getKthDigit
Write the function getKthDigit(n, k) which takes a possibly-negative int n and a non-negative int k, and returns the kth digit in n. The 0th digit is the rightmost digit, and counting goes right to left.
"""

def getKthDigit(n, k):
    pass

def testGetKthDigit():
    print('Testing getKthDigit()...', end='')
    assert(getKthDigit(456, 0) == 6)
    assert(getKthDigit(456, 1) == 5)
    assert(getKthDigit(456, 2) == 4)
    assert(getKthDigit(456, 3) == 0)
    assert(getKthDigit(0, 0) == 0)
    assert(getKthDigit(0, 1) == 0)
    assert(getKthDigit(-456, 0) == 6)
    assert(getKthDigit(-456, 1) == 5)
    assert(getKthDigit(-456, 2) == 4)
    assert(getKthDigit(-456, 3) == 0)
    print('Passed!')

def main():
    testGetKthDigit()

main()

"""### setKthDigit
Write the function setKthDigit(n, k, d) which takes a non-negative int n, a non-negative int k, and a non-negative single digit int d. Return the number n with the kth digit replaced with d. The 0th digit is the rightmost digit, and counting goes right to left.
"""

def setKthDigit(n, k, d):
    pass

def testSetKthDigit():
    print('Testing setKthDigit()...', end='')
    assert(setKthDigit(456, 0, 7) == 457)
    assert(setKthDigit(456, 1, 7) == 476)
    assert(setKthDigit(456, 2, 7) == 756)
    assert(setKthDigit(456, 3, 7) == 7456)
    assert(setKthDigit(456, 4, 7) == 70456)
    assert(setKthDigit(0, 0, 7) == 7)
    assert(setKthDigit(0, 1, 7) == 70)
    print('Passed!')

def main():
    testSetKthDigit()

main()

"""<pre>

</pre>
<hr>

## Sample Solutions
This section contains sample solutions to these exercises.

Note that there are many good ways to solve every problem.  These are just
one way of doing so.  If you found another good approach, that's fine!

Also, these may not even exactly match the solutions in the accompanying
videos.  That's fine. Again, there are many good solutions to
most problems.

Finally, while you are strongly encouraged to review these (that's
why we are providing them to you, after all), we recommend that you
try to get to the point where you can solve the problems above without
referring to the video or these sample solutions.  You can do it!

### distance
Write the function distance(x1, y1, x2, y2) which takes four int or float values x1, y1, x2, y2 that represent the two points (x1, y1) and (x2, y2), and returns the distance between those points as a float.
"""

import math

def distance(x1, y1, x2, y2):
    return ((x2 - x1)**2 + (y2 - y1)**2)**0.5

def almostEqual(x, y):
    epsilon = 10**-9
    return abs(x - y) < epsilon

def testDistance():
    print('Testing distance()...', end='')
    assert(almostEqual(distance(0, 0, 0, 1), 1))
    assert(almostEqual(distance(0, 0, 1, 0), 1))
    assert(almostEqual(distance(1, 5, 1, 12), 7))
    assert(almostEqual(distance(-7, -11, 5, -2), 15))
    assert(almostEqual(distance(-13, 21, 3, 51), 34))
    assert(almostEqual(distance(0, 0, 0, 0), 0))
    assert(almostEqual(distance(5, 5, 0, 0), 5 * math.sqrt(2)))
    assert(almostEqual(distance(-3, 1, -2, 4), math.sqrt(10)))
    assert(type(distance(0, 0, 0, 1)) == float)
    print('Passed!')

def main():
    testDistance()

main()

"""### getKthDigit
Write the function getKthDigit(n, k) which takes a possibly-negative int n and a non-negative int k, and returns the kth digit in n. The 0th digit is the rightmost digit, and counting goes right to left.
"""

def getKthDigit(n, k):
    n = abs(n)
    return n // 10**k % 10

def testGetKthDigit():
    print('Testing getKthDigit()...', end='')
    assert(getKthDigit(456, 0) == 6)
    assert(getKthDigit(456, 1) == 5)
    assert(getKthDigit(456, 2) == 4)
    assert(getKthDigit(456, 3) == 0)
    assert(getKthDigit(0, 0) == 0)
    assert(getKthDigit(0, 1) == 0)
    assert(getKthDigit(-456, 0) == 6)
    assert(getKthDigit(-456, 1) == 5)
    assert(getKthDigit(-456, 2) == 4)
    assert(getKthDigit(-456, 3) == 0)
    print('Passed!')

def main():
    testGetKthDigit()

main()

"""### setKthDigit
Write the function setKthDigit(n, k, d) which takes a non-negative int n, a non-negative int k, and a non-negative single digit int d. Return the number n with the kth digit replaced with d. The 0th digit is the rightmost digit, and counting goes right to left.
"""

def getKthDigit(n, k):
    n = abs(n)
    return n // 10**k % 10

def setKthDigit(n, k, d):
    kthDigit = getKthDigit(n, k)
    withoutOldDigit = n - kthDigit * 10**k
    withNewDigit = withoutOldDigit + d * 10**k
    return withNewDigit

def testSetKthDigit():
    print('Testing setKthDigit()...', end='')
    assert(setKthDigit(456, 0, 7) == 457)
    assert(setKthDigit(456, 1, 7) == 476)
    assert(setKthDigit(456, 2, 7) == 756)
    assert(setKthDigit(456, 3, 7) == 7456)
    assert(setKthDigit(456, 4, 7) == 70456)
    assert(setKthDigit(0, 0, 7) == 7)
    assert(setKthDigit(0, 1, 7) == 70)
    print('Passed!')

def main():
    testSetKthDigit()

main()