# -*- coding: utf-8 -*-
"""Level 2 topScorer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AcYO_j1xYWcctowx_w6zPMSZjIccmgX0

#### Problem Writeup



 Write the function `topScorer(data)` that takes a multiline
 string representing the scores for a competition. The first value on
 each line is the name of the player (which you can assume has no
 integers in it). Each value after that is an individual score (which you
 can assume is a non\-negative integer). All values on a line are
 separated by commas.




 The function should return the player with the highest total score
 (where a player's total score is the sum of all their scores). If there
 is a tie, return the names of the tied players in a comma\-separated
 string. They should appear in the same order they appeared in the
 original data. If nobody wins (because there is no data), return
 `None` (not the string `'None'`). So, for example:





```

data = '''\
Joe,10,20,30,40
Lauren,10,20,30
Ben,10,20,30,5
'''
assert(topScorer(data) == 'Joe')

data = '''\
David,11,20,30
Austin,10,20,30,1
Lauren,50
'''
assert(topScorer(data) == 'David,Austin')
```




#### Guided Solution
"""

def topScorer(data):
    if not data.strip():
        return None

    lines = data.strip().split('\n')
    scores = {}
    order = []

    for line in lines:
        parts = line.split(',')
        name = parts[0]
        player_scores = list(map(int, parts[1:]))
        total_score = sum(player_scores)

        if name not in scores:
            scores[name] = 0
            order.append(name)
        scores[name] += total_score

    max_score = max(scores.values())
    winners = [name for name in order if scores[name] == max_score]

    return ','.join(winners)

def testTopScorer():
    print('Testing topScorer()...', end='')
    print('Passed!')
    data = '''\
Joe,10,20,30,40
Lauren,10,20,30
Ben,10,20,30,5
'''
    assert(topScorer(data) == 'Joe')

    data = '''\
David,11,20,30
Austin,10,20,30,1
Lauren,50
'''
    assert(topScorer(data) == 'David,Austin')

    data = '''\
Ping-Ya,100,80,90
'''
    assert(topScorer(data) == 'Ping-Ya')

    data = '''\
Reyna,20,40,40
Ema,5,5,5,5,10
Ketandu,50,20,10,20
Tanya,80,20
Kate,70
'''
    assert(topScorer(data) == 'Reyna,Ketandu,Tanya')

    assert(topScorer('') == None)

def main():
    testTopScorer()

main()