# -*- coding: utf-8 -*-
"""2 - While Loops.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19qnyecMTMspGzEV2FDxCTo5Yr1hPJa6N

<font size="1" color="#AAA">Python Fundamentals &copy; David Kosbie</font>  

# While Loops

## While Loops
A while loop is just like an if statement, only it keeps looping over the body while the condition remains True (that is, until the condition is False).
"""

# Example code using an if statement:
x = 5
print(f'At first, x = {x}')
if x < 10:
    x += 1
    print(f'now x = {x}')
print(f'afterwards, x = {x}')

# Same example code replacing if with while:
x = 5
print(f'At first, x = {x}')
while x < 10:
    x += 1
    print(f'now x = {x}')
print(f'afterwards, x = {x}')

"""## For Loops vs While Loops

  * Use a for loop when you know the number of iterations before looping.
  
    * This includes looping over a range, a string, or a list.
    
  * Use a while loop when you do not know the number of iterations before looping.
  
  Let's look at some examples.

### leftmostDigit
Write the function leftmostDigit(n) that takes an int n and returns its
leftmost (or leading) digit.  For example, leftmostDigit(1234) returns 1.
  
While it is possible to write this without loops (using strings or using logarithms),
write this solution using loops instead.

To do so, we will repeatedly remove the rightmost digit in a loop until only one digit remains.

Since we do not know how many times we need to do this, we will use a while loop.
"""

def leftmostDigit(n):
    n = abs(n)
    while n >= 10:
        n //= 10
    return n

print(leftmostDigit(1234))
print(leftmostDigit(-1234))
print(leftmostDigit(972875627627248724782347823823482472348723487243))

"""### digitCount
Write the function digitCount(n) that takes an int n and returns the
number of digits in n.  For example:

  * digitCount(2222) returns 4
  * digitCount(-567) returns 3
  * digitCount(0) returns 1
"""

def digitCount(n):
    n = abs(n)
    result = 1
    while n >= 10:
        n //= 10
        result += 1
    return result

print(digitCount(2222))
print(digitCount(-567))
print(digitCount(0))