# -*- coding: utf-8 -*-
"""6 - Worked Examples (Loops).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gUpan3ZwA7nc39auK937TZ_wZSo2cwOX

<font size="1" color="#AAA">Python Fundamentals &copy; David Kosbie</font>  

# Worked Examples (Loops)
This notebook contains examples for you to review before you work on this section's exercises.
Watch the video solutions closely, then be sure you can reproduce the solutions
on your own!

Note: to help you focus on the materials we are currently covering,
you should resist using concepts we have not yet covered. For example,
here you should resist using lists yet (even if you already know them well).

## Problem Statements
This section contains the problem statements and starter code.
Watch the accompanying video, then try to solve the problems
yourself.  If needed, you can refer to the sample solutions below.

### areAnagrams
Background: Two strings are anagrams if each string can be reordered into the other. Treat uppercase and lowercase as the same letter (so 'Abca' and 'BAAc' are anagrams).

With this in mind, write the function areAnagrams(s1, s2) that takes two strings, s1 and s2, that you may assume contain only letters, and returns True if the strings are anagrams, and False otherwise.

Do not use sort(), sorted(), or any other list-based functions or approaches.

Hints:

  * Do not try to reorder either string! This can be solved more easily by not doing that.
  
  * Instead, s.count() could be quite handy here.
  
  * Also note that every string is an anagram of itself.
"""

def areAnagrams(s1, s2):
    pass

def testAreAnagrams():
    print('Testing areAnagrams()...', end='')
    assert(areAnagrams('Abca', 'BAAc') == True)
    assert(areAnagrams('Word', 'word') == True)
    assert(areAnagrams('CAT', 'act') == True)
    assert(areAnagrams('', '') == True)
    assert(areAnagrams('abcd', 'abc') == False)
    assert(areAnagrams('abc', 'abcd') == False)
    assert(areAnagrams('abc', 'abd') == False)
    assert(areAnagrams('abc', 'abc') == True)
    print('Passed!')

def main():
    testAreAnagrams()

main()

"""### mostFrequentLetters
Write the function mostFrequentLetters(text) that takes a string *text* and
returns another string in alphabetical order containing the letter or letters
that occur most frequently in *text*.

Your test should be *case-insensitive*, so treat uppercase and lowercase
the same.  And your result should be in uppercase.

Finally, if there are no letters in text, return None.
"""

import string

def mostFrequentLetters(text):
    pass

def testMostFrequentLetters():
    print('Testing mostFrequentLetters()...', end='')
    assert(mostFrequentLetters('ABCA') == 'A')
    assert(mostFrequentLetters('abca') == 'A')
    assert(mostFrequentLetters('BCAAB') == 'AB')

    assert(mostFrequentLetters('This is a test.') == 'ST')
    assert(mostFrequentLetters('Yet another test.') == 'T')
    assert(mostFrequentLetters('And one more.') == 'ENO')
    assert(mostFrequentLetters('?!?!?!?!?!?!?') == None)
    print('Passed!')


testMostFrequentLetters()

"""### capitalizeFirstWordsOnly
Write the function capitalizeFirstWordsOnly(text) that takes a string *text*
and returns another string where the first letter of the first word of
each sentence in text is capitalized, and all other letters are lowercase.

Non-letters are left as-is.

You should assume that all sentences end in a period, exclamation mark, or question mark.

Don't worry about special cases like quotes in sentences or other unusually-formatted
text.  Assume the text is formatted similarly to the test cases.
"""

def capitalizeFirstWordsOnly(text):
    return code

def testCapitalizeFirstWordsOnly():
    print('Testing capitalizeFirstWordsOnly()...', end='')
    assert(capitalizeFirstWordsOnly('hi. howdy. hi there.') ==
                                    'Hi. Howdy. Hi there.')
    assert(capitalizeFirstWordsOnly('this is a test? yes! for sure!') ==
                                    'This is a test? Yes! For sure!')
    assert(capitalizeFirstWordsOnly('THIS, TOO? yes!') ==
                                    'This, too? Yes!')
    assert(capitalizeFirstWordsOnly('') == '')
    print('Passed!')

testCapitalizeFirstWordsOnly()

"""<pre>

</pre>
<hr>

## Sample Solutions
This section contains sample solutions to these exercises.

Note that there are many good ways to solve every problem.  These are just
one way of doing so.  If you found another good approach, that's fine!

Also, these may not even exactly match the solutions in the accompanying
videos.  That's fine. Again, there are many good solutions to
most problems.

Finally, while you are strongly encouraged to review these (that's
why we are providing them to you, after all), we recommend that you
try to get to the point where you can solve the problems above without
referring to the video or these sample solutions.  You can do it!

### areAnagrams
Background: Two strings are anagrams if each string can be reordered into the other. Treat uppercase and lowercase as the same letter (so 'Abca' and 'BAAc' are anagrams).

With this in mind, write the function areAnagrams(s1, s2) that takes two strings, s1 and s2, that you may assume contain only letters, and returns True if the strings are anagrams, and False otherwise.

Do not use sort(), sorted(), or any other list-based functions or approaches.

Hints:

  * Do not try to reorder either string! This can be solved more easily by not doing that.
  
  * Instead, s.count() could be quite handy here.
  
  * Also note that every string is an anagram of itself.
"""

import string

# We provide two sample solutions here. This solution checks that every
# letter in the alphabet appears the same number of times in s1 and s2

def areAnagrams(s1, s2):
    s1 = s1.lower()
    s2 = s2.lower()
    for letter in string.ascii_lowercase:
        if s1.count(letter) != s2.count(letter):
            return False
    return True

# This solution checks that every letter in s1 appears the same number of
# times in s2. The length check is necessary to ensure there aren't extra
# letters in s2

def areAnagrams(s1, s2):
    if len(s1) != len(s2):
        return False
    s1 = s1.lower()
    s2 = s2.lower()
    for letter in s1:
        if s1.count(letter) != s2.count(letter):
            return False
    return True

def testAreAnagrams():
    print('Testing areAnagrams()...', end='')
    assert(areAnagrams('Abca', 'BAAc') == True)
    assert(areAnagrams('Word', 'word') == True)
    assert(areAnagrams('CAT', 'act') == True)
    assert(areAnagrams('', '') == True)
    assert(areAnagrams('abcd', 'abc') == False)
    assert(areAnagrams('abc', 'abcd') == False)
    assert(areAnagrams('abc', 'abd') == False)
    assert(areAnagrams('abc', 'abc') == True)
    print('Passed!')

def main():
    testAreAnagrams()

main()

"""### mostFrequentLetters
Write the function mostFrequentLetters(text) that takes a string *text* and
returns another string in alphabetical order containing the letter or letters
that occur most frequently in *text*.

Your test should be *case-insensitive*, so treat uppercase and lowercase
the same.  And your result should be in uppercase.

Finally, if there are no letters in text, return None.
"""

import string

def mostFrequentLetters(text):
    text = text.upper()
    bestCount = bestLetters = None
    for letter in string.ascii_uppercase:
        count = text.count(letter)
        if (count > 0) and ((bestCount == None) or (count > bestCount)):
            bestCount = count
            bestLetters = letter
        elif count == bestCount:
            bestLetters += letter
    return bestLetters

def testMostFrequentLetters():
    print('Testing mostFrequentLetters()...', end='')
    assert(mostFrequentLetters('ABCA') == 'A')
    assert(mostFrequentLetters('abca') == 'A')
    assert(mostFrequentLetters('BCAAB') == 'AB')

    assert(mostFrequentLetters('This is a test.') == 'ST')
    assert(mostFrequentLetters('Yet another test.') == 'T')
    assert(mostFrequentLetters('And one more.') == 'ENO')
    assert(mostFrequentLetters('?!?!?!?!?!?!?') == None)
    print('Passed!')

testMostFrequentLetters()

"""### capitalizeFirstWordsOnly
Write the function capitalizeFirstWordsOnly(text) that takes a string *text*
and returns another string where the first letter of the first word of
each sentence in text is capitalized, and all other letters are lowercase.

Non-letters are left as-is.

You should assume that all sentences end in a period, exclamation mark, or question mark.

Don't worry about special cases like quotes in sentences or other unusually-formatted
text.  Assume the text is formatted similarly to the test cases.
"""

def capitalizeFirstWordsOnly(text):
    result = ''
    prevNonSpaceChar = None
    for c in text:
        if c.isalpha():
            if (prevNonSpaceChar == None) or (prevNonSpaceChar in '.?!'):
                c = c.upper()
            else:
                c = c.lower()
        result += c
        if c != ' ':
            prevNonSpaceChar = c
    return result

def testCapitalizeFirstWordsOnly():
    print('Testing capitalizeFirstWordsOnly()...', end='')
    assert(capitalizeFirstWordsOnly('hi. howdy. hi there.') ==
                                    'Hi. Howdy. Hi there.')
    assert(capitalizeFirstWordsOnly('this is a test? yes! for sure!') ==
                                    'This is a test? Yes! For sure!')
    assert(capitalizeFirstWordsOnly('THIS, TOO? yes!') ==
                                    'This, too? Yes!')
    assert(capitalizeFirstWordsOnly('') == '')
    print('Passed!')

testCapitalizeFirstWordsOnly()