# -*- coding: utf-8 -*-
"""Level 2 oneWeatherReport.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H_MF1q-fBKr-gPmKeCA0cXr-rc314Gyk

Background: this problem involves weather reports, which are multiline strings
 of this form:





```

weatherReport1 = '''
# Colder cities:
Boston: cloudy and cold
Chicago: frigid
Denver: sunny and cold

# Warmer cities:
Miami: hot and humid
San Diego: sunny and warm
'''
```





 Each line starts with a city name (which can contain spaces),
 followed by a colon, followed by the weather for that city. The report
 can also contain blank lines, and also lines with comments (that start
 with '\#') should be ignored.




 With this in mind, write the function `oneWeatherReport(report1, report2)`
 that takes two such reports (multiline strings), and returns a set of
 the cities that are included in exactly one but not both of the two reports.
"""

def oneWeatherReport(report1, report2):
    return 42

def testOneWeatherReport():
    print('Testing oneWeatherReport()...', end='')
    print('Passed!')
    weatherReport1 = '''
# Colder cities:
Boston: cloudy and cold
Chicago: frigid
Denver: sunny and cold

# Warmer cities:
Miami: hot and humid
San Diego: sunny and warm
'''

    weatherReport2 = '''
# Northern cities:
Boston: strong winds
Chicago: heavy rain

# Western cities:
Denver: cold, cold, cold!
Los Angeles: hot, hot, hot!
San Diego: beautiful!
'''
    assert(oneWeatherReport(weatherReport1, weatherReport2) ==
           {'Miami', 'Los Angeles'})


    weatherReport3 = '''
Seattle: freezing!
Pittsburgh: warm and sunny!

#Hey, there's a comment here!
Orlando: humid and hot!
'''

    weatherReport4 = '''
Orlando: still sunny over here!

Pittsburgh: cloudy and gray
#It might rain in Pittsburgh next week

Seattle: still freezing here!'''
    assert(oneWeatherReport(weatherReport3, weatherReport4) ==
           set())

def main():
    testOneWeatherReport()

main()