# -*- coding: utf-8 -*-
"""Level 4 satisfyExpressions.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11Un4_Ekd7Y5VhDQobRc234W5umtxxy8T

Background: We have seen how the condition in an "if" statement is
 a boolean expression \-\- that is, a value that evaluates to
 `True` or `False`.




 Here, we will limit ourselves to boolean expressions that use two
 boolean variables, `x` and `y`. So each of `x` and `y` can be `True`
 or `False`.




 For example:

```
(x and y)
```





 This is a boolean expression. We will try to "satisfy" the expression.
 That is, we will find a list of all the values of `x` and `y` for which the
 expression is `True`. For `(x and y)`, the
 expression is only `True` when both `x` and `y` are
 `True`, which we will represents as:

```
[(True, True)]
```





 Let's look at another example:

```
(x or y)
```

 This is `True` when either `x` is `True`, or `y` is
 `True`, or both `x` and `y` are `True`.
 Thus, the values that satisfy this expression are:

```
[(True, True), (True, False), (False, True)]
```





 Note that the order of the `(x, y)` tuples matters. If
 `(True, True)` is present,
 it must be first. Then, `(True, False)`,
 then `(False, True)`, then `(False, False)`.




 Here is another example:

```
(x or (not y))
```

 This is `True` when `x` is `True`, or `y` is
 `False` (so `(not y)` is `True`),
 or both. That is:

```
[(True, True), (True, False), (False, False)]
```





 Another example:

```
((x and (not y)) or ((not x) and y))
```

 This may take a bit of reasoning, but it is only `True` when
 exactly one of `x` and `y` is `True` and the other one is
 `False`. That is:

```
[(True, False), (False, True)]
```





 And one last example:

```
((x and (not x)) and y)
```

 This is never `True`. Thus, the list of values that
 satisifes this expression
 is empty:

```
[]
```


 With this in mind, write the function `satisfyExpression(expr)`,
 which takes a string, `expr`, that is a boolean expression that uses
 both `x` and `y`, and the function returns a (possibly\-empty) list of `(x,y)`
 values that satisfy that expression.




 To do this, we need to be precise about the format of expressions. Basic
 expressions will always be either just `x` or `y` by themselves.
 Complex expressions are made up of other expressions, and will always
 be of one of these forms:
 * (expr1 and expr2\)
* (expr1 or expr2\)
* (not expr1\)






 Note: You may not use the Python builtin functions `eval()`
 or `exec()` here.
 The point is for you to evaluate the expression yourself.




 Hints:
 * Write a helper function, `satisfiesExpression(expr, x, y)`,
 which takes an expression string, as noted above, and
 `True`/`False`
 values for each of `x` and `y`, and returns `True` if those values
 for `x` and `y` satisfy the expression (that is, make it evaluate to
 `True`). For example,
 `satisfiesExpression('(x and y)', True, False)` returns
 `False`,
 and `satisfiesExpression('(x and y)', True, True)` returns
 `True`.
* Call that function 4 times, once for each pair of values for `x` and `y`.
 That is, `(True, True)`, `(True, False)`,
 `(False, True)`, and `(False, False)`.
 We used two nested loops over the list
 `[True, False]` to do this.
* In `satisfiesExpression()`, we suggest that you first
 replace `x` and `y` in the string with the string `'True'` or
 `'False'`, depending on their values.
 Next, repeatedly find a part of the string which is parenthesized, but
 contains no left parentheses (we will call these "inner parentheses").
 This must be of a complex expression of one of these forms:
	+ (expr1 and expr2\)
	+ (expr1 or expr2\)
	+ (not expr1\)
 If you followed this closely, then at this point expr1 and expre2 will each
 be either the string `'True'` or the string `'False'`.
 So replace the whole parenthesized expression with either
 `'True'` or `'False'`. Then, keep doing this in
 a loop until all the parentheses are gone. At that point,
 you will have a single string, either `'True'` or
 `'False'`. Be sure to return
 a boolean value, not a string. So return `True` or
 `False`, not `'True'` or `'False'`.
* For example, here is the step\-by\-step way a call to
 `satisfiesExpression('(x or (not y))', False, False)` works:


| 1\) Start with: | `'(x or (not y))'` |
| --- | --- |
| 2\) Replace `x` with `'False'`: | `'(False or (not y))'` |
| 3\) Replace `y` with `'False'`: | `'(False or (not False))'` |
| 4\) Replace `'(not False)'` with `'True'`: | `'(False or True)'` |
| 5\) return `True`: | `True` |
* As another example, here is the step\-by\-step way a call to
 `satisfiesExpression('((x and (not y)) or ((not x) and y))', True, True)`
 works:


| 1\) Start with: | `'((x and (not y)) or ((not x) and y))'` |
| --- | --- |
| 2\) Replace `x` and `y`: | `'((True and (not True)) or ((not True) and True))'` |
| 3\) Replace `'(not True)'` with `'False'`: | `'((True and False) or ((not True) and True))'` |
| 4\) Replace `'(True and False)'` with `'False'`: | `'(False or ((not True) and True))'` |
| 5\) Replace `'(not True)'` with `'False'`: | `'(False or (False and True))'` |
| 6\) Replace `'(False and True)'` with `'False'`: | `'(False or False)'` |
| 7\) Replace `'(False or False)'` with `'False'`: | `'False'` |
| 8\) Return `False`: | `False` |


 ​​
* We also found it helpful to write the function
 `findInnerParens(expr)`, which returns a tuple
 `(i, j)` of the indexes of the left\-paren and
 right\-paren for the first inner parentheses in `expr`.
"""

def satisfyExpression(expr):
    return 42

def testSatisfyExpression():
    print('Testing satisfyExpression()...', end='')
    assert(satisfyExpression('(x and y)') ==
        [(True, True)])
    assert(satisfyExpression('(x or y)') ==
        [(True, True), (True, False), (False, True)])
    assert(satisfyExpression('(x or (not y))') ==
        [(True, True), (True, False), (False, False)])
    assert(satisfyExpression('((x and (not y)) or ((not x) and y))') ==
        [(True, False), (False, True)])
    assert(satisfyExpression('((x and (not x)) and y)') ==
        [])
    assert(satisfyExpression('x') ==
        [(True, True), (True, False)])
    print('Passed!')

def main():
    testSatisfyExpression()

main()