# -*- coding: utf-8 -*-
"""Level 4 isBoxy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RqwJKCHt6MpkQjPZVrPdyEkyoDgYgo3h

Background: Given a board represented as a 2D list of
 integers, we will say that a value `v`
 in the board is "boxy" (a coined term) if every
 occurrence of `v` lies in a single rectangular
 region on the board. We also say that the
 board itself is boxy if every value in the board is boxy.




 Here is an example of a boxy board:

```
board = [ [ 1, 1, 2, 3, 3, 3 ],
          [ 1, 1, 2, 3, 3, 3 ],
          [ 1, 1, 4, 3, 3, 3 ] ]
```





 We see that every value lies in one rectangular region:
 * the 1's are in a 3x2 rectangle
* the 2's are in a 2x1 rectangle
* the 3's are in a 3x3 rectangle
* the 4's are in a 1x1 rectangle






 With this in mind, write the function `isBoxy(board)`
 that takes a 2D rectangular list of integers and returns
 `True` if the board is boxy and `False`
 otherwise.
"""

def isBoxy(board):
    return 42

def testIsBoxy():
    print('Testing isBoxy()...', end='')
    board1 =  [ [ 1, 1, 2, 3, 3, 3 ],
                [ 1, 1, 2, 3, 3, 3 ],
                [ 1, 1, 4, 3, 3, 3 ] ]
    assert(isBoxy(board1) == True)

    board2 =  [ [ 2, 2, 3 ],
                [ 2, 2, 4 ],
                [ 1, 1, 4 ] ]
    assert(isBoxy(board2) == True)

    board3 =  [ [ 0, 1, 2, 3 ],
                [ 1, 1, 2, 3 ],
                [ 1, 1, 4, 3 ] ]
    assert(isBoxy(board3) == False) # 1 is not boxy

    board4 =  [ [ 0, 3, 3, 3 ],
                [ 0, 3, 9, 3 ],
                [ 1, 3, 3, 3 ] ]
    assert(isBoxy(board4) == False) # 3 is not boxy (due to the 9)

    board5 =  [ [ 1, 1, 2, 2 ],
                [ 1, 1, 5, 5 ],
                [ 5, 7, 5, 5 ] ]
    assert(isBoxy(board5) == False) # 5 is not boxy (see bottom-left corner)
    print('Passed!')

def main():
    testIsBoxy()

main()