# -*- coding: utf-8 -*-
"""Level 3 isKnightsTour.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GFIat3lb9SqyJrdtUG2LmfBM_FwuoP7d

Background: Knights in chess move in “L” shapes. One move
 consists of 2 squares in one direction and 1 square in another
 direction. For example, a knight could move 1 square right and 2 squares up,
 or 1 square down and 2 squares left, etc.




 A "knight's tour" is a sequence of legal knight moves
 such that the knight visits every square exactly once.
 We will represent a possible knight's tour as an NxN list of the integers
 from 1 to N2 listing the positions in order that the knight occupied on the tour.
 If it is a legal knight's tour, then all the numbers from 1 to N2 will be included.




 With this in mind, write the function `isKnightsTour(board)` which takes
 a 2d list of integers and returns `True` if it represents a legal knight's
 tour, and `False` otherwise.




 For example, below is a legal 5x5 knight's tour as the 2d list includes every number from
 1 to 52 (25\), where each of the moves from 1 to 25 is a legal knight move.

```

[[1, 6, 15, 10, 21],
[14, 9, 20, 5, 16],
[19, 2, 7, 22, 11],
[8, 13, 24, 17, 4],
[25, 18, 3, 12, 23]]

```
"""

def isKnightsTour(board):
    n = len(board)
    if n == 0 or any(len(row) != n for row in board):
        return False

    # Check if all numbers from 1 to n^2 are present
    expected_numbers = set(range(1, n * n + 1))
    actual_numbers = {num for row in board for num in row}
    if expected_numbers != actual_numbers:
        return False

    # Possible knight moves
    knight_moves = [(2, 1), (2, -1), (-2, 1), (-2, -1),
                    (1, 2), (1, -2), (-1, 2), (-1, -2)]

    # Create a mapping from number to its position
    position = {}
    for r in range(n):
        for c in range(n):
            position[board[r][c]] = (r, c)

    # Check each move in the tour
    for i in range(1, n * n):
        r1, c1 = position[i]
        r2, c2 = position[i + 1]
        if not any((r1 + dr == r2 and c1 + dc == c2) for dr, dc in knight_moves):
            return False

    return True

def testIsKnightsTour():
    print('Testing isKnightsTour()...', end='')
    board = [[1, 6, 15, 10, 21],
             [14, 9, 20, 5, 16],
             [19, 2, 7, 22, 11],
             [8, 13, 24, 17, 4],
             [25, 18, 3, 12, 23]]
    assert(isKnightsTour(board) == True)

    board1 = [[1, 30, 33, 22, 25, 12],
              [34, 21, 26, 13, 32, 23],
              [29, 2, 31, 24, 11, 14],
              [20, 35, 18, 27, 8, 5],
              [17, 28, 3, 6, 15, 10],
              [36, 19, 16, 9, 4, 7]]
    assert(isKnightsTour(board1) == True)

    board2 = [[2, 5, 9],
              [7, 8, 3],
              [4, 1, 6]]
    assert(isKnightsTour(board2) == False)

    board3 = [[2, 5, 0],
              [7, 0, 3],
              [4, 1, 6]]
    assert(isKnightsTour(board3) == False)

    board4 = [[1, 4, 7, 10],
              [12, 9, 2, 5],
              [3, 6, 11, 8]]
    assert(isKnightsTour(board4) == False)
    print('Passed!')

def main():
    testIsKnightsTour()

main()