# -*- coding: utf-8 -*-
"""Level 3 betterWordSearch3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12M6EIF3aPhtfNAPwDl7b9CY10gIX9yJf

Background: This version of `wordSearch(board, cell)` also builds on
 `betterWordSearch1`. Now we allow for
 wraparound. That is, as we head off the board on one edge, we re\-enter
 the board on the opposite edge.




 For example:

```
board = [ [ 'g', 'd', 'o' ],
          [ 'c', 't', 'a' ],
          [ 'w', 'a', 't' ],
          [ 'r', 'a', 'b' ] ]

```

 The word 'dog' is on this board, because as we head off the board to the
 right, we re\-enter on the left and keep going. Thus:

```
assert(wordSearch(board, 'dog') ==
    "'dog' is at (0, 1) heading right")
assert(wordSearch(board, 'cat') ==
    "'cat' is at (1, 0) heading left")
assert(wordSearch(board, 'tag') ==
    "'tag' is at (2, 2) heading down-left")
assert(wordSearch(board, 'tact') ==
    "'tact' is at (1, 1) heading right")
assert(wordSearch(board, 'boat') ==
    "'boat' is at (3, 2) heading down")
assert(wordSearch(board, 'tow') == "'tow' not found")

```





 With this in mind, write the function `wordSearch(board, word)`, which takes
 a rectangular 2d list `board`, where each value in
 the board is a single lowercase letter, and `word`,
 which is a string of lowercase letters, and returns a string as outlined above.
"""

def wordSearch(board, word):
    return 42

def testWordSearch():
    print('Testing wordSearch()...', end='')
    board = [ [ 'g', 'd', 'o' ],
              [ 'c', 't', 'a' ],
              [ 'w', 'a', 't' ],
              [ 'r', 'a', 'b' ] ]
    assert(wordSearch(board, 'dog') == "'dog' is at (0, 1) heading right")
    assert(wordSearch(board, 'cat') == "'cat' is at (1, 0) heading left")
    assert(wordSearch(board, 'tag') == "'tag' is at (2, 2) heading down-left")
    assert(wordSearch(board, 'tact') == "'tact' is at (1, 1) heading right")
    assert(wordSearch(board, 'boat') == "'boat' is at (3, 2) heading down")
    assert(wordSearch(board, 'tow') == "'tow' not found")
    assert(wordSearch(board, 'www') == "'www' not found")
    print('Passed!')

def main():
    testWordSearch()

main()