# -*- coding: utf-8 -*-
"""Level 3 isLatinSquare.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xxWYqMQO-bgK3-pbiQ8HVsbFC0jRm_T4

#### Problem Writeup



 Background: A `list` `L` is a Latin Square if it has the following
 properties:
 1. `L` is 2d, non\-empty, and square (it has the same number of rows
 and columns).
2. `L` contains `n` unique integers, where `n` is the number of
 rows (and because `L` is square, `n` is also the number of columns).
3. Each of the `n` integers appears exactly once in each row
 and exactly once in each column of `L`. This restriction does
 not apply to diagonals.






 For example, the following list is a Latin Square because it is a
 square list, and the numbers 1, 5, and 7 appear exactly once in each
 row and once in each column:

```

[[5, 7, 1],
 [1, 5, 7],
 [7, 1, 5]]
```


 However, the following list is not a Latin Square, because 7 appears
 twice in column 2:

```

[[1, 5, 7],
 [5, 1, 7],
 [1, 7, 5]]
```





 With this in mind, write the function `isLatinSquare(L)`
 which takes a `list` `L`, which may or may not be a 2d list,
 and if it is a 2d list it may or may not be square, and returns
 `True` if `L` is a Latin Square and `False`
 otherwise.



#### Guided Solution
"""

def isLatinSquare(L):
    return 42

def testIsLatinSquare():
    print('Testing isLatinSquare()...', end='')
    L = [[5, 7, 1],
         [1, 5, 7],
         [7, 1, 5]]
    assert(isLatinSquare(L) == True)
    # Verify that the function is non-mutating
    assert(L == [[5, 7, 1],
                 [1, 5, 7],
                 [7, 1, 5]])

    L = [[1, 5, 7],
         [5, 1, 7],
         [1, 7, 5]]
    assert(isLatinSquare(L) == False)

    L = [[1, 2, 3],
         [3, 1, 2],
         [4, 3, 1, 2]]
    assert(isLatinSquare(L) == False)

    L = [[0, 1],
         [1, 0]]
    assert(isLatinSquare(L) == True)

    L = [[1, 4],
         [2, 1]]
    assert(isLatinSquare(L) == False)

    L = [1, 2, 3]
    assert(isLatinSquare(L) == False)

    L = [[1]]
    assert(isLatinSquare(L) == True)
    print('Passed!')

def main():
    testIsLatinSquare()

main()