# -*- coding: utf-8 -*-
"""Level 3 makeEdits.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10_tJJfOU3yWCR_-BUzcCKgX7uU5dDzL8

Background: Say we have this 2d list `M`:

```

M = [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]
```


 Also, we have this list of strings describing non\-mutating
 edits to make on `M`:

```

E = ['swap row 0 and row 1',
     'swap col 1 and col 2',
     'swap row 0 and row 2']
```


 To make the first edit, we swap row 0 and row 1 on the original
 list, to get:

```

[[4, 5, 6],
 [1, 2, 3],
 [7, 8, 9]]
```


 To make the second edit, we swap col 1 and col 2 on that list,
 to get:

```

[[4, 6, 5],
 [1, 3, 2],
 [7, 9, 8]]
```


 Finally, to make the last edit, we swap row 0 and row 2 on that
 list, to get:

```

[[7, 9, 8],
 [1, 3, 2],
 [4, 6, 5]]
```





 With this in mind, write the function `makeEdits(M, E)`, which
 takes a rectangular (but not necessarily square) 2d list `M` and a 1d list
 of edits `E`, and non\-mutatingly returns the 2d list that results
 from making the edits in `E` on `M`.




 You may assume that all the edits are of the form described above,
 and always contain legal indexes. Note that the list can be larger
 than 10x10, so the rows or columns you are supposed to swap are not
 necessarily one digit numbers.




 Hints:
 1. You may want to use `s.split()`.
2. You may want to use `copy.deepcopy(M)`.
"""

import copy

def makeEdits(M, E):
    return 42

def testMakeEdits():
    print('Testing makeEdits()...', end='')
    M = [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]
    E = ['swap row 0 and row 1',
        'swap col 1 and col 2',
        'swap row 0 and row 2']
    R = [[7, 9, 8],
        [1, 3, 2],
        [4, 6, 5]]
    assert(makeEdits(M, E) == R)

    M = [[1, 2, 3, 4],
        [5, 6, 7, 8]]
    E = ['swap row 0 and row 1',
        'swap row 1 and row 0']
    R = [[1, 2, 3, 4],
        [5, 6, 7, 8]]
    assert(makeEdits(M, E) == R)

    M = [[1, 2, 3, 4],
        [5, 6, 7, 8]]
    E = ['swap col 0 and col 1',
        'swap row 1 and row 1',
        'swap col 3 and col 0']
    R = [[4, 1, 3, 2],
        [8, 5, 7, 6]]
    assert(makeEdits(M, E) == R)

    M = [[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]]
    E = ['swap col 0 and col 10']
    R = [[11, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1, 12]]
    assert(makeEdits(M, E) == R)

    # Verify that the function is non-mutating
    M = [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]
    E = ['swap row 0 and row 1',
        'swap col 1 and col 2',
        'swap row 0 and row 2']
    makeEdits(M, E)
    assert(M == [[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
    assert(E == ['swap row 0 and row 1',
                'swap col 1 and col 2',
                'swap row 0 and row 2'])
    print('Passed!')

def main():
    testMakeEdits()

main()