# -*- coding: utf-8 -*-
"""2 - Lists.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IADbjyF29kJ0UVw0yPZfgI58gdN1NUg6

<font size="1" color="#AAA">Python Fundamentals &copy; David Kosbie</font>  

# Lists
We now cover *lists*, one of the most useful and important
data structures in Python.

## List Fundamentals

### Definition

A *list* is a *sequence* (an ordered collection)
of values (or *elements*) of any type.

Lists are printed as comma-separated values inside brackets (like `[1, 2, 3]`).

### Creating Lists

#### An Empty List
An *empty list* is a list with no elements. It is still a list.
"""

L = [ ]  # An empty list with no values
print(L)
print(type(L))

"""#### A Non-Empty List
Just place comma-separated elements inside brackets ([ ]).
"""

L = [ 1, 2, 3 ]
print(L)

"""#### A Variable-Length List
Use the `*` operator to create a variable-length list.
"""

n = 10
L = [ 0 ] * n # You can change 0 to any value
print(L)

"""#### Lists with Different Types
Lists can contain any type of value.
"""

L = [ 42, True, 3.14, 'Amazing' ]
print(L)

"""### Indexing and Slicing Lists
Because lists are sequences, as are strings,
indexing and slicing work the same for lists and strings.
"""

# List indexing works just like string indexing:
primes = [ 2, 3, 5, 7, 11, 13, 17 ]
print(primes[0])
print(primes[1])
print(primes[-1])
print(type(primes[0]))

# List slicing works just like string slicing:
primes = [ 2, 3, 5, 7, 11, 13, 17 ]
print(primes[2:4])
print(primes[:3])
print(primes[5:])
print(type(primes[2:4]))

"""An *empty slice* is a slice of length 0.  It is still a list."""

L = [ 2, 4, 6 ]
M = L[3:]
print(M)
print(len(M))
print(type(M))

"""### List Mutability Basics
While strings are immutable, lists are *mutable*, meaning we can
change (or mutate) lists.

It is important that you understand this well.

#### Lists are Mutable
For example, for a list L, we *can* change the value of L[i].
"""

L = [ 2, 4, 6, 8 ]
L[0] = 42
print(L)

"""#### List Aliases

Before we proceed, we must briefly cover how list aliases work.

As we already saw, variables are *aliases* if they are set to the same Python object.  Two variables set to the same list are *list aliases*.

This is how we create a list alias:
<pre>
    L = [ 1, 2 ]
    M = L  # Now L and M are aliases (set to the same list)
</pre>

If we mutate a list, all the aliases reflect the change.
"""

L = [ 1, 2 ]
M = L      # Now L and M are aliases
L[0] = 42  # This mutates L
print(L)
print(M)   # Surprised?

"""We use `is` to test if two values are aliases."""

L = [ 1, 2 ]
M = L
print(L == M)
print(L is M)

"""Two lists can be equal but not aliases."""

L = [ 1, 2 ]
M = [ 1, 2 ] # This is NOT an alias.  It is a new list.
print(L == M)
print(L is M)

"""We now can return to discussing list mutability.

#### Testing for Mutation
As we discuss below, some operators and methods mutate a list, and others do not.

For example (again discussed below), the following two lines both add a value
to the list L.  The first line mutates the list, and the second line does not.
<pre>
    L += [ 42 ]    # this mutates L

    L = L + [ 42 ] # this does not mutate L
</pre>

We need an easy way to test if a list was mutated.  In fact, here are two ways.

##### Using id()

Every object in Python has a unique id associated with it.

We use `id(value)` to get the id of a value.

If a list changes, but keeps the same id, then it was mutated.

If a list changes, but has a new id, then it was not mutated.
"""

# Using id() to confirm L was mutated:

L = [ 1, 2 ]
print(L)
print(id(L))

L += [ 3 ]
print(L)
print(id(L)) # did not change, so L was mutated!

# Using id() to confirm L was NOT mutated:

L = [ 1, 2 ]
print(L)
print(id(L))

L = L + [ 3 ]
print(L)
print(id(L)) # changed, so L was NOT mutated!

"""##### Using Aliases
We can test for mutation of L by first creating an alias M.

Then, if L changes:

  * if L was mutated, M will reflect the change.
  
  * if L was not mutated, M will not reflect the change.
"""

# Using an alias to confirm L was mutated:

L = [ 1, 2 ]
M = L
print(L, M)

L += [ 3 ]
print(L, M) # M changed, so L was mutated

# Using an alias to confirm L was NOT mutated:

L = [ 1, 2 ]
M = L
print(L, M)

L = L + [ 3 ]
print(L, M) # M did NOT change, so L was NOT mutated

"""#### Visualizing Aliaes
The [Python Tutor Visualizer](https://pythontutor.com/visualize.html#mode=edit)
is especially useful for *visualizing* aliases.

Paste the following code into the visualizer and step through it carefully.
See how the arrows make it very clear which values are aliases.
"""

# Paste this code into the Python Tutor Visualizer
L = [ 1, 2 ]
M = [ 1, 2 ]
N = L

L.append(3)

print(L)
print(M)
print(N)

"""## List Operators

### Indexing and Slicing
Again, indexing and slicing work the same for both lists and strings.

### The in Operator
`v in L` tests if v is an element in the list L.
"""

L = [ 2, 3, 5 ]
print(2 in L)
print(4 in L)

"""### The not in Operator
`v not in L` tests if v is not an element in the list L.
"""

L = [ 2, 3, 5 ]
print(2 not in L)
print(4 not in L)

"""### Non-Mutating Operators
Non-mutating operators do not change (mutate) a list.

Instead, they create a new list.

#### The + Operator
`L + M` creates a new list of the values in L followed by the values in M.
"""

L = [ 2, 3, 4 ]
M = [ 5, 6 ]
N = L + M
print(N)

"""#### The * Operator
`L * n` creates a new list of with n successive copies of the values in L.
"""

L = [ 2, 3, 4 ]
M = L * 3
print(M)

"""### Mutating Operators
Mutating operators change (mutate) a list.

They do NOT create a new list.

#### The += Operator
`L += M` changes (mutates) L by adding the values in M to it.
"""

L = [ 2, 3, 4 ]
L += [ 5, 6 ]
print(L)

"""#### The *= Operator
`L *= n` changes (mutates) L by adding copies of the values in L to itself.
"""

L = [ 2, 3, 4 ]
L *= 3
print(L)

"""## List Methods

### Non-Mutating Methods

#### L.index
`L.index(v)` returns the index of the first occurrence of v in L.
"""

L = [ 2, 3, 5, 7 ]
print(L.index(5))

"""If v is not in L, L.index(v) crashes."""

L = [ 2, 3, 5, 7 ]
print(L.index(42)) # crashes (42 is not in the list)

"""#### No L.find(v)
Regarding L.find(v):

  * We saw that a string s has two similar methods, s.index(t) and s.find(t).

    * s.find(t) is preferred, since it does not crash if t is not in s.

  * We just saw that lists have L.index(v), which works similarly to s.index(t).

  * Unfortunately, there is no L.find(v).  So for lists, we have to use L.index(v).
  
However:

  * We can write our own find function for lists.
"""

# Our own find(L, v) function for lists, since L.find(v) does not exist.

def find(L, v):
    for i in range(len(L)):
        if L[i] == v:
            return i
    return -1

L = [ 7, 11, 13, 17 ]
print(find(L, 13))
print(find(L, 15)) # works

print(L.index(13))
print(L.index(15)) # crashes

"""#### L.count
`L.count(v)` returns the number of times v occurs in L.
"""

L = [ 4, 5, 4, 5, 4 ]
print(L.count(4))

"""### Mutating Methods
Note: except for pop, list mutating methods return None.

#### insert
`L.insert(i, v)` inserts v at index i.

After this, the old value at L[i] is at L[i+1].
"""

L = [ 2, 3, 5 ]
L.insert(2, 4) # insert 4 at L[2]
print(L)
print(L[2]) # we inserted the 4 here
print(L[3]) # the 5 moved over one

"""#### append
`L.append(v)` adds (appends) v to the end of L.
"""

L = [ 2, 3, 5 ]
L.append(7)
print(L)

"""#### extend
`L.extend(M)` adds all the values in the list M to the end of L.
"""

L = [ 2, 3, 5 ]
L.extend([7, 9])
print(L)

"""Note:

  * Use L.append(v) to add a single value to a list.
  
  * Use L.extend(M) to add a list of values to a list.

#### pop
`L.pop(i)` removes the ith element in L and returns that value.

This is the only list mutating method that does not return None.
"""

L = [ 2, 3, 5, 7 ]
x = L.pop(1)
print(x)
print(L)

"""`L.pop()` removes the *last* element from L and returns that value."""

L = [ 2, 3, 5, 7 ]
x = L.pop()
print(x)
print(L)

"""#### remove
`L.remove(v)` removes the first occurrence of the value v from L.
"""

L = [ 2, 3, 4, 2, 3 ]
L.remove(3)
print(L)

"""Note that L.pop(i) takes an *index* i, and L.remove(v) takes a *value* v."""

L = [ 2, 3, 4, 5 ]
L.pop(2)
print(f'After L.pop(2), L = {L}')

# Do this again, but with L.remove:
L = [ 2, 3, 4, 5 ]
L.remove(2)
print(f'After L.remove(2), L = {L}')

"""#### clear
`L.clear()` removes every value from L.
"""

L = [ 2, 3, 4 ]
L.clear()
print(L)

"""#### reverse
`L.reverse()` reverses the order of values in L.
"""

L = [ 2, 3, 4, 5 ]
L.reverse()
print(L)

"""#### sort
`L.sort()` sorts the values in L from smallest to largest.
"""

L = [ 3, 5, 2, 4 ]
L.sort()
print(L)

"""`L.sort(reverse=True)` sorts the values in L from largest to smallest."""

L = [ 3, 5, 2, 4 ]
L.sort(reverse=True)
print(L)

"""## List-Related Functions

### len
`len(L)` returns the length of L (the number of elements in L).
"""

print(len([2, 4, 6]))
print(len([2]))
print(len([ ])) # the empty list

"""### min
`min(L)` returns the smallest value in L.
"""

print(min([4, 5, 1, 6, 2, 3]))
print(min(['this', 'works', 'over', 'strings', 'too!'])) # first alphabetically

"""### max
`max(L)` returns the largest value in L.
"""

print(max([4, 5, 1, 6, 2, 3]))
print(max(['this', 'works', 'over', 'strings', 'too!'])) # last alphabetically

"""### sum
`sum(L)` returns the sum of the values in L.
"""

print(sum([2, 3, 4]))
print(sum([2, 3, 4.5]))
print(sum([ ] )) # surprised?

"""### any
`any(L)` returns True if any value in L is True.
"""

print(any([False, False, False, False, False]))
print(any([False, False, False, True, False]))

"""Actually, `any(L)` works with truthy and falsy values.

  * For a list of ints, it returns True if any of the ints is non-zero.
  
  * For a list of strings, it returns True if any of the strings is not empty.
"""

print(any([0, 0, 0, 0, 0]))
print(any([0, 0, 0, 42, 0]))

print(any(['', '', '', '']))
print(any(['', '', 'wow', '']))

"""### all
`all(L)` returns True if all the values in L are True (or truthy).
"""

print(all([True, True, True, False, True]))
print(all([True, True, True, True, True]))

"""### sorted
`sorted(L)` returns a new sorted list, from smallest to largest.

This is very similar to `L.sort()`, but it is non-mutating.
"""

L = [ 3, 5, 2, 4 ]
M = sorted(L)
print(L)
print(M)

"""`sorted(L, reverse=True)` sorts the values in L from largest to smallest."""

L = [ 3, 5, 2, 4 ]
M = sorted(L, reverse=True)
print(L)
print(M)

"""### reversed
`list(reversed(L))` returns a new list with the values of L in reverse.
"""

L = [ 2, 3, 4, 5 ]
M = list(reversed(L))
print(M)

"""Note that to get a new list, you must use `list(reversed(L))` and not just `reversed(L)`."""

L = [ 2, 3, 4, 5 ]
M = reversed(L) # This calls reversed(L) instead of list(reversed(L))
print(M)        # Surprised?

"""### copy.copy
`copy(L)` returns a *copy* of L.  That is, a new list of the same length
and with the same values in the same order.

Remember to import copy first!
"""

import copy # don't forget this!

L = [ 2, 3, 4 ]
M = copy.copy(L)
print(M)

"""A copy is not an alias.  So changes to the original will not be
reflected in the copy.
"""

import copy

L = [ 2, 3, 4 ]
M = copy.copy(L)

print(L == M) # copies are equal
print(L is M) # but copies are not aliases

L[0] = 42

print(L) # L changed
print(M) # but the copy did not change

"""## Looping Over Lists
We loop over lists in the same way that we loop over strings.

### Looping over Values
We use `for v in s` to loop the variable v over each value
in the list L.
"""

L = [ 2, 3.14, 'yes!' ]
for v in L:
    print(f'The next value is: {v}')

"""### Looping over Indexes
We use `for i in range(len(L))` to loop the variable i over each valid *index*
of the list L.

Then we use `L[i]` to access the ith value in L.
"""

L = [ 2, 3.14, 'yes!' ]
for i in range(len(L)):
    v = L[i]
    print(f'Value {i} is {v}')

"""### Reverse Looping over Indexes
We use `for i in range(len(L)-1, -1, -1)` to loop the variable i
*in reverse order* over each valid index of L.
"""

L = [ 2, 3.14, 'yes!' ]
for i in range(len(L)-1, -1, -1):
    v = L[i]
    print(f'Value {i} is {v}')

"""## List Comprehensions
A *list comprehension* compactly and efficiently creates a list by evaluating
an expression for each value in a sequence.

The general form (or *syntax*) of a list comprehension is:
<pre>
    [expression for item in sequence]
</pre>
Here, *item* is the loop variable, and *expression* uses *item*
to compute the values in the list.

For example:
"""

L = [ x**2 for x in range(10) ] # list of the first 10 squares
print(L)

"""We can add a *condition* like so:
<pre>
    [expression for item in sequence if condition]
</pre>

For example:
"""

L = [ x**2 for x in range(10) if x % 2 == 0 ] # just the even squares
print(L)

"""## Mutability and Functions Using Lists

### Parameters are Aliases
Parameters are aliases, so if a parameter is a list, and you change (mutate) that
list, you just changed the caller's list (so be sure that is what you meant to do!).
"""

def f(M):
    print(f'id(M) = {id(M)}') # this is an alias to L!

L = [1, 2]
print(f'id(L) = {id(L)}')
f(L)

"""### Avoid Mutating Parameters
Since parameters are aliases, you should *avoid mutating parameters* unless
that is the well-understood purpose of your function.

For example, never do this:
"""

# This code shows how you should never write a function!
# This unexpectedly mutates (changes) the caller's list.
# This is *extremely* undesirable.

def endsInEven(L):
    if len(L) == 0:
        return False
    else:
        return L.pop() % 2 == 0 # This mutates the caller's list!

L = [ 1, 2, 3 ]
print(L)             # to start...
print(endsInEven(L)) # seems to work
print(L)             # oh no!

"""Instead, find a way to write your function without mutating.
In this case, like so:
"""

# This code fixes the problem from above, and does not mutate its parameter.

def endsInEven(L):
    if len(L) == 0:
        return False
    else:
        return L[-1] % 2 == 0 # Better!

L = [ 1, 2, 3 ]
print(L)             # to start...
print(endsInEven(L)) # seems to work
print(L)             # whew!

"""### Copying Breaks Aliases
Continuing with the previous example, if you really cannot find a better way,
you can always just copy a list.

Once you copy a list, it is not longer an alias, so changes to it do not
affect the original list.
"""

# This code is not optimal (the previous example is preferable),
# but if you really can't do anything else, you can usually
# avoid mutating simply by copying the list.

import copy

def endsInEven(L):
    L = copy.copy(L) # <-- This breaks the alias
    if len(L) == 0:
        return False
    else:
        return L.pop() % 2 == 0 # This no longer mutates the caller's list!

L = [ 1, 2, 3 ]
print(L)             # to start...
print(endsInEven(L)) # seems to work
print(L)             # whew!

"""Note that the solution that uses copy is very wasteful -- it creates an entire
new copy of the list just to pop the last element!

It is much better to just index into the last element, as we saw above.

### Writing Mutating Functions
In general, your functions should not mutate parameters.  However, there are times
when you actually *intend* to do this.  In that case:

  * Give the function a name that makes this as clear as possible.
  
  * Document that the function is mutating, at least in a clear comment.
  
  * If possible, have the function return None.  This is a clear sign
    that a function is mutating.
"""

# This function is mutating! It adds 10 to every value in L.
# This function returns None (by default).
def addTenToEveryValue(L):
    for i in range(len(L)):
        L[i] += 10

L = [ 1, 2, 3 ]
print(L)
print(addTenToEveryValue(L)) # None (the function returns None, as it should)
print(L)

"""## Anti-Pattern: Modifying while Looping
You should avoid modifying a list that you are looping over.
This often causes Python to crash.
"""

# This code does not work!
L = [ 2, 8, 6, 4]
for i in range(len(L)):
    if L[i] > 5:
        L.pop(i) # This modifies the list L inside the loop (and crashes!)
print(L)

"""The problem is that range() is called only once at the start of the loop.
It does not change when the list gets smaller.

A fix for this is to use a while loop without calling range() at all.
"""

# This code works!
L = [ 2, 8, 6, 4]
i = 0
while i < len(L):
    if L[i] > 5:
        L.pop(i)
    else:
        i += 1
print(L) # [2, 4]

"""Note that sometimes we *can* use a for loop, by looping in reverse order.
If you opt for this approach, be sure you thoroughly understand this
(so you know when this approach will not work)!
"""

# This code also works!
L = [ 2, 8, 6, 4]
for i in range(len(L)-1, -1, -1):
    if L[i] > 5:
        L.pop(i)
print(L)

"""Here is a more useful example.  Note that Python does not include a
built-in function that removes all the occurrences of a value from a list.
So this is handy!
"""

# This function modifies L by removing every occurrence of v.
def removeAll(L, v):
    for i in range(len(L)-1, -1, -1):
        if L[i] == v:
            L.pop(i)

L = [ 1, 2, 3, 1, 2, 3, 1, 2, 3 ]
print(L)
print(removeAll(L, 2)) # None (removeAll is mutating and correctly returns None)
print(L) # works!