# -*- coding: utf-8 -*-
"""5 - Additional Topics (Strings and Lists).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GamAKdHX6yjQREAbLo59yiqQBi2Jb1U0

<font size="1" color="#AAA">Python Fundamentals &copy; David Kosbie</font>  

# Additional Topics (Strings and Lists)
Here are some additional topics that are not part of the core curriculum.
However, they are likely to be useful to you in your coding future.
If you are new to Python, you can skip these topics for now and
return later.  For those of you with some Python experience,
you may find some useful concepts here that are new to you.

## More on `==` vs `is`

Some coders confuse `==` and `is`. But these are very different!

  * `x == y` is intuitive.  It basically behaves how you would expect.
  
  * `x is y` is intuitive when you strictly use it to test for *aliases*.
  
    * If x and y are aliases, then `x is y` is True.  Simple.

  * *However*, some coders sometimes use `is` as a test for equality
    (and not alias).  This is a mistake, and it can be very confusing.

For example, see if you can predict what these examples will print:
"""

# See if you can predict the output before running this code.
# Hint: ALL of the examples print True for (x == y).
# Some of this can be surprising:

print('#  x   y  x==y x is y')
# Example 1:
x = y = 256
print(1, x, y, x == y, x is y)

# Example 2:
x = y = 256
x += 1
y += 1
print(2, x, y, x == y, x is y)

# Example 3:
x = y = 257
print(3, x, y, x == y, x is y)

# Example 4:
x = 257
y = 257 + 0
print(4, x, y, x == y, x is y)

"""The bottom line: only use *is* to test for aliases, and nothing else, ever.

## More on F-Strings
Here we cover a bit more about f-strings.

### Field Width
"""

x = 123
print(f'|{x}| No field width')
print(f'|{x:2}| Field width of 2')
print(f'|{x:4}| Field width of 4')
print(f'|{x:6}| Field width of 6')

"""### Leading Zeros"""

x = 123
print(f'|{x:6}| No leading zeros.')
print(f'|{x:06}| With leading zeros.')

"""### Alignment"""

x = 123
print(f'|{x:<6}| Left-aligned.')
print(f'|{x:^6}| Center-aligned.')
print(f'|{x:>6}| Right-aligned.')

"""### Fill"""

x = 123
print(f'|{x:<6}| No fill.')
print(f'|{x:#<6}| Filled with #.')

"""### Leading Sign"""

x = 123
y = -123
print(f'|{x},{y}| No leading sign.')
print(f'|{x:+},{y:+}| With leading sign.')

"""### Grouping"""

x = 123456789
print(f'|{x:}| No grouping.')
print(f'|{x:,}| Comma grouping.')
print(f'|{x:_}| Underscore grouping.')

"""### Binary and Hexadecimal"""

x = 123
print(f'{x} (decimal)')
print(f'{x:b} (binary)')
print(f'{x:x} (hexadecimal lowercase)')
print(f'{x:X} (hexadecimal uppercase)')

"""### Float Precision"""

x = 123.4567
print(f'{x} (no precision)')
print(f'{x:0.1f} (1 digit precision)')
print(f'{x:0.2f} (2 digit precision)')

"""### More
See [here](https://docs.python.org/3/library/string.html#grammar-token-format-spec-width) for
more details.

## Many Ways to Copy a List
In practice, you are likely to see several ways to copy a list.

However, most of these are not very clear, which makes them *disadvised*.

We suggest that you use `copy.copy(L)` to copy a list.

While we do not suggest you use these, you certainly need to understand them,
so we present some of them here.
"""

# Some of the many ways to copy a list:
# Note: this example is best viewed with the Python Visualizer.

L = [ 1, 2, 3 ]

# Some less-obvious ways to make a copy of a list:
M = list(L)
M = L[:]
M = L + [ ]
M = L * 1
M = [v for v in L]

# The next one is clearer, but still not preferred for reasons we will
# cover when we get to 2d lists (looking ahead, basically this only
# works for shallow copies, as there is no L.deepcopy() method):
M = L.copy()

# Here is the preferred way (because it is clear, and more general):
import copy
M = copy.copy(L) # YES!

"""## Sorting with a Key Function

Sorting with a *key function* allows us to customize the sort order.

If we provide a key function, then each value v in the list
is sorted based on key(v).
"""

# Examples of sorting with a key function:

L = [ 'DOGS', 'kitten', 'emu', 'ZEBRA', 'OX' ]

print('1. Standard sort (uppercase first, then lowercase):')
print(sorted(L))

print('\n2. Case-insensitive sort:')
print(sorted(L, key=str.lower))

print('\n3. Sort by element length:')
print(sorted(L, key=len))

print('\n4. Sort by element length, longest first:')
print(sorted(L, key=len, reverse=True))

print('\n5. Sort by second character of each element (case insensitive):')
print(sorted(L, key=lambda v: v[1].lower() if len(v) >= 2 else ''))

# This also works for L.sort:

L = [ 5, -3, 2, -7, 1 ]
L.sort()
print('After standard sort:', L)

L.sort(key=abs)
print('After sort by absolute values:', L)

"""## Timing join vs concat
We can use join or concat to combine a list of strings into a single string.

Let's see which is faster.
"""

import time

n = 10**5 # 100,000
L = [ str(x**2) for x in range(n) ]

# Time using join:
t0 = time.time()
s1 = ','.join(L)
elapsed1 = time.time() - t0

# Time using concat:
t0 = time.time()
s2 = ''
for v in L:
    if s2 != '': s2 += ','
    s2 += v
elapsed2 = time.time() - t0

# Verify they are the same
assert(s1 == s2)

# And report on the times:
print(f'Timing data with a list of {n:,} strings.')
print(f'Time using join:   {elapsed1:.5f}s')
print(f'Time using concat: {elapsed2:.5f}s')
print()
print(f'Result: in this case, join is {round(elapsed2/elapsed1)} times faster than concat!')

"""Results:

  * Combining strings with + is slow.
  
  * Combining strings with join is fast.
  
Conclusions:

  * You can use + to combine just a few strings.
  
  * But to combine a lot of strings, use join.
"""