# -*- coding: utf-8 -*-
"""1 - Strings (Part 2).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HwMwgj9zlovZkMfDHCjeX4eM-s22GzOe

<font size="1" color="#AAA">Python Fundamentals &copy; David Kosbie</font>  

# Strings (Part 2)
We continue to explore strings in more detail.  Here we will revisit some topics we covered in part 1 in more detail, and introduce some new topics.

## More String Operators

### Negative Indexes
We can use *negative indexes* to access characters from the right side of a string,
where s[-1] is the rightmost character.
"""

s = 'abc'
print(s[-1])
print(s[-2])
print(s[-3])

"""Since the last character of a string s is at s[len(s)-1], we see that:

  * s[-1] is the same character as s[len(s)-1]
  
  * s[-2] is the same character as s[len(s)-2]
  
  * and so on
"""

s = 'abc'
print(s[-1], s[len(s)-1])
print(s[-2], s[len(s)-2])
print(s[-3], s[len(s)-3])

"""### Slicing with Out-of-Range Indexes

We have seen that s[i] crashes if `i` is out of range.

This is true for indexing, but not for slicing.

Slices always work even for out-of-range values.
"""

s = 'abc'
print(s[1:100])  # surprised?
print(s[-200:2]) # surprised again?

"""### Empty Slices

If a slice contains no characters, it returns the empty string.
"""

s = 'abc'
print(s[2:2])
print(s[2:2] == '')

"""### Slicing with Steps
Though rare, we can use `s[i:j:k]` to slice a string starting at
index i (inclusive), up to index j (exclusive), stepping by k.
This is similar to how range() works.
"""

s = 'abcdefgh'
print(s[1:7:2])

"""As with range, we can also use negative steps:"""

s = 'abcdefgh'
print(s[7:1:-2])

"""### Reversing a String
We can use negative indexing to reverse a string.
"""

s = 'abcdefgh'
print(s[::-1]) # surprised?

"""Reversing a string s with `s[::-1]` is commonly seen in practice.  Even so,
it can be confusing, so it's best to place this in a well-named function,
like reverseString.  After that, instead of using s[::-1] in your code,
call reverseString(s), which is much clearer.
"""

def reverseString(s):
    return s[::-1]

print(reverseString(s))

"""## More String-Related Functions

#### len, int, and str
We already saw these functions in Strings (Part 1).
"""

print(len('abcd'))

n = int('1234')
print(n, type(n))

s = str(1234)
print(s, type(s))

"""### ord
Every character has a unique Unicode value assigned to it.

We can use `ord(s)` to convert a single-character string into its
Unicode value.
"""

print(ord('A')) # uppercase A is 65
print(ord('a')) # lowercase a is 97
print(ord('0')) # the character '0' (not the int value 0) is 48
print(ord('!')) # exclamation mark is 33
print(ord(' ')) # space is 32

"""The uppercase letters are in the same order alphabetically as in Unicode."""

import string
for letter in string.ascii_uppercase:
    print(f'Unicode for {letter} is {ord(letter)}')

"""The lowercase letters are also in the same order alphabetically as in Unicode."""

import string
for letter in string.ascii_lowercase:
    print(f'Unicode for {letter} is {ord(letter)}')

"""However, all the lowercase letters are after all of the uppercase letters."""

print(ord('a'), ord('Z'))
print(ord('a') > ord('Z')) # surprised?

"""Python uses Unicode values when comparing letters. So all lowercase letters
are greater than all uppercase letters.
"""

print('a' > 'Z') # surprised?

"""### chr
We use `chr(n)` to convert the Unicode value n back into a string of length 1
of the corresponding character.
"""

print(ord('A')) # Unicode for A is 65
print(chr(65))  # So chr(65) returns the string 'A'

"""We see that chr and ord are *inverse functions* -- they undo what the other does.  So:

  * chr(ord(s)) == s, and
  
  * ord(chr(n)) == n
"""

print(ord(chr(63)) == 63)
print(ord(chr(192)) == 192)

print(chr(ord('!')) == '!')
print(chr(ord('+')) == '+')

"""### repr
We use `repr(s)` to get the Python-readable string representation of a value.

This is especially useful when debugging to help us see whitespace
(spaces, tabs, newlines) at the end of a string.
"""

s = 'This has extra spaces at the end.  '
print(s)       # not obvious here
print(repr(s)) # but it is obvious here!

"""`repr` also can be useful for debugging multiline strings
because it displays newline characters as `\n`.
"""

s = '''a
b'''
print(repr(s))

"""### eval (Do Not Use!)
Python includes `eval(expr)` that takes a string which should be a Python
expression, evaluates it, and returns the result.

We discuss eval here, but you should know that its use should be avoided.
Why? Because code using eval is very prone to being hacked.

  * A bad actor might inject their own code into your eval,
    which could then do all kinds of malicious things, like:
    
      * delete all your files, or
      
      * reformat your hard drive, or
      
      * even worse!
    
  * So: *Do not use eval!*
  
However, sadly, eval is used by some coders, so you need to at
least understand how it works.
"""

# This uses eval to show you how it works.
# Do not use eval in your own code!
n = eval('2 * 3') # DO NOT DO THIS!
print(n)
print(type(n))

"""## String Methods

### Character Type Methods
These test if a string s contains only characters of a certain type.

Note that these have some subtleties we will cover in the Additional Topics.

#### s.isalpha
`s.isalpha()` tests if s contains only letters (alphabetics)
"""

print('AbCd'.isalpha())
print('Ab34'.isalpha())

"""#### s.isdigit
`s.isdigit()` tests if s contains only digits.
"""

print('1234'.isdigit())
print('123C'.isdigit())

"""#### s.isalnum
`s.isalnum()` tests if s contains only letters (alphabetics) or digits (numerics).
"""

print('Ab34'.isalnum())
print('Ab??'.isalnum())

"""####  s.islower
`s.islower()` tests if s contains letters and they are all lowercase.
"""

print('abcd'.islower())
print('abCD'.islower())
print('ab12'.islower()) # surprised?
print('1234'.islower()) # surprised?

"""#### s.isupper
`s.isupper()` tests if s contains letters and they are all uppercase.
"""

print('ABCD'.isupper())
print('ABcd'.isupper())
print('AB12'.isupper())
print('1234'.isupper())

"""#### s.isspace
`s.isspace()` tests if s contains only *whitespace* (spaces, tabs, or newlines)
"""

print('  \n'.isspace())
print('   x'.isspace())

"""### String Editing Methods
These methods make edits on a string, returning a new string.

#### s.lower
`s.lower()` converts the letters in s to lowercase, leaving non-letters unchanged.
"""

print('ABC def 123 !!!'.lower())

"""#### s.upper
`s.upper()` converts the letters in s to uppercase, leaving non-letters unchanged.
"""

print('ABC def 123 !!!'.upper())

"""#### s.replace
`s.replace(u, v)` replaces all the occurrences of the string u in s with v,
where u and v are both strings.
"""

print('This is a good example. A really good example!'.replace('good', 'great'))

"""`s.replace(u, v, count)` replaces only the first `count` occurrences of u."""

print('abc abc abc'.replace('a', 'x'))    # replace every a with x
print('abc abc abc'.replace('a', 'x', 1)) # replace just the first a
print('abc abc abc'.replace('a', 'x', 2)) # replace just the first two a's

"""#### s.strip
`s.strip()` removes any leading or trailing whitespace in s.
"""

print(repr('     This is a test!     '.strip()))

"""Leading or trailing newlines are also stripped."""

print(repr('''

Hello!

'''.strip()))

"""Note that `s.strip()` does not remove any internal whitespace in s."""

print(repr('     s   u   r   p   r   i   s   e   d   ?      '.strip()))

"""### Substring Search Methods
These search a string for occurrences of a substring.

#### s.count
`s.count(t)` returns the number of times t occurs in s.
"""

print('abcd abc ab a'.count('bc'))

"""#### s.startswith
`s.startswith(t)` tests if s starts with t.
"""

print('cheerful morning, cheerful day'.startswith('cheer'))
print('cheerful morning, cheerful day'.startswith('morning'))

"""#### s.endswith
`s.endswith(t)` tests if s ends with t.
"""

print('Happy day, sound sleep'.endswith('sleep'))
print('Happy day, sound sleep'.endswith('sound'))

"""#### s.find
`s.find(t)` returns the index where the first t occurs in s,
or -1 if s does not contain t.
"""

print('I am happy if you are happy'.find('happy'))
print('I am happy if you are happy'.find('sad'))

"""`s.find(t, start)` works the same as `s.find(t)` but it
starts checking from the given index.
"""

print('I am happy if you are happy'.find('happy'))
print('I am happy if you are happy'.find('happy', 5)) # surprised?
print('I am happy if you are happy'.find('happy', 6))
print('I am happy if you are happy'.find('sad', 6))

"""#### s.index
`s.index(t)` works the same as `s.find(t)`, only it raises an exception
(crashes) if t is not in s.
"""

# This works just like find:
print('I am happy if you are happy'.index('happy'))

# But this crashes:
print('I am happy if you are happy'.index('sad')) # crash: substring not found

"""#### s.rfind
`s.rfind(t)` works the same as `s.find(t)` but it searches from the *right*.
So it finds the *last* occurrence of t in s.
"""

print('I am happy if you are happy'.rfind('happy'))

"""### Splitting Methods
These methods split a string up into parts that we can loop over.

Since these return lists, we will cover these methods after lists.

## String Literals
A string value in quotes is called a *string literal*.

#### Kinds of Quotes
We can use several different kinds of quotes in strings:

  * single quotes ('like this')
  
  * double quotes ("like this")
  
  * triple single quotes ('''like this''')
  
  * triple double quotes ('''like this''')
"""

print('This uses single quotes.')
print("This uses double quotes.")
print('''This uses triple single quotes.''')
print("""This uses triple double quotes.""")

"""Both types of triple quotes allow newlines in the string."""

print('''
This is
a multiline string.''')

print("""
And this is
another multiline string.""")

"""Python crashes if we put single quotes in a single-quoted string."""

# Error: placing a single-quote inside a single-quoted string:
#print('This can't work!')

"""We can fix this by using double-quotes or by escaping the single-quote with
a backslash (`\`).
"""

print("This doesn't crash!")
print('And this also doesn\'t crash!')

"""### Escape Sequences
We use `\` (backslash) to include special characters in strings.

  * These are called *escape sequences*.
  
  * While we type them with two characters, escape sequences count as just a single character
    in the string.

#### \n
`\n` is a newline character.
"""

print('abc\ndef')

"""Again, escape sequences count as just one character."""

print(len('abc\ndef'))

"""#### \t
`\t` is a tab character.
"""

print('abc\tdef')
print('ab\tcdef')

"""#### \\'
`\'` is the single-quote character.
"""

print('You don\'t have to use double-quotes here!')

"""#### \\"
`\"` is the double-quote character.
"""

print("And I quote: \"You can do this in double-quotes!\"  Amazing!")

"""#### \\\\
`\\` is the backslash character.
"""

print('This is a backslash: \\')

"""## String Constants

### string.ascii_lowercase
`string.ascii_lowercase` contains all the lowercase letters (in order).
"""

import string
s = string.ascii_lowercase
print(s)

"""### string.ascii_uppercase
`string.ascii_uppercase` contains all the uppercase letters (in order).
"""

import string
s = string.ascii_uppercase
print(s)

"""### string.ascii_letters
`string.ascii_letters` contains all the lowercase letters followed by
all the uppercase letters (in order).
"""

import string
s = string.ascii_letters
print(s)

"""### string.digits
`string.digits` contains all the digits (in order).
"""

import string
s = string.digits
print(s)

"""### string.punctuation
`string.punctuation` contains all the punctuation characters
(in order according to their Unicode values).
"""

import string
s = string.punctuation
print(s)

"""### string.whitespace
`string.whitespace` contains all the whitespace characters
(in order according to their Unicode values).

These include space, tab, newline, and a few more obscure characters.
"""

import string
s = string.whitespace
print(s)
print(repr(s)) # why do this?

"""### string.printable
`string.printable` contains all the *printable* characters.
That is, all the digits, letters, punctuation, and whitespace.
"""

import string
s = string.printable
print(s)
print(repr(s))

"""## Strings and Aliases

Values in Python are also called *objects*.

Variables are *aliases* if they are set to the same Python object.

Since strings are immutable, changing a string does not change aliases.
"""

s = 'abc'
t = s      # now s and t are aliases, both set to the same string
s += 'def' # we just changed s
print(s)
print(t)   # surprised?