# -*- coding: utf-8 -*-
"""3 - Combining Strings and Lists.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18fWtEcLH-AuCcrlG0BpMHqAIIcBXOh1V

<font size="1" color="#AAA">Python Fundamentals &copy; David Kosbie</font>  

# Combining Strings and Lists
This note covers topics that involve both strings and lists working together.

#### s.split
`s.split(t)` returns a list of substrings of s using t as the *separator*.
"""

fruits = 'apples,bananas,cherries,dates'
L = fruits.split(',')
print(L)

"""We often just loop directly over the result without storing it in a variable."""

fruits = 'apples,bananas,cherries,dates'
for fruit in fruits.split(','):
    print(f'The next fruit is {fruit}')

"""`s.split()` with no argument returns a list of substrings using any whitespace
(spaces, tabs, newlines) as the separator.

It treats any sequence of whitespace as a single separator.
"""

poem = '''\
Celery by Ogden Nash
    Celery, raw
    Develops the jaw,
    But celery, stewed,
    Is more quietly chewed.'''

# We can store the result in a list:
L = poem.split()
print(L)

# Or we can directly loop over the result:
for word in poem.split():
    print(f'The next word is {word}')

"""#### s.splitlines
`s.splitlines()` returns a list containing each line in s.
"""

poem = '''\
Celery by Ogden Nash
    Celery, raw
    Develops the jaw,
    But celery, stewed,
    Is more quietly chewed.'''

# Again, we can store the result in a list:
L = poem.splitlines()
print(L)

# Or we can directly loop over the result:
for line in poem.splitlines():
    print(f'The next line is {line}')

"""#### Using splitlines with split
When we have multiline data where each line is comma-separated,
we use splitlines to access each line, and split to access each value
within a line.
"""

data = '''\
2,7,4
3,8
1,0,6,5'''

for line in data.splitlines():
    lineTotal = 0
    for value in line.split(','):
        lineTotal += int(value)
    print(f'line total: {lineTotal}')

"""## Converting a String to a List
The splitting methods convert a string to a list.  We can also use
`list(s)` to create a list of every character in s.
"""

s = 'Amazing!'
L = list(s)
print(L)

"""## Converting a List to a String
`t.join(L)` converts the list L to a string, where each string in L is
separated by the string t (called the *separator*).
"""

L = ['apples', 'bananas', 'cherries']
print(L)
s = ','.join(L)
print(s)

"""Note that t.join(L) crashes if any value in L is not a string."""

L = [ 'apples', 42, 3.14 ]
print(L)
s = ','.join(L) # this crashes
print(s)

"""We can fix this with a list comprehension that first converts every value
in L to a string.
"""

L = [ 'apples', 42, 3.14 ]
print(L)
s = ','.join([str(v) for v in L]) # this works!
print(s)
print(type(s))