# -*- coding: utf-8 -*-
"""4 - Worked Examples (Strings and Lists).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GZowwFJpFyNdNmsBrSK7iXvR-jPCtdHU

<font size="1" color="#AAA">Python Fundamentals &copy; David Kosbie</font>  

# Worked Examples (Strings and Lists)
This notebook contains examples for you to review before you work on this section's exercises.
Watch the video solutions closely, then be sure you can reproduce the solutions
on your own!

Note: to help you focus on the materials we are currently covering,
you should resist using concepts we have not yet covered. For example,
here you should resist using 2d lists, sets, or dicts yet
(even if you already know them well).

## Problem Statements
This section contains the problem statements and starter code.
Watch the accompanying video, then try to solve the problems
yourself.  If needed, you can refer to the sample solutions below.

### smallestDifference
Write the function smallestDifference(L) which takes a list L of integers and returns the smallest absolute difference between any two numbers in the list. If the list has fewer than two elements, return -1.

For example, smallestDifference([19, 2, 83, 6, 27]) == 4, since the two closest numbers in the list are 2 and 6, and their difference is 4.
"""

def smallestDifference(L):
    pass

def testSmallestDifference():
    print('Testing smallestDifference()...', end='')
    assert(smallestDifference([19,2,83,6,27]) == 4)
    assert(smallestDifference([-2,-5,7,15]) == 3)
    assert(smallestDifference([2,3,5,9,9]) == 0)
    assert(smallestDifference([]) == -1)
    assert(smallestDifference([0]) == -1)
    print('Passed!')

def main():
    testSmallestDifference()

main()

"""### Caesar Cipher

*Background:* To shift a letter by n, you use the letter that is n characters after it in the alphabet. For example:

  * 'a' shifted by 3 is 'd'.

  * 'd' shifted by 2 is 'f'.

Once we reach the end of the alphabet, we wrap back around to the beginning. For example:

  * 'z' shifted by 1 is 'a'.
  
  * 'x' shifted by 4 is 'b'.
  
A *Caesar Cipher* is a simple cipher that takes a message (a string) and a shift (an integer), and shifts each letter in the message by shift characters.

For example, a Caesar Cipher of the message 'I like zoos!' with a shift of 2 returns 'K nkmg bqqu!'.

Note:

  * We did not shift non-letters, we just used them unmodified.
  
  * We preserved case, so uppercase letters are shifted to uppercase, and lowercase letters are shifted to lowercase.

With this in mind, write the function encodeCaesarCipher(msg, shift) that performs a Caesar Cipher on msg, shifting each letter by shift characters. You are guaranteed that msg is a string, and that shift is a possibly-negative integer.  For example:

  * encodeCaesarCipher('Zebra', 2) == 'Bgdtc'
  
  * encodeCaesarCipher('Zebra', -2) == 'Xczpy'

Also write the function decodeCaesarCipher(encodedMsg, shift) that takes a message that has been encoded using a Caesar Cipher with the given shift and returns the decoded message. For example:

  * decodeCaesarCipher('Bgdtc', 2) == 'Zebra'
  
  * decodeCaesarCipher('Xczpy', -2) == 'Zebra'
  
Notice that the decode function undoes what the encode function does. That is, for any msg and any shift:

  * decodeCaesarCipher(encodeCaesarCipher(msg, shift)) == msg

That, after all, is the entire point of using a cipher. The sender uses the encode
function to send an encoded message, then the recipient uses the decode
function to retrieve the original plaintext (unencoded) message.

Hint: Once you have written encodeCaesarCipher(), you can write decodeCaesarCipher() in just a couple lines of code.
"""

def encodeCaesarCipher(msg, shift):
    pass

def decodeCaesarCipher(encodedMsg, shift):
    pass

def testEncodeCaesarCipher():
    print('testing encodeCaesarCipher()...', end='')
    assert(encodeCaesarCipher('I like zoos!', 2) == 'K nkmg bqqu!')
    assert(encodeCaesarCipher('Zebra', 2) == 'Bgdtc')
    assert(encodeCaesarCipher('Zebra', -2) == 'Xczpy')
    assert(encodeCaesarCipher('I love C3PO!', -7) == 'B ehox V3IH!')
    assert(encodeCaesarCipher('Carpe Diem', 63) == 'Nlcap Otpx')
    assert(encodeCaesarCipher('', 13) == '')
    print('Passed!')

def testDecodeCaesarCipher():
    print('testing decodeCaesarCipher()...', end='')
    assert(decodeCaesarCipher('J mjlf appt!', 1) == 'I like zoos!')
    assert(decodeCaesarCipher('Bgdtc', 2) == 'Zebra')
    assert(decodeCaesarCipher('Xczpy', -2) == 'Zebra')
    assert(decodeCaesarCipher('B ehox V3IH!', -7) == 'I love C3PO!')
    assert(decodeCaesarCipher('Nlcap Otpx', 63) == 'Carpe Diem')
    assert(decodeCaesarCipher('', 13) == '')
    print('Passed!')

def main():
    testEncodeCaesarCipher()
    testDecodeCaesarCipher()

main()

"""<pre>

</pre>
<hr>

## Sample Solutions
This section contains sample solutions to these exercises.

Note that there are many good ways to solve every problem.  These are just
one way of doing so.  If you found another good approach, that's fine!

Also, these may not even exactly match the solutions in the accompanying
videos.  That's fine. Again, there are many good solutions to
most problems.

Finally, while you are strongly encouraged to review these (that's
why we are providing them to you, after all), we recommend that you
try to get to the point where you can solve the problems above without
referring to the video or these sample solutions.  You can do it!

### smallestDifference
Write the function smallestDifference(L) which takes a list L of integers and returns the smallest absolute difference between any two numbers in the list. If the list has fewer than two elements, return -1.

For example, smallestDifference([19, 2, 83, 6, 27]) == 4, since the two closest numbers in the list are 2 and 6, and their difference is 4.
"""

def smallestDifference(L):
    if len(L) < 2:
        return -1
    smallest = None
    for i in range(len(L)):
        for j in range(i+1, len(L)):
            difference = abs(L[i] - L[j])
            if (smallest == None) or (difference < smallest):
                smallest = difference
    return smallest

def testSmallestDifference():
    print('Testing smallestDifference()...', end='')
    assert(smallestDifference([19,2,83,6,27]) == 4)
    assert(smallestDifference([-2,-5,7,15]) == 3)
    assert(smallestDifference([2,3,5,9,9]) == 0)
    assert(smallestDifference([]) == -1)
    assert(smallestDifference([0]) == -1)
    print('Passed!')

def main():
    testSmallestDifference()

main()

"""### Caesar Cipher

*Background:* To shift a letter by n, you use the letter that is n characters after it in the alphabet. For example:

  * 'a' shifted by 3 is 'd'.

  * 'd' shifted by 2 is 'f'.

Once we reach the end of the alphabet, we wrap back around to the beginning. For example:

  * 'z' shifted by 1 is 'a'.
  
  * 'x' shifted by 4 is 'b'.
  
A *Caesar Cipher* is a simple cipher that takes a message (a string) and a shift (an integer), and shifts each letter in the message by shift characters.

For example, a Caesar Cipher of the message 'I like zoos!' with a shift of 2 returns 'K nkmg bqqu!'.

Note:

  * We did not shift non-letters, we just used them unmodified.
  
  * We preserved case, so uppercase letters are shifted to uppercase, and lowercase letters are shifted to lowercase.

With this in mind, write the function encodeCaesarCipher(msg, shift) that performs a Caesar Cipher on msg, shifting each letter by shift characters. You are guaranteed that msg is a string, and that shift is a possibly-negative integer.  For example:

  * encodeCaesarCipher('Zebra', 2) == 'Bgdtc'
  
  * encodeCaesarCipher('Zebra', -2) == 'Xczpy'

Also write the function decodeCaesarCipher(encodedMsg, shift) that takes a message that has been encoded using a Caesar Cipher with the given shift and returns the decoded message. For example:

  * decodeCaesarCipher('Bgdtc', 2) == 'Zebra'
  
  * decodeCaesarCipher('Xczpy', -2) == 'Zebra'
  
Notice that the decode function undoes what the encode function does. That is, for any msg and any shift:

  * decodeCaesarCipher(encodeCaesarCipher(msg, shift)) == msg

That, after all, is the entire point of using a cipher. The sender uses the encode
function to send an encoded message, then the recipient uses the decode
function to retrieve the original plaintext (unencoded) message.

Hint: Once you have written encodeCaesarCipher(), you can write decodeCaesarCipher() in just a couple lines of code.
"""

def doShift(c, shift):
    startChar = 'a' if c.islower() else 'A'
    offset = (ord(c) - ord(startChar) + shift) % 26
    return chr(ord(startChar) + offset)

def encodeCaesarCipher(msg, shift):
    result = ''
    for c in msg:
        if (c.isalpha()):
            result += doShift(c, shift)
        else:
            result += c
    return result

def decodeCaesarCipher(encodedMsg, shift):
    return encodeCaesarCipher(encodedMsg, -shift)

def testEncodeCaesarCipher():
    print('testing encodeCaesarCipher()...', end='')
    assert(encodeCaesarCipher('I like zoos!', 2) == 'K nkmg bqqu!')
    assert(encodeCaesarCipher('Zebra', 2) == 'Bgdtc')
    assert(encodeCaesarCipher('Zebra', -2) == 'Xczpy')
    assert(encodeCaesarCipher('I love C3PO!', -7) == 'B ehox V3IH!')
    assert(encodeCaesarCipher('Carpe Diem', 63) == 'Nlcap Otpx')
    assert(encodeCaesarCipher('', 13) == '')
    print('Passed!')

def testDecodeCaesarCipher():
    print('testing decodeCaesarCipher()...', end='')
    assert(decodeCaesarCipher('J mjlf appt!', 1) == 'I like zoos!')
    assert(decodeCaesarCipher('Bgdtc', 2) == 'Zebra')
    assert(decodeCaesarCipher('Xczpy', -2) == 'Zebra')
    assert(decodeCaesarCipher('B ehox V3IH!', -7) == 'I love C3PO!')
    assert(decodeCaesarCipher('Nlcap Otpx', 63) == 'Carpe Diem')
    assert(decodeCaesarCipher('', 13) == '')
    print('Passed!')

def main():
    testEncodeCaesarCipher()
    testDecodeCaesarCipher()

main()