# -*- coding: utf-8 -*-
"""Level 4 isKingsTour.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18mJm9aGtALGMeiTLHy-NPYr83AApkAZs

Note: you may not use `for` or `while` loops in
this exercise. Instead, use recursion.
  
  

Background: In chess, a king can move one square at a time
 in any of the 8 directions (up, down, left, right, up\-left,
 up\-right, down\-left, down\-right).



A "king's tour" is a 2D list of integers representing a valid
 sequence of moves by the king. More specifically, a king's tour
 with dimensions MxN should contain the integers from 1 to M\*N,
 where each integer (other than 1\) can be reached from the previous
 integer via a legal king's move.



For example, this is a king's tour:

```

[[ 3, 5, 1 ],
 [ 4, 2, 6 ]]
```

Notice that we can make a legal king's move to get from: 1 to 2 (down\-left),
2 to 3 (up\-left), 3 to 4 (down), 4 to 5 (up\-right), and 5 to 6 (down\-right).




By contrast, the following 2D list is not a legal king's tour because there is
no legal king's move to get from 5 to 6:

```

[[ 4, 3, 1 ],
 [ 5, 2, 6 ]]

```




With this in mind, use recursion to write the function
`isKingsTour(board)` that takes a 2d list of integers and
returns `True` if it is a legal king's tour and `False`
otherwise.




Hint: You may want to first write a recursive helper function that returns the
`row, col` location of the 1 on the board (or `None`
if there is no 1\). Then, check that the current value (starting at 1\)
has a neighbor one larger than it, and continue checking until you've
hit all the values.




To see some more examples of valid and invalid kings tours, you can revisit
the *8\.10 solveKingsTour* guided exercise. Note that the guided exercise
asks you to generate a king's tour, while this exercise only asks you to
check if a king's tour is legal.
"""

def isKingsTour(board):
    return 42

def testIsKingsTour():
    print('Testing isKingsTour()...', end='')
    board1 = [[3, 5, 1],
              [4, 2, 6]]
    assert(isKingsTour(board1) == True)

    board2 = [[1]]
    assert(isKingsTour(board2) == True)

    board3 = [[2]] # not a valid king's tour because it does not start with 1
    assert(isKingsTour(board3) == False)

    board4 = [[4, 3, 1],
              [5, 2, 6]]
    assert(isKingsTour(board4) == False)
    print('Passed!')

def main():
    testIsKingsTour()

main()