# -*- coding: utf-8 -*-
"""Level 2 encodeSubstitutionCipher_+_decodeSubstitutionCipher.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RxMWXIp0eEkrD0Z3DzHw84gbDerb57yw

Background: A substitution cipher is a cipher that replaces each letter in the
 alphabet with another letter. We keep track of which letter maps to
 which using a key. A key is a jumbled version of the alphabet, where the
 first character replaces A, the second character replaces B, etc. For
 example, using the key `'SQGYFEZXLANKJIMPURDCWTHVOB'` would turn
 `'CAB'` into `'GSQ'`.




 With this in mind, write the function
 `encodeSubstitutionCipher(msg, key)` that takes a message
 and a key as described above and returns the encoded message. You can
 assume that the key uses uppercase letters, but case should be preserved
 when encoding the message. Non\-letter characters should remain
 unchanged. For example, using the key `'SQGYFEZXLANKJIMPURDCWTHVOB'`
 would turn `'Cab Z?'` into `'Gsq B?'`.




 Only after you have written
 `encodeSubstitutionCipher(msg, key)`, write the function
 `decodeSubstitutionCipher(encodedMsg, key)` that takes a
 message that has been encoded with the given key and returns the
 original decoded message.
"""

def encodeSubstitutionCipher(msg, key):
    alphabet = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'
    key_map = {alphabet[i]: key[i] for i in range(26)}
    encoded_msg = []

    for char in msg:
        if char.isupper():
            encoded_msg.append(key_map[char])
        elif char.islower():
            encoded_msg.append(key_map[char.upper()].lower())
        else:
            encoded_msg.append(char)

    return ''.join(encoded_msg)

def decodeSubstitutionCipher(encodedMsg, key):
    alphabet = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'
    key_map = {alphabet[i]: key[i] for i in range(26)}
    decoded_msg = []

    for char in encodedMsg:
        if char.isupper():
            decoded_msg.append(alphabet[key.index(char)])
        elif char.islower():
            decoded_msg.append(alphabet[key.index(char.upper())].lower())
        else:
            decoded_msg.append(char)

    return ''.join(decoded_msg)

def testEncodeSubstitutionCipher():
    print('Testing encodeSubstitutionCipher()...', end='')
    assert(encodeSubstitutionCipher('CAB',
    'SQGYFEZXLANKJIMPURDCWTHVOB') == 'GSQ')
    assert(encodeSubstitutionCipher('Cab Z?',
    'SQGYFEZXLANKJIMPURDCWTHVOB') == 'Gsq B?')
    assert(encodeSubstitutionCipher('Hello, World!',
    'ABCDEFGHIJKLMNOPQRSTUVWXYZ') == 'Hello, World!')
    assert(encodeSubstitutionCipher('42 - 0 = 42',
    'XHNSBMTOPQWGZDCEAVLKJYIURF') == '42 - 0 = 42')
    assert(encodeSubstitutionCipher('', 'XHNSBMTOPQWGZDCEAVLKJYIURF') == '')

def testDecodeSubstitutionCipher():
    print('Testing decodeSubstitutionCipher()...', end='')
    assert(decodeSubstitutionCipher('GSQ',
    'SQGYFEZXLANKJIMPURDCWTHVOB') == 'CAB')
    assert(decodeSubstitutionCipher('Gsq B?',
    'SQGYFEZXLANKJIMPURDCWTHVOB') == 'Cab Z?')
    assert(decodeSubstitutionCipher('Hello, World!',
    'ABCDEFGHIJKLMNOPQRSTUVWXYZ') == 'Hello, World!')
    assert(decodeSubstitutionCipher('42 - 0 = 42',
    'XHNSBMTOPQWGZDCEAVLKJYIURF') == '42 - 0 = 42')
    assert(decodeSubstitutionCipher('', 'XHNSBMTOPQWGZDCEAVLKJYIURF') == '')
    print('Passed!')

def main():
    testEncodeSubstitutionCipher()
    testDecodeSubstitutionCipher()

main()