# -*- coding: utf-8 -*-
"""Level 2 sortEvens.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/107Ft3C2puKUYzalLcHSc-PjMdYosIBG9

Write the function sortEvens(L) that takes a list L of ints and
mutatingly changes the list so that all the evens are in sorted
order (while in the same positions as the original evens),
but all the odds remain unchanged (same positions, same order).
  
  

For example, consider the list L \= \[ 1, 8, 4, 9, \-2, 7 ].
  
  

The evens in this list are 8, 4, and \-2\.
  
  

In sorted order, these are \-2, 4, and 8\.
  
  

So here is the list with the evens in sorted order: \[ 1, \-2, 4, 9, 8, 7 ].
  
  

Finally, sortEvens should return None (as mutating functions generally do).
  
  

So we get:

```

    L = [ 1, 8, 4, 9, -2, 7 ]
    assert(sortEvens(L) == None)
    assert(L == [ 1, -2, 4, 9, 8, 7 ])

```
"""

def sortEvens(L):
    evens = sorted([x for x in L if x % 2 == 0])
    even_index = 0

    for i in range(len(L)):
        if L[i] % 2 == 0:
            L[i] = evens[even_index]
            even_index += 1

    return None

def testSortEvens():
    print('Testing sortEvens()...', end='')
    L = [ 1, 8, 4, 9, -2, 7 ]
    assert(sortEvens(L) == None)
    assert(L == [ 1, -2, 4, 9, 8, 7 ])

    L = [1, 4, 3, 2, 5]
    assert(sortEvens(L) == None)
    assert(L == [1, 2, 3, 4, 5])

    L = [1, 3, 2, 5]
    assert(sortEvens(L) == None)
    assert(L == [1, 3, 2, 5])

    L = [3, 6, 4, -2, 8, 4, 0, 5]
    assert(sortEvens(L) == None)
    assert(L == [3, -2, 0, 4, 4, 6, 8, 5])

    L = [1, 3, 5]
    assert(sortEvens(L) == None)
    assert(L == [1, 3, 5])

    L = [ ]
    assert(sortEvens(L) == None)
    assert(L == [ ])
    print('Passed!')

def main():
    testSortEvens()

main()