# -*- coding: utf-8 -*-
"""Level 2 isNearlySorted.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PRKAJ0TGiDcmS7woVr4UnU_YCcnWzcye

Background: We say that a list is "nearly\-sorted" (a coined
 term) if it is not sorted, and it requires exactly one swap of two of
 its values to become sorted from least to greatest. For example,
 `L = [2, 7, 5, 4]` is nearly\-sorted because swapping
 `L[1]` and `L[3]` results in the sorted list
 `[2, 4, 5, 7]`. However, `L = [2, 3, 1]` is not
 nearly\-sorted because it requires at least two swaps to become
 sorted. Additionally, `L = [1, 2, 3]` is not nearly\-sorted
 since it is already sorted.




 With this in mind, write the function `isNearlySorted(L)`
 that takes a list of integers `L` and returns
 `False` if the list is not nearly\-sorted. If the list is
 nearly\-sorted, the function returns the list `[i, j]`,
 where `i < j` and swapping the values at indices
 `i` and `j` would make the list sorted.




 So for the examples above, `isNearlySorted([2, 7, 5, 4])`
 returns `[1, 3]` and `isNearlySorted([1, 2, 3])`
 returns `False`. Notice for the first example that the function
 returns a list instead of True.




 Note: Your function should be non\-mutating.
"""

import copy

def isNearlySorted(L):
    if len(L) < 2:
        return False

    sorted_L = sorted(L)
    diff_indices = [i for i in range(len(L)) if L[i] != sorted_L[i]]

    if len(diff_indices) == 2:
        return diff_indices
    else:
        return False

def testIsNearlySorted():
    print('Testing isNearlySorted()...', end='')
    assert(isNearlySorted([2, 7, 5, 4]) == [1, 3])
    assert(isNearlySorted([2, 3, 1]) == False)
    assert(isNearlySorted([1, 2, 3]) == False)
    assert(isNearlySorted([-1, 1, 0, 5]) == [1, 2])
    assert(isNearlySorted([5, 6, 9, 8, 8]) == [2, 4])
    assert(isNearlySorted([2, 1]) == [0, 1])
    assert(isNearlySorted([3, 3]) == False)
    assert(isNearlySorted([2]) == False)
    assert(isNearlySorted([]) == False)

    # Verify that the function is non-mutating
    L = [2, 7, 5, 4]
    isNearlySorted(L)
    assert(L == [2, 7, 5, 4])
    print('Passed!')

def main():
    testIsNearlySorted()

main()