# -*- coding: utf-8 -*-
"""Level 2 repeatingPattern.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YqghbGhjSw_fcAFqGCkharn3q2G25Y1J

Background: We will say that a `list` `L` includes a repeating
 pattern if it contains at least 2 values, and there is some list `M` that
 is shorter than `L`, and `L` equals repeated copies of `M`.




 For example, if `L = [1, 2, 1, 2]`, then `L` includes the
 repeating pattern `M = [1, 2]`, because
 `L = M * 2`.




 It is possible for a list to contain multiple repeating patterns. For
 example, if `L = [1, 2, 1, 2, 1, 2, 1, 2]`, then
 `M = [1, 2]` is a repeating
 pattern, because `L = M * 4`. But
 `N = [1, 2, 1, 2]` is also a repeating pattern, becuase
 `L = N * 2`. In this case, use the shortest such pattern.
 So we will say that `L` contains the repeating pattern
 `[1, 2]`.




 With this in mind, write the function `repeatingPattern(L)`,
 which takes a list `L` and returns the shortest repeating pattern in `L`,
 if there is one. If `L` does not contain a repeating pattern, return
 `None`.




 Hints:
 * If `M` is the repeating pattern of `L`, then the length of `L` must
 be a multiple of the length of `M`. For example, if `L` is of
 length 6, then the pattern must be of length 1, 2, or 3\.
* Remember that functions must be non\-mutating by default. So
 the `list` `L` cannot be
 mutated by your function.
"""

def repeatingPattern(L):
    if len(L) < 2:
        return None

    for size in range(1, len(L)//2 + 1):
        if len(L) % size == 0:
            pattern = L[:size]
            if pattern * (len(L) // size) == L:
                return pattern

    return None

def testRepeatingPattern():
    print('Testing repeatingPattern()...', end='')
    assert(repeatingPattern([1,2,1,2]) == [1,2])
    assert(repeatingPattern([1,2,1,2,1,2,1,2])==[1,2])
    assert(repeatingPattern([1,2,3,1,2,3]) == [1,2,3])
    assert(repeatingPattern([1,1]) == [1])
    assert(repeatingPattern([]) == None)
    assert(repeatingPattern([42]) == None)
    assert(repeatingPattern([1,2,3,1,2]) == None)
    assert(repeatingPattern([121,212,12]) == None)
    L = [1,2,3,4]
    assert(repeatingPattern(L*20) == L)

    # Finally, verify that the function is non-mutating
    L = [1,2,1,2]
    repeatingPattern(L)
    assert(L == [1,2,1,2])
    print('Passed!')

def main():
    testRepeatingPattern()

main()